export const LANGUAGES = [
  { title: "Abkhazian", value: "ab" },
  { title: "Acehnese", value: "ace" },
  { title: "Acehnese (Jawoë)", value: "ace-arab" },
  { title: "Acehnese (Jawoë) (BCP 47)", value: "ace-Arab" },
  { title: "Acehnese (Latin)", value: "ace-latn" },
  { title: "Acehnese (Latin) (BCP 47)", value: "ace-Latn" },
  { title: "Adyghe", value: "ady" },
  { title: "Afar", value: "aa" },
  { title: "Afrikaans", value: "af" },
  { title: "Aiton", value: "aio" },
  { title: "Aiton (Myanmar)", value: "aio-mymr" },
  { title: "Aiton (Myanmar) (BCP 47)", value: "aio-Mymr" },
  { title: "Akha", value: "ahk" },
  { title: "Akan", value: "ak" },
  { title: "Albanian", value: "sq" },
  { title: "Albanian (Arvanitika)", value: "aat" },
  { title: "Albanian (Arvanitika, Greek)", value: "aat-grek" },
  { title: "Albanian (Arvanitika, Greek) (BCP 47)", value: "aat-Grek" },
  { title: "Albanian (Gheg)", value: "aln" },
  { title: "Albanian (Tosk)", value: "als" },
  { title: "Alsatian/Swiss German", value: "gsw" },
  { title: "Amharic", value: "am" },
  { title: "Angika/अंगिका", value: "anp" },
  { title: "Anishinaabe/Ojibwe", value: "oj" },
  { title: "Arabic/العربية", value: "ar" },
  { title: "Arabic (Modern Standard)/العربية الفصحى الحديثة", value: "arb" },
  { title: "Arabic (Algerian)/الدارجة الجزائرية", value: "arq" },
  { title: "Arabic (Andalusian)/العربية الأندلسية", value: "xaa" },
  { title: "Arabic (Bahrani)/العربية البحرانية", value: "abv" },
  { title: "Arabic (Chadian)/لهجة تشادية", value: "shu" },
  { title: "Arabic (Dhofari)", value: "adf" },
  { title: "Arabic (Egyptian)/مصرى", value: "arz" },
  { title: "Arabic (Gulf)/خليجي/اللهجة الخليجية", value: "afb" },
  { title: "Arabic (Hadhrami)/اللهجة الحضرمية", value: "ayh" },
  { title: "Arabic (Hassaniya)/حسانية", value: "mey" },
  { title: "Arabic (Hejazi)/حجازي", value: "acw" },
  { title: "Arabic (Moroccan)/العربية المغربية الدارجة", value: "ary" },
  { title: "Arabic (Judeo-Iraqi)/ערבית יהודית/عربية يهودية", value: "yhd" },
  { title: "Arabic (Judeo-Moroccan)/العربية المغربية الدارجة", value: "aju" },
  { title: "Arabic (Judeo-Yemeni)/תימנית-יהודית", value: "jye" },
  { title: "Arabic (Levantine)/شامي", value: "apc" },
  { title: "Arabic (Levantine Bedawi)", value: "avl" },
  { title: "Arabic (Libyan)/ليبي", value: "ayl" },
  { title: "Arabic (Najdi)/نجدي", value: "ars" },
  { title: "Arabic (North Mesopotamian (Qeltu))/لهجة موصلية", value: "ayp" },
  { title: "Arabic (Omani)/اللهجة العمانية", value: "acx" },
  { title: "Arabic (Saʽīdi (Upper Egyptian))/صعيدى", value: "aec" },
  { title: "Arabic (Sanʽani)", value: "ayn" },
  { title: "Arabic (Shihhi)/اللهجة الشحية", value: "ssh" },
  { title: "Arabic (Sicilian)/العربية الصقلية", value: "sqr" },
  { title: "Arabic (South Mesopotamian (Gelet))/اللهجة العراقية", value: "acm" },
  { title: "Arabic (Southern Yemeni)/لهجة تعزية عدنية", value: "acq" },
  { title: "Arabic (Sudanese)/لهجة سودانية", value: "apd" },
  { title: "Arabic (Tunisian)/تونسي", value: "aeb" },
  { title: "Aragonese", value: "an" },
  { title: "Aramaic", value: "arc" },
  { title: "Arbëreshe", value: "aae" },
  { title: "Armenian", value: "hy" },
  { title: "Aromanian", value: "rup" },
  { title: "Arpitan/Patois/Franco-Provençal", value: "frp" },
  { title: "Aso Chin", value: "csh" },
  { title: "Aso Chin (Myanmar)", value: "csh-mymr" },
  { title: "Aso Chin (Myanmar) (BCP 47)", value: "csh-Mymr" },
  { title: "Assamese", value: "as" },
  { title: "Asturian", value: "ast" },
  { title: "Asu", value: "asa" },
  { title: "Avar/Avaric", value: "av" },
  { title: "Avar/Avaric (Old)", value: "oav" },
  { title: "Avestan", value: "ae" },
  { title: "Awa", value: "vwa" },
  { title: "Aymara", value: "ay" },
  { title: "Azerbaijani", value: "az" },
  { title: "Azerbaijani (Cyrillic)", value: "az-cyrl" },
  { title: "Azerbaijani (Cyrillic) (BCP 47)", value: "az-Cyrl" },
  { title: "Azerbaijani (Latin)", value: "az-latn" },
  { title: "Azerbaijani (Latin) (BCP 47)", value: "az-Latn" },
  { title: "Bakhtiari/بختياري", value: "bqi" },
  { title: "Balinese", value: "ban" },
  { title: "Balinese (Aksara Bali)", value: "ban-bali" },
  { title: "Balinese (Aksara Bali) (BCP 47)", value: "ban-Bali" },
  { title: "Balinese (Latin)", value: "ban-latn" },
  { title: "Balinese (Latin) (BCP 47)", value: "ban-Latn" },
  { title: "Balti", value: "bft" },
  { title: "Balti (Arabic)", value: "bft-arab" },
  { title: "Balti (Arabic) (BCP 47)", value: "bft-Arab" },
  { title: "Balti (Tibetan)", value: "bft-tibt" },
  { title: "Balti (Tibetan) (BCP 47)", value: "bft-Tibt" },
  { title: "Bambara", value: "bm" },
  { title: "Bashkir", value: "ba" },
  { title: "Basque", value: "eu" },
  { title: "Batak", value: "btk" },
  { title: "Batak (Latin)", value: "btk-latn" },
  { title: "Batak (Latin) (BCP 47)", value: "btk-Latn" },
  { title: "Batak (Surat Batak)", value: "btk-batk" },
  { title: "Batak (Surat Batak) (BCP 47)", value: "btk-Batk" },
  { title: "Belarusian", value: "be" },
  { title: "Bemba", value: "bem" },
  { title: "Bena", value: "bez" },
  { title: "Bengali", value: "bn" },
  { title: "Berber", value: "ber" },
  { title: "Berber (Arabic)", value: "ber-arab" },
  { title: "Berber (Arabic) (BCP 47)", value: "ber-Arab" },
  { title: "Berber (Latin)", value: "ber-latn" },
  { title: "Berber (Latin) (BCP 47)", value: "ber-Latn" },
  { title: "Berber (Tifinagh)", value: "ber-tfng" },
  { title: "Berber (Tifinagh) (BCP 47)", value: "ber-Tfng" },
  { title: "Bghai/Bwe", value: "bwe" },
  { title: "Bhojpuri/भोजपुरी", value: "bho" },
  { title: "Bihari/बिहारी", value: "bh" },
  { title: "Bislama", value: "bi" },
  { title: "Bisu", value: "bzi" },
  { title: "Blang", value: "blr" },
  { title: "Bosnian", value: "bs" },
  { title: "Bosnian (Cyrillic)", value: "bs-cyrl" },
  { title: "Bosnian (Cyrillic) (BCP 47)", value: "bs-Cyrl" },
  { title: "Bosnian (Latin)", value: "bs-latn" },
  { title: "Bosnian (Latin) (BCP 47)", value: "bs-Latn" },
  { title: "Bote-Majhi", value: "bmj" },
  { title: "Breton", value: "br" },
  { title: "Bru (Eastern)", value: "bru" },
  { title: "Bru (Western)", value: "brv" },
  { title: "Buginese", value: "bug" },
  { title: "Buginese (Latin)", value: "bug-latn" },
  { title: "Buginese (Latin) (BCP 47)", value: "bug-Latn" },
  { title: "Buginese (Lontara)", value: "bug-bugi" },
  { title: "Buginese (Lontara) (BCP 47)", value: "bug-Bugi" },
  { title: "Buginese (Aksara Makassar Kuno)", value: "bug-maka" },
  { title: "Buginese (Aksara Makassar Kuno) (BCP 47)", value: "bug-Maka" },
  { title: "Buksa", value: "tkb" },
  { title: "Bulgarian", value: "bg" },
  { title: "Burmese (Unicode)", value: "my" },
  { title: "Burmese (Zawgyi)", value: "my-qaag" },
  { title: "Burmese (Zawgyi) (BCP 47)", value: "my-Qaag" },
  { title: "Cantonese", value: "yue" },
  { title: "Cantonese (Simplified Han)", value: "yue-hans" },
  { title: "Cantonese (Simplified Han) (BCP 47)", value: "yue-Hans" },
  { title: "Cantonese (Traditional Han)", value: "yue-hant" },
  { title: "Cantonese (Traditional Han) (BCP 47)", value: "yue-Hant" },
  { title: "Catalan/Valencian", value: "ca" },
  { title: "Chamorro", value: "ch" },
  { title: "Chao-bon/ชาวบน/Nyah Kur/ญัฮกุร", value: "cbn" },
  { title: "Chechen", value: "ce" },
  { title: "Cherokee", value: "chr" },
  { title: "Chicewa/Chewa/Nyanja", value: "ny" },
  { title: "Chigga", value: "cgg" },
  { title: "Chinese", value: "zh" },
  { title: "Chinese (Simplified Han)", value: "zh-hans" },
  { title: "Chinese (Simplified Han) (BCP 47)", value: "zh-Hans" },
  { title: "Chinese (Traditional Han)", value: "zh-hant" },
  { title: "Chinese (Traditional Han) (BCP 47)", value: "zh-Hant" },
  { title: "Chong/Samre/ภาษาชอง", value: "cog" },
  { title: "Church Slavonic", value: "cu" },
  { title: "Chuvash", value: "cv" },
  { title: "Cornish", value: "kw" },
  { title: "Corsican", value: "co" },
  { title: "Cree", value: "cr" },
  { title: "Croatian", value: "hr" },
  { title: "Czech", value: "cs" },
  { title: "Danish", value: "da" },
  { title: "Danuwar", value: "dhw" },
  { title: "Darai", value: "dry" },
  { title: "Dari (Afghan Farsi/Afghan Persian)/دری", value: "prs" },
  { title: "Divehi/Dhivehi/Maldivian", value: "dv" },
  { title: "Dutch", value: "nl" },
  { title: "Dzongkha", value: "dz" },
  { title: "Embu", value: "ebu" },
  { title: "English", value: "en" },
  { title: "Esperanto", value: "eo" },
  { title: "Estonian", value: "et" },
  { title: "Ewe", value: "ee" },
  { title: "Extremaduran", value: "ext" },
  { title: "Fala", value: "fax" },
  { title: "Faroese", value: "fo" },
  { title: "Farsi/Persian/فارسی", value: "fa" },
  { title: "Fijian", value: "fj" },
  { title: "Filipino", value: "fil" },
  { title: "Finnish", value: "fi" },
  { title: "French", value: "fr" },
  { title: "Frisian (Eastern)", value: "mis" },
  { title: "Frisian (Northern)", value: "frr" },
  { title: "Frisian (Saterland)", value: "stq" },
  { title: "Frisian (Western)", value: "fy" },
  { title: "Friulian", value: "fur" },
  { title: "Fula/Fulah/Pulaar/Pular", value: "ff" },
  { title: "Galician", value: "gl" },
  { title: "Ganda/Luganda", value: "lg" },
  { title: "Georgian/ქართული ენა", value: "ka" },
  { title: "German", value: "de" },
  { title: "Gikuyu/Kikuyu", value: "ki" },
  { title: "Gilaki/گیلکی", value: "glk" },
  { title: "Gong", value: "ugo" },
  { title: "Greek (Ancient)", value: "grc" },
  { title: "Greek (Modern)", value: "el" },
  { title: "Greenlandic/Kalaallisut", value: "kl" },
  { title: "Guarani", value: "gn" },
  { title: "Guernésiais and Jèrriais", value: "nrf" },
  { title: "Gujarati", value: "gu" },
  { title: "Gusii", value: "guz" },
  { title: "Haitian Creole", value: "ht" },
  { title: "Hausa", value: "ha" },
  { title: "Hausa (Arabic)", value: "ha-arab" },
  { title: "Hausa (Arabic) (BCP 47)", value: "ha-Arab" },
  { title: "Hausa (Latin)", value: "ha-latn" },
  { title: "Hausa (Latin) (BCP 47)", value: "ha-Latn" },
  { title: "Hawaiian", value: "haw" },
  { title: "Hebrew/עברית", value: "he" },
  { title: "Herero", value: "hz" },
  { title: "Hindi/हिन्दी", value: "hi" },
  { title: "Hiri Motu/Police Motu", value: "ho" },
  { title: "Hmong", value: "hmn" },
  { title: "Hmong Daw", value: "mww" },
  { title: "Hokkien/Min Nan", value: "nan" },
  { title: "Hokkien/Min Nan (Simplified Han)", value: "nan-hans" },
  { title: "Hokkien/Min Nan (Simplified Han) (BCP 47)", value: "nan-Hans" },
  { title: "Hokkien/Min Nan (Traditional Han)", value: "nan-hant" },
  { title: "Hokkien/Min Nan (Traditional Han) (BCP 47)", value: "nan-Hant" },
  { title: "Hungarian", value: "hu" },
  { title: "Hyolmo/Yolmo", value: "scp" },
  { title: "Icelandic", value: "is" },
  { title: "Ido", value: "io" },
  { title: "Igbo", value: "ig" },
  { title: "Indonesian", value: "id" },
  { title: "Interlingua (International Auxiliary Language Association)", value: "ia" },
  { title: "Interlingue/Occidental", value: "ie" },
  { title: "Inuinnaqtun", value: "ikt" },
  { title: "Inuktitut", value: "iu" },
  { title: "Inuktitut (Latin)", value: "iu-latn" },
  { title: "Inuktitut (Latin) (BCP 47)", value: "iu-Latn" },
  { title: "Inupiaq", value: "ik" },
  { title: "Irish Gaelic", value: "ga" },
  { title: "Isan", value: "tts" },
  { title: "Istriot", value: "ist" },
  { title: "Istro-Romanian", value: "ruo" },
  { title: "Italian", value: "it" },
  { title: "Japanese", value: "ja" },
  { title: "Javanese", value: "jv" },
  { title: "Javanese (Aksara Jawa)", value: "jv-java" },
  { title: "Javanese (Aksara Jawa) (BCP 47)", value: "jv-Java" },
  { title: "Javanese (Latin)", value: "jv-latn" },
  { title: "Javanese (Latin) (BCP 47)", value: "jv-Latn" },
  { title: "Javanese (Pégon)", value: "jv-arab" },
  { title: "Javanese (Pégon) (BCP 47)", value: "jv-Arab" },
  { title: "Jinghpaw/Jinghpo/Kachin", value: "kac" },
  { title: "Jirel", value: "jul" },
  { title: "Jirel (Devanagari)", value: "jul-deva" },
  { title: "Jirel (Devanagari) (BCP 47)", value: "jul-Deva" },
  { title: "Jirel (Tibetan)", value: "jul-tibt" },
  { title: "Jirel (Tibetan) (BCP 47)", value: "jul-Tibt" },
  { title: "Kabuverdianu", value: "kea" },
  { title: "Kabyle", value: "kab" },
  { title: "Kabyle (Arabic)", value: "kab-arab" },
  { title: "Kabyle (Arabic) (BCP 47)", value: "kab-Arab" },
  { title: "Kabyle (Latin)", value: "kab-latn" },
  { title: "Kabyle (Latin) (BCP 47)", value: "kab-Latn" },
  { title: "Kabyle (Tifinagh)", value: "kab-tfng" },
  { title: "Kabyle (Tifinagh) (BCP 47)", value: "kab-Tfng" },
  { title: "Kalaktang Monpa", value: "kkf" },
  { title: "Kalenjin", value: "kln" },
  { title: "Kamba", value: "kam" },
  { title: "Kannada", value: "kn" },
  { title: "Kanuri", value: "kr" },
  { title: "Karen", value: "kar" },
  { title: "Karen (Mopwa)", value: "jkm" },
  { title: "Karen (Paku)", value: "jkp" },
  { title: "Karen (S'gaw)", value: "ksw" },
  { title: "Karen (S'gaw, Myanmar)", value: "ksw-mymr" },
  { title: "Karen (S'gaw, Myanmar) (BCP 47)", value: "ksw-Mymr" },
  { title: "Karen (Wewaw)", value: "wea" },
  { title: "Kashmiri/कॉशुर/کٲشُر", value: "ks" },
  { title: "Kashmiri (Arabic)/کٲشُر", value: "ks-arab" },
  { title: "Kashmiri (Arabic) (BCP 47)/کٲشُر", value: "ks-Arab" },
  { title: "Kashmiri (Devanagari)/कॉशुर", value: "ks-deva" },
  { title: "Kashmiri (Devanagari) (BCP 47)/कॉशुर", value: "ks-Deva" },
  { title: "Kashmiri (Latin)", value: "ks-latn" },
  { title: "Kashmiri (Latin) (BCP 47)", value: "ks-Latn" },
  { title: "Kashubian", value: "csb" },
  { title: "Katang (Northern)", value: "ncq" },
  { title: "Katang (Southern)", value: "sct" },
  { title: "Kayah", value: "kyu" },
  { title: "Kayah (Myanmar)", value: "kyu-mymr" },
  { title: "Kayah (Myanmar) (BCP 47)", value: "kyu-Mymr" },
  { title: "Kazakh", value: "kk" },
  { title: "Kazakh (Cyrillic)", value: "kk-cyrl" },
  { title: "Kazakh (Cyrillic) (BCP 47)", value: "kk-Cyrl" },
  { title: "Kazakh (Latin)", value: "kk-latn" },
  { title: "Kazakh (Latin) (BCP 47)", value: "kk-Latn" },
  { title: "Kensiu", value: "kns" },
  { title: "Khamet/Lamet", value: "lbn" },
  { title: "Khamti", value: "kht" },
  { title: "Khamti (Myanmar)", value: "kht-mymr" },
  { title: "Khamti (Myanmar) (BCP 47)", value: "kht-Mymr" },
  { title: "Khasi", value: "kha" },
  { title: "Khasi (Bengali-Assamese)", value: "kha-beng" },
  { title: "Khasi (Bengali-Assamese) (BCP 47)", value: "kha-Beng" },
  { title: "Khasi (Latin)", value: "kha-latn" },
  { title: "Khasi (Latin) (BCP 47)", value: "kha-Latn" },
  { title: "Khmer", value: "km" },
  { title: "Khmer Surin", value: "kxm" },
  { title: "Khmu", value: "kjg" },
  { title: "Khmu (Buddhist)", value: "khf" },
  { title: "Khua", value: "xhv" },
  { title: "Khün/ไทเขิน", value: "kkh" },
  { title: "Khün (Tai Tham)", value: "kkh-lana" },
  { title: "Khün (Tai Tham) (BCP 47)", value: "kkh-Lana" },
  { title: "Khün (Thai)/ไทเขิน", value: "kkh-thai" },
  { title: "Khün (Thai) (BCP 47)/ไทเขิน", value: "kkh-Thai" },
  { title: "Kikongo/Kongo", value: "kg" },
  { title: "Kinyarwanda", value: "rw" },
  { title: "Kirundi/Rundi", value: "rn" },
  { title: "Kiswahili/Swahili", value: "sw" },
  { title: "Komi", value: "kv" },
  { title: "Konkani", value: "kok" },
  { title: "Konkani (Goan)", value: "gom" },
  { title: "Konkani (Maharashtrian)", value: "knn" },
  { title: "Konkani (Devanagari)", value: "kok-deva" },
  { title: "Konkani (Devanagari) (BCP 47)", value: "kok-Deva" },
  { title: "Konkani (Kannada)", value: "kok-knda" },
  { title: "Konkani (Kannada) (BCP 47)", value: "kok-Knda" },
  { title: "Konkani (Latin)", value: "kok-latn" },
  { title: "Konkani (Latin) (BCP 47)", value: "kok-Latn" },
  { title: "Konkani (Malayalam)", value: "kok-mlym" },
  { title: "Konkani (Malayalam) (BCP 47)", value: "kok-Mlym" },
  { title: "Konkani (Perso-Arabic)", value: "kok-arab" },
  { title: "Konkani (Perso-Arabic) (BCP 47)", value: "kok-Arab" },
  { title: "Korean", value: "ko" },
  { title: "Koyra Chiini", value: "khq" },
  { title: "Koyraboro Senni", value: "ses" },
  { title: "Kuanyama/Kwanyama", value: "kj" },
  { title: "Kudmali/কুড়মালি/কুর্মালী/कुड़मालि/कुरमालि", value: "kyw" },
  { title: "Kumhali/कुमाल भाषा/कुमाले कुरा", value: "kra" },
  { title: "Kurdish", value: "ku" },
  { title: "Kurdish (Central)/کوردی سورانی", value: "ckb" },
  { title: "Kurdish (Hawar)", value: "ku-latn" },
  { title: "Kurdish (Hawar) (BCP 47)", value: "ku-Latn" },
  { title: "Kurdish (Kurmanji)", value: "ku-cyrl" },
  { title: "Kurdish (Kurmanji) (BCP 47)", value: "ku-Cyrl" },
  { title: "Kurdish (Northern)", value: "kmr" },
  { title: "Kurdish (Sorani)", value: "ku-arab" },
  { title: "Kurdish (Sorani) (BCP 47)", value: "ku-Arab" },
  { title: "Kuy/Kuay/ภาษากูย", value: "kdt" },
  { title: "Kyrgyz", value: "ky" },
  { title: "K’iche", value: "quc" },
  { title: "Ladakhi", value: "lbi" },
  { title: "Lahu", value: "lhu" },
  { title: "Lahu Kucong", value: "lkc" },
  { title: "Lahu Shi", value: "lhi" },
  { title: "Langi", value: "lag" },
  { title: "Lao", value: "lo" },
  { title: "Latin", value: "la" },
  { title: "Lawa (Eastern)", value: "lwl" },
  { title: "Lawa (Western)", value: "lcp" },
  { title: "Latvian", value: "lv" },
  { title: "Ligurian", value: "lij" },
  { title: "Limburgan/Limburger/Limburgish", value: "li" },
  { title: "Lingala", value: "ln" },
  { title: "Lisu", value: "lis" },
  { title: "Lithuanian", value: "lt" },
  { title: "Livonian", value: "liv" },
  { title: "Luba-Katanga/Luba-Shaba", value: "lu" },
  { title: "Luo", value: "luo" },
  { title: "Luxembourgish/Letzeburgesch", value: "lb" },
  { title: "Macedonian", value: "mk" },
  { title: "Machame", value: "jmc" },
  { title: "Magahi/मगही", value: "mag" },
  { title: "Maithili/मैथिली", value: "mai" },
  { title: "Majhi/माझी", value: "mjz" },
  { title: "Makonde", value: "kde" },
  { title: "Malagasy", value: "mg" },
  { title: "Malay", value: "ms" },
  { title: "Malay (Jawi)", value: "ms-arab" },
  { title: "Malay (Jawi) (BCP 47)", value: "ms-Arab" },
  { title: "Malay (Pattani)", value: "mfa" },
  { title: "Malay (Rumi)", value: "ms-latn" },
  { title: "Malay (Rumi) (BCP 47)", value: "ms-Latn" },
  { title: "Malayalam", value: "ml" },
  { title: "Maltese", value: "mt" },
  { title: "Mandaic (Classical)", value: "myz" },
  { title: "Mandaic (Modern)", value: "mid" },
  { title: "Manipuri", value: "mni" },
  { title: "Manipuri (Bengali)", value: "mni-beng" },
  { title: "Manipuri (Bengali) (BCP 47)", value: "mni-Beng" },
  { title: "Manipuri (Meitei Mayek)", value: "mni-mtei" },
  { title: "Manipuri (Meitei Mayek) (BCP 47)", value: "mni-Mtei" },
  { title: "Manipuri (Old)", value: "omp" },
  { title: "Manx Gaelic", value: "gv" },
  { title: "Māori", value: "mi" },
  { title: "Marathi/मराठी", value: "mr" },
  { title: "Marshallese", value: "mh" },
  { title: "Mapudungun", value: "arn" },
  { title: "Masai", value: "mas" },
  { title: "Mazanderani/مازِرونی", value: "mzn" },
  { title: "Mende", value: "men" },
  { title: "Meru", value: "mer" },
  { title: "Mirandese", value: "mwl" },
  { title: "Mizo", value: "lus" },
  { title: "Mlabri/Yumbri", value: "mra" },
  { title: "Mohawk", value: "moh" },
  { title: "Moken", value: "mwt" },
  { title: "Moldavian/Moldovan (Deprecated)", value: "mo" },
  { title: "Mon (Modern)", value: "mnw" },
  { title: "Mon (Modern, Myanmar)", value: "mnw-mymr" },
  { title: "Mon (Modern, Myanmar) (BCP 47)", value: "mnw-Mymr" },
  { title: "Mon (Old)", value: "omx" },
  { title: "Mongolian", value: "mn" },
  { title: "Mongolian (Cyrillic)", value: "mn-cyrl" },
  { title: "Mongolian (Cyrillic) (BCP 47)", value: "mn-Cyrl" },
  { title: "Mongolian (Traditional Script)", value: "mn-mong" },
  { title: "Mongolian (Traditional Script) (BCP 47)", value: "mn-Mong" },
  { title: "Montenegrin", value: "cnr" },
  { title: "Montenegrin (Cyrillic)", value: "cnr-cyrl" },
  { title: "Montenegrin (Cyrillic) (BCP 47)", value: "cnr-Cyrl" },
  { title: "Montenegrin (Latin)", value: "cnr-latn" },
  { title: "Montenegrin (Latin) (BCP 47)", value: "cnr-Latn" },
  { title: "Morisyen", value: "mfe" },
  { title: "Mpi", value: "mpz" },
  { title: "Nagpuri (Sadri)/नगपुरी", value: "sck" },
  { title: "Nagpuri (Oraon Sadri)/सादरी", value: "sdr" },
  { title: "Nama", value: "naq" },
  { title: "Nauru", value: "na" },
  { title: "Navajo", value: "nv" },
  { title: "Ndonga", value: "ng" },
  { title: "Ndebele (Northern)", value: "nd" },
  { title: "Ndebele (Southern)", value: "nr" },
  { title: "Neapolitan", value: "nap" },
  { title: "Nepali/नेपाली", value: "ne" },
  { title: "Nias", value: "nia" },
  { title: "Norwegian", value: "no" },
  { title: "Norwegian Bokmål", value: "nb" },
  { title: "Norwegian Nynorsk", value: "nn" },
  { title: "Nuosu/Sichuan Yi", value: "ii" },
  { title: "Nyankole", value: "nyn" },
  { title: "Nyeu/Yoe", value: "nyl" },
  { title: "N’Ko", value: "nqo" },
  { title: "Occitan (post-1500)", value: "oc" },
  { title: "Occitan (Auvergnat)", value: "auv" },
  { title: "Occitan (Gascon)", value: "gsc" },
  { title: "Occitan (Languedocien)", value: "lnc" },
  { title: "Occitan (Limousin)", value: "lms" },
  { title: "Occitan (Provençal)", value: "prv" },
  { title: "Oriya", value: "or" },
  { title: "Oromo", value: "om" },
  { title: "Ossetian", value: "os" },
  { title: "Padaung", value: "pdu" },
  { title: "Palaung (Ruching)", value: "pce" },
  { title: "Palaung (Rumai)", value: "rbb" },
  { title: "Palaung (Shwe)", value: "pll" },
  { title: "Pāli", value: "pi" },
  { title: "Panchpargania", value: "tdb" },
  { title: "Papiamento", value: "pap" },
  { title: "Parauk", value: "prk" },
  { title: "Pashto/پښتو", value: "ps" },
  { title: "Pa'O/Taungthu'", value: "blk" },
  { title: "Phake", value: "phk" },
  { title: "Phake (Myanmar)", value: "phk-mymr" },
  { title: "Phake (Myanmar) (BCP 47)", value: "phk-Mymr" },
  { title: "Phu Thai/ภาษาผู้ไท", value: "pht" },
  { title: "Phuan/พวน", value: "phu" },
  { title: "Phuan (Lao)/ພວນ", value: "phu-laoo" },
  { title: "Phuan (Lao) (BCP 47)/ພວນ", value: "phu-Laoo" },
  { title: "Phuan (Tai Tham)", value: "phu-lana" },
  { title: "Phuan (Tai Tham) (BCP 47)", value: "phu-Lana" },
  { title: "Phuan (Thai)/พวน", value: "phu-thai" },
  { title: "Phuan (Thai) (BCP 47)/พวน", value: "phu-Thai" },
  { title: "Piedmontese", value: "pms" },
  { title: "Polish", value: "pl" },
  { title: "Portuguese", value: "pt" },
  { title: "Prussian (Old)", value: "prg" },
  { title: "Punjabi", value: "pa" },
  { title: "Punjabi (Gurmukhi)", value: "pa-guru" },
  { title: "Punjabi (Gurmukhi) (BCP 47)", value: "pa-Guru" },
  { title: "Punjabi (Shahmukhi)/", value: "pa-arab" },
  { title: "Punjabi (Shahmukhi) (BCP 47)", value: "pa-Arab" },
  { title: "Punjabi (Western)/پنجابی", value: "pnb" },
  { title: "Pwo (Eastern)", value: "kjp" },
  { title: "Pwo (Northern)", value: "pww" },
  { title: "Pwo (Phrae)", value: "kjt" },
  { title: "Pwo (Western)", value: "pwo" },
  { title: "Quechua", value: "qu" },
  { title: "Queretaro Otomi", value: "otq" },
  { title: "Rejang", value: "rej" },
  { title: "Rejang (Aksara Rejang)", value: "rej-rjng" },
  { title: "Rejang (Aksara Rejang) (BCP 47)", value: "rej-Rjng" },
  { title: "Rejang (Latin)", value: "rej-latn" },
  { title: "Rejang (Latin) (BCP 47)", value: "rej-Latn" },
  { title: "Réunion Creole", value: "rcf" },
  { title: "Romansh", value: "rm" },
  { title: "Romanian/Moldavian/Moldovan", value: "ro" },
  { title: "Rombo", value: "rof" },
  { title: "Russian", value: "ru" },
  { title: "Rwa", value: "rwk" },
  { title: "Sa'och'", value: "scq" },
  { title: "Saek/ภาษาแสก/แถร̄ก", value: "skb" },
  { title: "Sakha/Yakut", value: "sah" },
  { title: "Samburu", value: "saq" },
  { title: "Sámi (Arjeplog/Pite)", value: "sje" },
  { title: "Sámi (Inari)", value: "smn" },
  { title: "Sámi (Lule)", value: "smj" },
  { title: "Sámi (Northern)", value: "se" },
  { title: "Sámi (Southern)", value: "sma" },
  { title: "Sámi (Skolt)", value: "sms" },
  { title: "Sámi (Ume)", value: "sju" },
  { title: "Samoan", value: "sm" },
  { title: "Samtao", value: "stu" },
  { title: "Sango", value: "sg" },
  { title: "Sanskrit", value: "sa" },
  { title: "Santali", value: "sat" },
  { title: "Santali (Devanagari)", value: "sat-deva" },
  { title: "Santali (Devanagari) (BCP 47)", value: "sat-Deva" },
  { title: "Santali (Ol Chiki)", value: "sat-olck" },
  { title: "Santali (Ol Chiki) (BCP 47)", value: "sat-Olck" },
  { title: "Saraiki/سرائیکی", value: "skr" },
  { title: "Sardinian", value: "sc" },
  { title: "Scots", value: "sco" },
  { title: "Scottish Gaelic", value: "gd" },
  { title: "Sena", value: "seh" },
  { title: "Serbian", value: "sr" },
  { title: "Serbian (Cyrillic)", value: "sr-cyrl" },
  { title: "Serbian (Cyrillic) (BCP 47)", value: "sr-Cyrl" },
  { title: "Serbian (Latin)", value: "sr-latn" },
  { title: "Serbian (Latin) (BCP 47)", value: "sr-Latn" },
  { title: "Serbo-Croatian", value: "sh" },
  { title: "Setswana/Tswana", value: "tn" },
  { title: "Shan", value: "shn" },
  { title: "Shan (Myanmar)", value: "shn-mymr" },
  { title: "Shan (Myanmar) (BCP 47)", value: "shn-Mymr" },
  { title: "Sherpa", value: "xsr" },
  { title: "Sherpa (Devanagari)", value: "xsr-deva" },
  { title: "Sherpa (Devanagari) (BCP 47)", value: "xsr-Deva" },
  { title: "Sherpa (Tibetan)", value: "xsr-tibt" },
  { title: "Sherpa (Tibetan) (BCP 47)", value: "xsr-Tibt" },
  { title: "Shona", value: "sn" },
  { title: "Sikkimese", value: "sip" },
  { title: "Silesian", value: "szl" },
  { title: "Sindhi/सिन्धी/سنڌي", value: "sd" },
  { title: "Sindhi (Arabic)/سنڌي", value: "sd-arab" },
  { title: "Sindhi (Arabic) (BCP 47)/سنڌي", value: "sd-Arab" },
  { title: "Sindhi (Devanagari)/सिन्धी", value: "sd-deva" },
  { title: "Sindhi (Devanagari) (BCP 47)/सिन्धी", value: "sd-Deva" },
  { title: "Singpho", value: "sgp" },
  { title: "Sinhala", value: "si" },
  { title: "Siswati/Swati", value: "ss" },
  { title: "Slovak", value: "sk" },
  { title: "Slovenian", value: "sl" },
  { title: "Sô", value: "sss" },
  { title: "Soga", value: "xog" },
  { title: "Somali", value: "so" },
  { title: "Sonha", value: "soi" },
  { title: "Sorbian (Lower)", value: "dsb" },
  { title: "Sorbian (Upper)", value: "hsb" },
  { title: "Sotho (Northern/Pedi/Sesotho sa Leboa)", value: "st" },
  { title: "Sotho (Southern/Sesotho)", value: "nso" },
  { title: "Southern Balochi/بلوچی مکرانی", value: "bcc" },
  { title: "Spanish", value: "es" },
  { title: "Sundanese", value: "su" },
  { title: "Sundanese (Aksara Sunda)", value: "su-sund" },
  { title: "Sundanese (Aksara Sunda) (BCP 47)", value: "su-Sund" },
  { title: "Sundanese (Aksara Jawa)", value: "su-java" },
  { title: "Sundanese (Aksara Jawa) (BCP 47)", value: "su-Java" },
  { title: "Sundanese (Latin)", value: "su-latn" },
  { title: "Sundanese (Latin) (BCP 47)", value: "su-Latn" },
  { title: "Sundanese (Pégon)", value: "su-arab" },
  { title: "Sundanese (Pégon) (BCP 47)", value: "su-Arab" },
  { title: "Swedish", value: "sv" },
  { title: "Syriac", value: "syr" },
  { title: "Tachelhit", value: "shi" },
  { title: "Tachelhit (Arabic)", value: "shi-arab" },
  { title: "Tachelhit (Arabic) (BCP 47)", value: "shi-Arab" },
  { title: "Tachelhit (Latin)", value: "shi-latn" },
  { title: "Tachelhit (Latin) (BCP 47)", value: "shi-Latn" },
  { title: "Tachelhit (Tifinagh)", value: "shi-tfng" },
  { title: "Tachelhit (Tifinagh) (BCP 47)", value: "shi-Tfng" },
  { title: "Tagalog", value: "tl" },
  { title: "Tahitian", value: "ty" },
  { title: "Tai Cung/Tai Ya", value: "cuu" },
  { title: "Tai Dam/ภาษาไทดำ", value: "blt" },
  { title: "Tai Dam (Tai Viet)", value: "blt-tavt" },
  { title: "Tai Dam (Tai Viet) (BCP 47)", value: "blt-Tavt" },
  { title: "Tai Dam (Thai)/ภาษาไทดำ", value: "blt-thai" },
  { title: "Tai Dam (Thai) (BCP 47)/ภาษาไทดำ", value: "blt-Thai" },
  { title: "Tai Laing", value: "tjl" },
  { title: "Tai Laing (Myanmar)", value: "tjl-mymr" },
  { title: "Tai Laing (Myanmar) (BCP 47)", value: "tjl-Mymr" },
  { title: "Tai Lue/ภาษาไทลื้อ", value: "khb" },
  { title: "Tai Lue (New Tai Lü)", value: "khb-talu" },
  { title: "Tai Lue (New Tai Lü) (BCP 47)", value: "khb-Talu" },
  { title: "Tai Lue (Tai Tham)", value: "khb-lana" },
  { title: "Tai Lue (Tai Tham) (BCP 47)", value: "khb-Lana" },
  { title: "Tai Lue (Thai)/ภาษาไทลื้อ", value: "khb-thai" },
  { title: "Tai Lue (Thai)/ภาษาไทลื้อ (BCP 47)", value: "khb-Thai" },
  { title: "Tai Nyaw/ไทญ้อ", value: "nyw" },
  { title: "Tai Yo/ไทญ้อ", value: "tyj" },
  { title: "Taita", value: "dav" },
  { title: "Tajik", value: "tg" },
  { title: "Tajik (Cyrillic)", value: "tg-cyrl" },
  { title: "Tajik (Cyrillic) (BCP 47)", value: "tg-Cyrl" },
  { title: "Tajik (Latin)", value: "tg-latn" },
  { title: "Tajik (Latin) (BCP 47)", value: "tg-Latn" },
  { title: "Taman", value: "tcl" },
  { title: "Tamazight", value: "tzm" },
  { title: "Tamazight (Arabic)", value: "tzm-arab" },
  { title: "Tamazight (Arabic) (BCP 47)", value: "tzm-Arab" },
  { title: "Tamazight (Latin)", value: "tzm-latn" },
  { title: "Tamazight (Latin) (BCP 47)", value: "tzm-Latn" },
  { title: "Tamazight (Tifinagh)", value: "tzm-tfng" },
  { title: "Tamazight (Tifinagh) (BCP 47)", value: "tzm-Tfng" },
  { title: "Tamil", value: "ta" },
  { title: "Tatar", value: "tt" },
  { title: "Telugu", value: "te" },
  { title: "Tetum", value: "tet" },
  { title: "Teso", value: "teo" },
  { title: "Thai/ภาษาไทย", value: "th" },
  { title: "Thai (Northern)/กำเมือง", value: "nod" },
  { title: "Thai (Northern, Tai Tham)", value: "nod-lana" },
  { title: "Thai (Northern, Tai Tham) (BCP 47)", value: "nod-Lana" },
  { title: "Thai (Northern, Thai)/กำเมือง", value: "nod-thai" },
  { title: "Thai (Northern, Thai) (BCP 47)/กำเมือง", value: "nod-Thai" },
  { title: "Thai (Southern)/ภาษาไทยถิ่นใต้/ภาษาตามโพร/ภาษาปักษ์ใต้/ภาษาใต้", value: "sou" },
  { title: "Tharu (Chitwania)", value: "the" },
  { title: "Tharu (Dangaura)", value: "thl" },
  { title: "Tharu (Kathariya)", value: "tkt" },
  { title: "Tharu (Kochila)", value: "thq" },
  { title: "Tharu (Rana)", value: "thr" },
  { title: "Thavưng/ทะวืง", value: "thm" },
  { title: "Tibetan", value: "bo" },
  { title: "Tigrinya", value: "ti" },
  { title: "Tongan", value: "to" },
  { title: "Tshangla", value: "tsj" },
  { title: "Tsonga", value: "ts" },
  { title: "Tuareg", value: "tmh" },
  { title: "Tuareg (Arabic)", value: "tmh-arab" },
  { title: "Tuareg (Arabic) (BCP 47)", value: "tmh-Arab" },
  { title: "Tuareg (Latin)", value: "tmh-latn" },
  { title: "Tuareg (Latin) (BCP 47)", value: "tmh-Latn" },
  { title: "Tuareg (Tifinagh)", value: "tmh-tfng" },
  { title: "Tuareg (Tifinagh) (BCP 47)", value: "tmh-Tfng" },
  { title: "Turkish", value: "tr" },
  { title: "Turkmen", value: "tk" },
  { title: "Twi", value: "tw" },
  { title: "Ukrainian", value: "uk" },
  { title: "Urak Lawoiʼ/อูรักลาโวยจ", value: "urk" },
  { title: "Urdu/اردو", value: "ur" },
  { title: "Uyghur/Uyghurche/Уйғурчә/ئۇيغۇرچە", value: "ug" },
  { title: "Uyghur (Arabic)/ئۇيغۇرچە", value: "ug-arab" },
  { title: "Uyghur (Arabic) (BCP 47)/ئۇيغۇرچە", value: "ug-Arab" },
  { title: "Uyghur (Cyrillic)/Уйғурчә", value: "ug-cyrl" },
  { title: "Uyghur (Cyrillic) (BCP 47)/Уйғурчә", value: "ug-Cyrl" },
  { title: "Uyghur (Latin)/Uyghurche", value: "ug-latn" },
  { title: "Uyghur (Latin) (BCP 47)/Uyghurche", value: "ug-Latn" },
  { title: "Uzbek", value: "uz" },
  { title: "Uzbek (Arabic)", value: "uz-arab" },
  { title: "Uzbek (Arabic) (BCP 47)", value: "uz-Arab" },
  { title: "Uzbek (Cyrillic)", value: "uz-cyrl" },
  { title: "Uzbek (Cyrillic) (BCP 47)", value: "uz-Cyrl" },
  { title: "Uzbek (Latin)", value: "uz-latn" },
  { title: "Uzbek (Latin) (BCP 47)", value: "uz-Latn" },
  { title: "Venda", value: "ve" },
  { title: "Venetian", value: "vec" },
  { title: "Vietnamese/Tiếng Việt", value: "vi" },
  { title: "Vo", value: "wbm" },
  { title: "Volapük", value: "vo" },
  { title: "Võro", value: "vro" },
  { title: "Vunjo", value: "vun" },
  { title: "Walloon", value: "wa" },
  { title: "Welsh", value: "cy" },
  { title: "Wolof", value: "wo" },
  { title: "Wu", value: "wuu" },
  { title: "Xhosa", value: "xh" },
  { title: "Yiddish/ייִדיש", value: "yi" },
  { title: "Yong", value: "yno" },
  { title: "Yoy", value: "yoy" },
  { title: "Yoruba", value: "yo" },
  { title: "Yucatec Maya", value: "yua" },
  { title: "Zhuang", value: "za" },
  { title: "Zangskari", value: "zau" },
  { title: "Zulu", value: "zu" },
];

export const LANGUAGE_MAP = LANGUAGES.reduce(
  (acc, { title, value }) => ((acc[value] = title), acc),
  {},
);

export const languagesWith12HoursSystem = LANGUAGES.filter(({ value: lang }) => {
  const { hourCycle, hour12 } = new Intl.DateTimeFormat(lang, {
    timeStyle: "full",
  }).resolvedOptions();
  return hour12 ?? (hourCycle === "h12" || hourCycle === "h11");
});

// console.log(languagesWith12HoursSystem.length);
// console.log(
//   LANGUAGES.filter(
//     ({ value }) => Intl.DateTimeFormat(value).resolvedOptions().numberingSystem === "mymr",
//   ),
// );

// TODO : put UTC and GMT time zone names of each languages to respective arrays
let UTCTimeZoneLongNames = [];
let GMTTimeZoneLongNames = [];
let UTCTimeZoneFullNames = [];
let GMTTimeZoneFullNames = [];
function assignTimeZoneName(timeStyle) {
  for (const { value } of LANGUAGES) {
    const tzName = timeZone =>
      new Intl.DateTimeFormat(value, { timeStyle, timeZone })
        .formatToParts(Date.now())
        .find(({ type }) => type === "timeZoneName")?.value ?? "GMT";
    const UTCTzName = tzName("UTC");
    const GMTTzName1 = tzName("GMT");
    const GMTTzName2 = tzName("Africa/Abidjan");
    const GMTTzName3 = tzName("Atlantic/Reykjavik");

    switch (timeStyle) {
      case "long":
        if (!UTCTimeZoneLongNames.includes(UTCTzName)) {
          UTCTimeZoneLongNames.push(UTCTzName);
        }

        if (!GMTTimeZoneLongNames.includes(GMTTzName1)) {
          GMTTimeZoneLongNames.push(GMTTzName1);
        } else if (!GMTTimeZoneLongNames.includes(GMTTzName2)) {
          GMTTimeZoneLongNames.push(GMTTzName2);
        } else if (!GMTTimeZoneLongNames.includes(GMTTzName3)) {
          GMTTimeZoneLongNames.push(GMTTzName3);
        }
        break;

      case "full":
        if (!UTCTimeZoneFullNames.includes(UTCTzName)) {
          UTCTimeZoneFullNames.push(UTCTzName);
        }

        if (!GMTTimeZoneFullNames.includes(GMTTzName1)) {
          GMTTimeZoneFullNames.push(GMTTzName1);
        } else if (!GMTTimeZoneFullNames.includes(GMTTzName2)) {
          GMTTimeZoneFullNames.push(GMTTzName2);
        } else if (!GMTTimeZoneFullNames.includes(GMTTzName3)) {
          GMTTimeZoneFullNames.push(GMTTzName3);
        }
        break;

      default:
        break;
    }
  }
}

assignTimeZoneName("long");
assignTimeZoneName("full");

export { UTCTimeZoneLongNames, UTCTimeZoneFullNames, GMTTimeZoneLongNames, GMTTimeZoneFullNames };

export const REGIONS = [
  { title: " Unspecified", value: "" },
  { title: "Afghanistan", value: "AF" },
  { title: "Åland Island", value: "AX" },
  { title: "Albania", value: "AL" },
  { title: "Algeria", value: "DZ" },
  { title: "American Samoa", value: "AS" },
  { title: "Andorra", value: "AD" },
  { title: "Angola", value: "AO" },
  { title: "Anguilla", value: "AI" },
  { title: "Antarctica", value: "AQ" },
  { title: "Antigua and Barbuda", value: "AG" },
  { title: "Aotearoa/New Zealand", value: "NZ" },
  { title: "Argentina", value: "AR" },
  { title: "Armenia", value: "AM" },
  { title: "Aruba", value: "AW" },
  { title: "Ascension Island PD", value: "AC" },
  { title: "Australia", value: "AU" },
  { title: "Austria", value: "AT" },
  { title: "Azerbaijan", value: "AZ" },
  { title: "Bahamas", value: "BS" },
  { title: "Bahrain", value: "BH" },
  { title: "Bangladesh", value: "BD" },
  { title: "Barbados", value: "BB" },
  { title: "Belarus", value: "BY" },
  { title: "Belgium", value: "BE" },
  { title: "Belize", value: "BZ" },
  { title: "Benin", value: "BJ" },
  { title: "Bermuda", value: "BM" },
  { title: "Bhutan", value: "BT" },
  { title: "Bolivia", value: "BO" },
  { title: "Bonaire, Sint Eustatius and Saba (Carribean Netherlands)", value: "BQ" },
  { title: "Bosnia and Herzegovina", value: "BA" },
  { title: "Botswana", value: "BW" },
  { title: "Bouvet Island", value: "BV" },
  { title: "Brazil", value: "BR" },
  { title: "British Indian Ocean Territory", value: "IO" },
  { title: "Brunei Darussalam", value: "BN" },
  { title: "Bulgaria", value: "BG" },
  { title: "Burkina Faso", value: "BF" },
  { title: "Burma/Myanmar", value: "MM" },
  { title: "Burundi", value: "BI" },
  { title: "Cambodia", value: "KH" },
  { title: "Cameroon", value: "CM" },
  { title: "Canada", value: "CA" },
  { title: "Canary Islands", value: "IC" },
  { title: "Cape Verde", value: "CV" },
  { title: "Cayman Islands", value: "KY" },
  { title: "Central African Republic", value: "CF" },
  { title: "Ceuta and Melilla", value: "EA" },
  { title: "Chad", value: "TD" },
  { title: "Chechnya", value: "CE" },
  { title: "Chile", value: "CL" },
  { title: "China (Mainland) (People’s Republic of China)", value: "CN" },
  { title: "Christmas Islands", value: "CX" },
  { title: "Clipperton Island", value: "CP" },
  { title: "Cocos (Keeling) Islands", value: "CC" },
  { title: "Colombia", value: "CO" },
  { title: "Comoros", value: "KM" },
  { title: "Congo (Brazzaville, Republic of)", value: "CG" },
  { title: "Congo (Kinshasa and Lubumbashi, Democratic Republic of)", value: "CD" },
  { title: "Cook Islands", value: "CK" },
  { title: "Costa Rica", value: "CR" },
  { title: "Côte d’Ivoire/Ivory Coast", value: "CI" },
  { title: "Croatia", value: "HR" },
  { title: "Cuba", value: "CU" },
  { title: "Curaçao", value: "CW" },
  { title: "Cyprus", value: "CY" },
  { title: "Czech Republic", value: "CZ" },
  { title: "Denmark", value: "DK" },
  { title: "Diego Garcia", value: "DG" },
  { title: "Djibouti", value: "DJ" },
  { title: "Dominica", value: "DM" },
  { title: "Dominican Republic", value: "DO" },
  { title: "Ecuador", value: "EC" },
  { title: "Egypt", value: "EG" },
  { title: "El Salvador", value: "SV" },
  { title: "Equatorial Guinea", value: "GQ" },
  { title: "Eritrea", value: "ER" },
  { title: "Estonia", value: "EE" },
  { title: "Eswatini/Swaziland", value: "SZ" },
  { title: "Ethiopia", value: "ET" },
  { title: "European Union", value: "EU" },
  { title: "Falkland Islands/Malvinas", value: "FK" },
  { title: "Faroe Islands", value: "FO" },
  { title: "Fiji Islands", value: "FJ" },
  { title: "Finland", value: "FI" },
  { title: "France", value: "FR" },
  { title: "France (Saint Barthélemy)", value: "BL" },
  { title: "French Guiana", value: "GF" },
  { title: "French Polynesia", value: "PF" },
  { title: "French Southern and Antarctic Territories", value: "TF" },
  { title: "Gabon", value: "GA" },
  { title: "Gambia", value: "GM" },
  { title: "Georgia", value: "GE" },
  { title: "Germany", value: "DE" },
  { title: "Ghana", value: "GH" },
  { title: "Gibraltar", value: "GI" },
  { title: "Greece", value: "GR" },
  { title: "Grenada", value: "GD" },
  { title: "Guadeloupe", value: "GP" },
  { title: "Guam", value: "GU" },
  { title: "Guatemala", value: "GT" },
  { title: "Guernsey and Alderney", value: "GG" },
  { title: "Guinea", value: "GN" },
  { title: "Guinea-Bissau", value: "GW" },
  { title: "Guyana", value: "GY" },
  { title: "Haiti", value: "HT" },
  { title: "Heard Island and McDonald Islands", value: "HM" },
  { title: "Holy See (Vatican)", value: "VA" },
  { title: "Honduras", value: "HN" },
  { title: "Hong Kong Special Administrative Region", value: "HK" },
  { title: "Hungary", value: "HU" },
  { title: "Iceland", value: "IS" },
  { title: "India", value: "IN" },
  { title: "Indonesia", value: "ID" },
  { title: "Iran", value: "IR" },
  { title: "Iraq", value: "IQ" },
  { title: "Ireland", value: "IE" },
  { title: "Isle of Man", value: "IM" },
  { title: "Israel", value: "IL" },
  { title: "Italy", value: "IT" },
  { title: "Jamaica", value: "JM" },
  { title: "Japan", value: "JP" },
  { title: "Jersey", value: "JE" },
  { title: "Jordan", value: "JO" },
  { title: "Kalaallit Nunaat/Greenland", value: "GL" },
  { title: "Kazakhstan", value: "KZ" },
  { title: "Kenya", value: "KE" },
  { title: "Kiribati", value: "KI" },
  { title: "Korea (North, Democratic People’s Republic of)", value: "KP" },
  { title: "Korea (South, Republic of)", value: "KR" },
  { title: "Kosovo", value: "XK" },
  { title: "Kuwait", value: "KW" },
  { title: "Kyrgyzstan", value: "KG" },
  { title: "Laos", value: "LA" },
  { title: "Latin America", value: 419 },
  { title: "Latvia", value: "LV" },
  { title: "Lebanon", value: "LB" },
  { title: "Lesotho", value: "LS" },
  { title: "Liberia", value: "LR" },
  { title: "Libya", value: "LY" },
  { title: "Liechtenstein", value: "LI" },
  { title: "Lithuania", value: "LT" },
  { title: "Luxembourg", value: "LU" },
  { title: "Macau Special Administrative Region", value: "MO" },
  { title: "Madagascar", value: "MG" },
  { title: "Malawi", value: "MW" },
  { title: "Malaysia", value: "MY" },
  { title: "Maldives", value: "MV" },
  { title: "Mali", value: "ML" },
  { title: "Malta", value: "MT" },
  { title: "Marshall Islands", value: "MH" },
  { title: "Martinique", value: "MQ" },
  { title: "Mauritania", value: "MR" },
  { title: "Mauritius", value: "MU" },
  { title: "Mayotte", value: "YT" },
  { title: "Mexico", value: "MX" },
  { title: "Micronesia", value: "FM" },
  { title: "Moldova", value: "MD" },
  { title: "Monaco", value: "MC" },
  { title: "Mongolia", value: "MN" },
  { title: "Montenegro", value: "ME" },
  { title: "Montserrat", value: "MS" },
  { title: "Morocco", value: "MA" },
  { title: "Mozambique", value: "MZ" },
  { title: "Namibia", value: "NA" },
  { title: "Nauru", value: "NR" },
  { title: "Nepal", value: "NP" },
  { title: "Netherland", value: "NL" },
  { title: "Netherland Antilles", value: "AN" },
  { title: "New Caledonia", value: "NC" },
  { title: "Nicaragua", value: "NI" },
  { title: "Niger", value: "NE" },
  { title: "Nigeria", value: "NG" },
  { title: "Niue", value: "NU" },
  { title: "Norfolk Island", value: "NF" },
  { title: "North Macedonia", value: "MK" },
  { title: "Northern Mariana Islands", value: "MP" },
  { title: "Norway", value: "NO" },
  { title: "Oman", value: "OM" },
  { title: "Pakistan", value: "PK" },
  { title: "Palau", value: "PW" },
  { title: "Palestine", value: "PS" },
  { title: "Panama", value: "PA" },
  { title: "Papua New Guinea", value: "PG" },
  { title: "Paraguay", value: "PY" },
  { title: "Peru", value: "PE" },
  { title: "Philippines", value: "PH" },
  { title: "Pitcairn Islands", value: "PN" },
  { title: "Poland", value: "PL" },
  { title: "Portugal", value: "PT" },
  { title: "Puerto Rico", value: "PR" },
  { title: "Qatar", value: "QA" },
  { title: "Réunion", value: "RE" },
  { title: "Romania", value: "RO" },
  { title: "Russia", value: "RU" },
  { title: "Rwanda", value: "RW" },
  { title: "Saint Helena, Ascension and Tristan da Cunha", value: "SH" },
  { title: "Saint Kitts and Nevis", value: "KN" },
  { title: "Saint Lucia", value: "LC" },
  { title: "Saint Martin (Dutch)", value: "SX" },
  { title: "Saint Martin (French)", value: "MF" },
  { title: "Saint Pierre and Miquelon", value: "PM" },
  { title: "Saint Vincent and the Grenadines", value: "VC" },
  { title: "Samoa", value: "WS" },
  { title: "San Marino", value: "SM" },
  { title: "São Tomé and Príncipe", value: "ST" },
  { title: "Sark", value: "CQ" },
  { title: "Saudi Arabia", value: "SA" },
  { title: "Senegal", value: "SN" },
  { title: "Serbia", value: "RS" },
  { title: "Seychelles", value: "SC" },
  { title: "Sierra Leone", value: "SL" },
  { title: "Singapore", value: "SG" },
  { title: "Slovakia", value: "SK" },
  { title: "Slovenia", value: "SI" },
  { title: "Solomon Islands", value: "SB" },
  { title: "Somalia", value: "SO" },
  { title: "South Africa", value: "ZA" },
  { title: "South Georgia and the South Sandwich Islands", value: "GS" },
  { title: "South Sudan", value: "SS" },
  { title: "Spain", value: "ES" },
  { title: "Sri Lanka", value: "LK" },
  { title: "Sudan", value: "SD" },
  { title: "Suriname", value: "SR" },
  { title: "Svalbard and Jan Mayen Islands", value: "SJ" },
  { title: "Sweden", value: "SE" },
  { title: "Switzerland", value: "CH" },
  { title: "Syria", value: "SY" },
  { title: "Taiwan (Republic of China)", value: "TW" },
  { title: "Tajikistan", value: "TJ" },
  { title: "Tanzania", value: "TZ" },
  { title: "Thailand", value: "TH" },
  { title: "Timor Leste", value: "TL" },
  { title: "Togo", value: "TG" },
  { title: "Tokelau", value: "TK" },
  { title: "Tonga", value: "TO" },
  { title: "Trinidad and Tobago", value: "TT" },
  { title: "Tristan da Cunha", value: "TA" },
  { title: "Tunisia", value: "TN" },
  { title: "Türkiye", value: "TR" },
  { title: "Turkmenistan", value: "TM" },
  { title: "Turks and Caicos Islands", value: "TC" },
  { title: "Tuvalu", value: "TV" },
  { title: "Uganda", value: "UG" },
  { title: "Ukraine", value: "UA" },
  { title: "United Arab Emirates", value: "AE" },
  { title: "United Kingdom", value: "GB" },
  { title: "United Nations Organization", value: "UN" },
  { title: "United States of America", value: "US" },
  { title: "United States Minor Outlying Islands", value: "UM" },
  { title: "Uruguay", value: "UY" },
  { title: "Uzbekistan", value: "UZ" },
  { title: "Vanuatu", value: "VU" },
  { title: "Venezuela", value: "VE" },
  { title: "Việt Nam", value: "VN" },
  { title: "Virgin Islands (British)", value: "VG" },
  { title: "Virgin Islands (U.S.)", value: "VI" },
  { title: "Wallis and Futuna", value: "WF" },
  { title: "Western Sahara", value: "EH" },
  { title: "Yemen", value: "YE" },
  { title: "Zambia", value: "ZM" },
  { title: "Zimbabwe", value: "ZW" },
];

export const REGION_MAP = REGIONS.reduce(
  (acc, { title, value }) => ((acc[value] = title), acc),
  {},
);

export const regionsAdoptingAR = [
  "AE",
  "BH",
  "DJ",
  "DZ",
  "EG",
  "EH",
  "ER",
  "IL",
  "IQ",
  "JO",
  "KM",
  "KW",
  "LB",
  "LY",
  "MA",
  "MR",
  "OM",
  "PS",
  "QA",
  "SA",
  "SD",
  "SO",
  "SS",
  "SY",
  "TD",
  "TN",
  "UN",
  "YE",
]; // 28
export const arabRegionsUsingWesternArabicNumbers = ["AE", "DZ", "EH", "LY", "MA", "TN"];
export const regionsAdoptingFA = ["AF", "IR"];
export const regionsAdoptingUR = ["IN", "PK"];
export const regionsAdoptingHE = ["IL"];

export const regionsAdoptingZH = ["CN", "HK", "MO", "MY", "SG", "TW", "UN"];
export const regionsAdoptingKO = ["KR", "KP"];
export const regionsAdoptingJA = ["JP"];
export const regionsAdoptingMN = ["MN"];

export const regionsAdoptingTA = ["IN", "LK", "MY", "SG"];
export const regionsAdoptingBN = ["BD", "IN"];
export const regionsAdoptingHI = ["IN"];

export const regionsAdoptingMS = ["BN", "ID", "MY", "SG"];
export const regionsAdoptingID = ["ID"];
export const regionsAdoptingJV = ["ID", "NC", "SR"];
export const regionsAdoptingSU = ["ID"];
export const regionsAdoptingTL = ["PH"];
export const regionsAdoptingTH = ["TH"];
export const regionsAdoptingLO = ["LA"];
export const regionsAdoptingKM = ["KH"];
export const regionsAdoptingMY = ["MM"];
export const regionsAdoptingVI = ["VN"];

export const regionsAdoptingAM = ["ER", "ET"];
export const regionsAdoptingTI = ["ER", "ET"];
export const regionsAdoptingSW = ["KE", "TZ", "UG"];

export const regionsAdoptingKA = ["GE"];
export const regionsAdoptingHY = ["AM"];

export const regionsAdoptingRU = ["BY", "KZ", "KG", "RU", "UA", "UN", "MD"]; // 7
export const regionsAdoptingEL = ["GR", "CY"]; // 2

export const regionsAdoptingEN = [
  "AE",
  "AG",
  "AI",
  "AS",
  "AT",
  "AU",
  "BB",
  "BE",
  "BI",
  "BM",
  "BN",
  "BS",
  "BW",
  "BZ",
  "CA",
  "CC",
  "CH",
  "CK",
  "CM",
  "CQ",
  "CX",
  "CY",
  "CZ",
  "DE",
  "DK",
  "DM",
  "ER",
  "ES",
  "EU",
  "FI",
  "FJ",
  "FK",
  "FM",
  "FR",
  "GB",
  "GD",
  "GG",
  "GH",
  "GI",
  "GM",
  "GS",
  "GU",
  "GY",
  "HK",
  "HU",
  "ID",
  "IE",
  "IL",
  "IM",
  "IN",
  "IO",
  "IT",
  "JE",
  "JM",
  "KE",
  "KI",
  "KN",
  "KY",
  "LC",
  "LR",
  "LS",
  "MF",
  "MH",
  "MO",
  "MP",
  "MS",
  "MT",
  "MU",
  "MV",
  "MW",
  "MY",
  "NA",
  "NF",
  "NG",
  "NL",
  "NO",
  "NR",
  "NU",
  "NZ",
  "PG",
  "PH",
  "PK",
  "PL",
  "PN",
  "PR",
  "PT",
  "PW",
  "RO",
  "RW",
  "SB",
  "SC",
  "SD",
  "SE",
  "SG",
  "SH",
  "SI",
  "SK",
  "SL",
  "SS",
  "SX",
  "SZ",
  "TC",
  "TK",
  "TO",
  "TT",
  "TV",
  "TZ",
  "UG",
  "UM",
  "UN",
  "US",
  "VC",
  "VG",
  "VI",
  "VU",
  "WS",
  "ZA",
  "ZM",
  "ZW",
]; // 119
export const regionsAdoptingFR = [
  "BE",
  "BF",
  "BJ",
  "BL",
  "CA",
  "CG",
  "CD",
  "CF",
  "CH",
  "CI",
  "CM",
  "DJ",
  "DZ",
  "EU",
  "FR",
  "GA",
  "GF",
  "GN",
  "GP",
  "HT",
  "KM",
  "LU",
  "MA",
  "MC",
  "MF",
  "MG",
  "ML",
  "MQ",
  "MR",
  "MU",
  "NC",
  "NE",
  "PF",
  "RE",
  "SC",
  "SN",
  "TD",
  "TN",
  "UN",
  "WF",
  "YT",
]; // 41
export const regionsAdoptingDE = ["AT", "BE", "CH", "DE", "EU", "LI", "LU"]; // 7
export const regionsAdoptingIT = ["IT", "CH", "EU", "SM", "VA"]; // 5
export const regionsAdoptingES = [
  419,
  "AR",
  "BO",
  "CL",
  "CO",
  "CR",
  "CU",
  "DO",
  "EC",
  "ES",
  "EU",
  "GQ",
  "GT",
  "HN",
  "MX",
  "NI",
  "PA",
  "PE",
  "PH",
  "PR",
  "PY",
  "SV",
  "UN",
  "US",
  "UY",
  "VE",
]; // 26
export const regionsAdoptingPT = ["AO", "BR", "CV", "EU", "GW", "MO", "MZ", "PT", "ST", "TL"]; // 10
export const regionsAdoptingNL = ["AW", "BE", "BQ", "CW", "EU", "NL", "SR", "SX"]; // 8

// console.log(REGIONS.filter(({ value }) => regionsAdoptingES.some(region => region === value)));
// console.log(Intl.Collator("ja-JP", { collation: "gb2312" }).resolvedOptions());

export const CALENDAR_OPTIONS = {
  CALENDARS: [
    { title: " None", value: "" },
    { title: "Balinese Hindu/Indian Calendar", value: "indian" },
    { title: "Buddhist Calendar", value: "buddhist" },
    { title: "Civil (Algorithmic) Arabic Calendar", value: "islamicc" },
    { title: "Coptic Calendar", value: "coptic" },
    { title: "Ethiopic Amete Alem Calendar (Epoch Approx. 5493 B.C.E)", value: "ethioaa" },
    { title: "Ethiopic Amete Mihret Calendar (Epoch Approx, 8 C.E.)", value: "ethiopic" },
    { title: "Gregorian Calendar", value: "gregory" },
    { title: "Hijri Calendar", value: "islamic" },
    { title: "Hijri Calendar, Umm al-Qura", value: "islamic-umalqura" },
    { title: "Hijri Calendar, Astronomical Epoch", value: "islamic-tbla" },
    { title: "Hijri Calendar, Civil Epoch", value: "islamic-civil" },
    { title: "Hijri Calendar, Saudi Sighting", value: "islamic-rgsa" },
    { title: "ISO 8601 Calendar", value: "iso8601" },
    { title: "Japanese Imperial Calendar", value: "japanese" },
    { title: "Persian Calendar", value: "persian" },
    { title: "Taiwanese R.O.C. Calendar", value: "roc" },
    { title: "Traditional Chinese Calendar", value: "chinese" },
    { title: "Traditional Hebrew Calendar", value: "hebrew" },
    { title: "Traditional Korean Calendar", value: "dangi" },
    { title: "Tibetan Calendar", value: "tibetan" },
    { title: "Ugaritic Calendar", value: "ugaritic" },
  ].sort((a, b) => a.title.localeCompare(b.title, "en", { collation: "ducet" })),
  NUMBERS: [
    { title: " None", value: "" },
    { title: "ASCII/Western Arabic Numbers", value: "latn" },
    { title: "Adlam Numbers", value: "adlm" },
    { title: "Ahom Numbers", value: "ahom" },
    { title: "Armenian Upper Case Numbers", value: "armn" },
    { title: "Armenian Lower Case Numbers", value: "armnlow" },
    { title: "Balinese Numbers", value: "bali" },
    { title: "Bengali Numbers", value: "beng" },
    { title: "Bhaiksuki Numbers", value: "bhks" },
    { title: "Brahmi Numbers", value: "brah" },
    { title: "Chakma Numbers", value: "cakm" },
    { title: "Cham Numbers", value: "cham" },
    { title: "Chisoi Numbers", value: "chis" },
    { title: "Cyrillic Algorithmic Numbers", value: "cyrl" },
    { title: "Dari/Farsi/Kashmir/Mazanderani/Pashto/Shahmukhi/Urdu Numbers", value: "arabext" },
    { title: "Devanagari Numbers", value: "deva" },
    { title: "Dives Akuru Numbers", value: "diak" },
    { title: "Eastern Arabic Numbers", value: "arab" },
    { title: "Ethiopian Algorithmic Numbers", value: "ethi" },
    { title: "Financial Numeral", value: "finance" },
    { title: "Full-Width Numbers (CJK)", value: "fullwide" },
    { title: "Garay Numbers", value: "gara" },
    { title: "Georgian Algorithmic Numbers", value: "geor" },
    { title: "Greek Upper Case Numbers", value: "grek" },
    { title: "Greek Lower Case Numbers", value: "greklow" },
    { title: "Gujarati Numbers", value: "gujr" },
    { title: "Gunjala Gondi Numbers", value: "gong" },
    { title: "Gurung Khema Numbers", value: "gukh" },
    { title: "Gurmukhi Numbers", value: "guru" },
    { title: "Han Decimal Ideographical Numbers", value: "hanidec" },
    { title: "Han Numbers (Lunar Calendar)", value: "hanidays" },
    { title: "Hanifi Rohingya Numbers", value: "rohg" },
    { title: "Hebrew Upper Case Numbers", value: "hebr" },
    { title: "Javanese Numbers", value: "java" },
    { title: "Japanese Numbers", value: "jpan" },
    { title: "Japanese Financial Numbers", value: "jpanfin" },
    { title: "Japanese First-Year Gannen Numbering for Japanese Calendar", value: "jpanyear" },
    { title: "Kannada Numbers", value: "knda" },
    { title: "Kayah Li Numbers", value: "kali" },
    { title: "Kayah Li Numbers (Latin)", value: "kalil" },
    { title: "Kawi Numbers", value: "kawi" },
    { title: "Khmer Numbers", value: "khmr" },
    { title: "Khmer Symbols", value: "khmrsym" },
    { title: "Khmer Symbols (Latin)", value: "khmrlatn" },
    { title: "Khudawadi Numbers", value: "sind" },
    { title: "Kirat Rai Numbers", value: "krai" },
    { title: "Korean Hangul Numbers", value: "hang" },
    { title: "Lao Numbers", value: "laoo" },
    { title: "Legacy Computing Outlined Numbers", value: "outlined" },
    { title: "Legacy Computing Segmented Numbers", value: "segment" },
    { title: "Lepcha Numbers", value: "lepc" },
    { title: "Limbu Numbers", value: "limb" },
    { title: "Lisu Numbers", value: "lisudec" },
    { title: "Lisu Traditional Numbers", value: "lisutr" },
    { title: "Lycian Upper Case Numbers", value: "lyci" },
    { title: "Lycian Lower Case Numbers", value: "lycilow" },
    { title: "Lydian Upper Case Numbers", value: "lydi" },
    { title: "Lydian Lower Case Numbers", value: "lydilow" },
    { title: "Malayalam Numbers", value: "mlym" },
    { title: "Mandaic Upper Case Numbers", value: "mand" },
    { title: "Mandaic Lower Case Numbers", value: "mandlow" },
    { title: "Masaram Gondi Numbers", value: "gonm" },
    { title: "Mathematical Bold Numbers", value: "mathbold" },
    { title: "Mathematical Double-Struck Numbers", value: "mathdbl" },
    { title: "Mathematical Monospace Numbers", value: "mathmono" },
    { title: "Mathematical Sans-Serif Bold Numbers", value: "mathsanb" },
    { title: "Mathematical Sans-Serif Numbers", value: "mathsans" },
    { title: "Modi Numbers", value: "modi" },
    { title: "Mongolian Numbers", value: "mong" },
    { title: "Mro Numbers", value: "mroo" },
    { title: "Meitei Mayek Numbers", value: "mtei" },
    { title: "Myanmar Numbers", value: "mymr" },
    { title: "Myanmar Eastern Pwo Karen Numbers", value: "mymrepka" },
    { title: "Myanmar Pao Numbers", value: "mymrpao" },
    { title: "Myanmar Shan Numbers", value: "mymrshan" },
    { title: "Myanmar Tai Laing Numbers", value: "mymrtlng" },
    { title: "Nag Mundari Numbers", value: "nagm" },
    { title: "Native Numbers", value: "native" },
    { title: "New Tai Lüe Numbers", value: "talu" },
    { title: "Newa Numbers", value: "newa" },
    { title: "Nyiakeng Puachue Hmong Numbers", value: "hmnp" },
    { title: "N’Ko Numbers", value: "nkoo" },
    { title: "Ol Chiki Numbers", value: "olck" },
    { title: "Ol Onal Numbers", value: "onao" },
    { title: "Oriya Numbers", value: "orya" },
    { title: "Osmanya Numbers", value: "osma" },
    { title: "Pahawh Hmong Numbers", value: "hmng" },
    { title: "Roman Upper Case Numbers", value: "roman" },
    { title: "Roman Lower Case Numbers", value: "romanlow" },
    { title: "Saurashtra Numbers", value: "saur" },
    { title: "Sharada Numbers", value: "shrd" },
    { title: "Simplified Chinese Numbers", value: "hans" },
    { title: "Simplified Chinese Financial Numbers", value: "hansfin" },
    { title: "Sinhala Numbers", value: "sinh" },
    { title: "Sora Sompeng Numbers", value: "sora" },
    { title: "Sundanese Numbers", value: "sund" },
    { title: "Sunuwar Numbers", value: "sunu" },
    { title: "Tai Tham Hora (Secular) Numbers", value: "lana" },
    { title: "Tai Tham Tham (Ecclesiastical) Numbers", value: "lanatham" },
    { title: "Takri Numbers", value: "takr" },
    { title: "Tamil Decimal Numbers", value: "tamldec" },
    { title: "Tamil Traditional Numbers", value: "taml" },
    { title: "Tangsa Numbers", value: "tnsa" },
    { title: "Telugu Numbers", value: "telu" },
    { title: "Thai Numbers", value: "thai" },
    { title: "Tibetan Numbers", value: "tibt" },
    { title: "Tirhuta Numbers", value: "tirh" },
    { title: "Tolong Siki Numbers", value: "tols" },
    { title: "Traditional Numbers", value: "traditio" },
    { title: "Traditional Chinese Numbers", value: "hant" },
    { title: "Traditional Chinese Financial Numbers", value: "hantfin" },
    { title: "Vai Numbers", value: "vaii" },
    { title: "Warang Citi Numbers", value: "wara" },
    { title: "Wancho Numbers", value: "wcho" },
  ].sort((a, b) => a.title.localeCompare(b.title, "en", { collation: "ducet" })),
  COLLATIONS: [
    { title: " None", value: "" },
    { title: "Binary Code-Point Collation (Hindi)", value: "direct" },
    { title: "Compatibility Collation", value: "compat" },
    { title: "Default Collation", value: "standard" },
    { title: "Default Unicode Collation Element Table Order", value: "ducet" },
    { title: "Dictionary-style Collation (Sinhala)", value: "dict" },
    { title: "Emoji Collation", value: "emoji" },
    { title: "European Collation", value: "eor" },
    { title: "Korean Initial Consonant Collation", value: "searchjl" },
    {
      title:
        "Pinyin Collation for Latin, Big5 Character Set Collation for CJK characters (Traditional Chinese)",
      value: "big5han",
    },
    {
      title:
        "Pinyin Collation for Latin, GB2312 Character Set Collation for CJK characters (Simplified Chinese)",
      value: "gb2312",
    },
    {
      title: "Pinyin Collation for Latin, Stroke Order Collation for CJK characters (Chinese)",
      value: "stroke",
    },
    {
      title:
        "Pinyin Collation for Latin, Unihan Radical Stroke Order Collation for CJK characters (Chinese)",
      value: "unihan",
    },
    {
      title:
        "Pinyin Collation for Latin, Zhuyin Order for Bopomofo and CJK characters (Primarily Traditional Chinese)",
      value: "zhuyin",
    },
    {
      title: "Pinyin Collation for Latin and CJK characters (Primarily Simplified Chinese)",
      value: "pinyin",
    },
    { title: "Phonebook-style Collation (German)", value: "phonebk" },
    { title: "Phonetic Collation", value: "phonetic" },
    { title: "Reformed Collation (Swedish)", value: "reformed" },
    { title: "String-Search Collation", value: "search" },
    { title: "Traditional Collation (Spanish)", value: "trad" },
  ].sort((a, b) => a.title.localeCompare(b.title, "en", { collation: "ducet" })),
};

export const CALENDAR_MAP = CALENDAR_OPTIONS.CALENDARS.reduce(
  (acc, { title, value }) => ((acc[value] = title), acc),
  {},
);

export const NUMBER_MAP = CALENDAR_OPTIONS.NUMBERS.reduce(
  (acc, { title, value }) => ((acc[value] = title), acc),
  {},
);

export const COLLATION_MAP = CALENDAR_OPTIONS.COLLATIONS.reduce(
  (acc, { title, value }) => ((acc[value] = title), acc),
  {},
);

// console.log(LANGUAGE_MAP);
// for (const key in LANGUAGE_MAP) {
//   if (!Object.hasOwn(LANGUAGE_MAP, key)) continue;

//   const element = LANGUAGE_MAP[key];

//   console.log(element);
// }

// console.log(REGION_MAP);
// for (const key in REGION_MAP) {
//   if (!Object.hasOwn(REGION_MAP, key)) continue;

//   const element = REGION_MAP[key];

//   console.log(element);
// }

// console.log(CALENDAR_MAP);
// for (const key in CALENDAR_MAP) {
//   if (!Object.hasOwn(CALENDAR_MAP, key)) continue;

//   const element = CALENDAR_MAP[key];

//   console.log(element);
// }

// console.log(NUMBER_MAP);
// for (const key in NUMBER_MAP) {
//   if (!Object.hasOwn(NUMBER_MAP, key)) continue;

//   const element = NUMBER_MAP[key];

//   console.log(element);
// }

// console.log(COLLATION_MAP);
// for (const key in COLLATION_MAP) {
//   if (!Object.hasOwn(COLLATION_MAP, key)) continue;

//   const element = COLLATION_MAP[key];

//   console.log(element);
// }
