export const LANGUAGES = [
  { title: "Abkhaizan", value: "ab" },
  { title: "Afar", value: "aa" },
  { title: "Afrikaans", value: "af" },
  { title: "Akan", value: "ak" },
  { title: "Albanian", value: "sq" },
  { title: "Albanian (Arvanitika)", value: "aat" },
  { title: "Albanian (Arvanitika, Greek)", value: "aat-grek" },
  { title: "Albanian (Arvanitika, Greek) (BCP 47)", value: "aat-Grek" },
  { title: "Albanian (Gheg)", value: "aln" },
  { title: "Albanian (Tosk)", value: "als" },
  { title: "Amharic", value: "am" },
  { title: "Anishinaabe/Ojibwe", value: "oj" },
  { title: "Arabic", value: "ar" },
  { title: "Arabic (Modern Standard)", value: "arb" },
  { title: "Arabic (Algerian)", value: "arq" },
  { title: "Arabic (Andalusian)", value: "xaa" },
  { title: "Arabic (Bahrani)", value: "abv" },
  { title: "Arabic (Chadian)", value: "shu" },
  { title: "Arabic (Dhofari)", value: "adf" },
  { title: "Arabic (Egyptian)", value: "arz" },
  { title: "Arabic (Gulf)", value: "afb" },
  { title: "Arabic (Hadhrami)", value: "ayh" },
  { title: "Arabic (Hassaniya)", value: "mey" },
  { title: "Arabic (Hejazi)", value: "acw" },
  { title: "Arabic (Moroccan)", value: "ary" },
  { title: "Arabic (Judeo-Iraqi)", value: "yhd" },
  { title: "Arabic (Judeo-Moroccan)", value: "aju" },
  { title: "Arabic (Judeo-Yemeni)", value: "jye" },
  { title: "Arabic (Levantine)", value: "apc" },
  { title: "Arabic (Levantine Bedawi)", value: "avl" },
  { title: "Arabic (Libyan)", value: "ayl" },
  { title: "Arabic (Najdi)", value: "ars" },
  { title: "Arabic (North Mesopotamian (Qeltu))", value: "ayp" },
  { title: "Arabic (Omani)", value: "acx" },
  { title: "Arabic (Saʽīdi (Upper Egyptian))", value: "aec" },
  { title: "Arabic (Sanʽani)", value: "ayn" },
  { title: "Arabic (Shihhi)", value: "ssh" },
  { title: "Arabic (Sicilian)", value: "sqr" },
  { title: "Arabic (South Mesopotamian (Gelet))", value: "acm" },
  { title: "Arabic (Southern Yemeni)", value: "acq" },
  { title: "Arabic (Sudanese)", value: "apd" },
  { title: "Arabic (Tunisian)", value: "aeb" },
  { title: "Aramaic", value: "arc" },
  { title: "Aragonese", value: "an" },
  { title: "Arbëreshe", value: "aae" },
  { title: "Armenian", value: "hy" },
  { title: "Assamese", value: "as" },
  { title: "Asturian", value: "ast" },
  { title: "Asu", value: "asa" },
  { title: "Avaric", value: "av" },
  { title: "Avestan", value: "ae" },
  { title: "Aymara", value: "ay" },
  { title: "Azerbaijani", value: "az" },
  { title: "Azerbaijani (Cyrillic)", value: "az-cyrl" },
  { title: "Azerbaijani (Cyrillic) (BCP 47)", value: "az-Cyrl" },
  { title: "Azerbaijani (Latin)", value: "az-latn" },
  { title: "Azerbaijani (Latin) (BCP 47)", value: "az-Latn" },
  { title: "Bakhtiari", value: "bqi" },
  { title: "Balinese", value: "ban" },
  { title: "Balinese (Aksara Bali)", value: "ban-bali" },
  { title: "Balinese (Aksara Bali) (BCP 47)", value: "ban-Bali" },
  { title: "Balinese (Latin)", value: "ban-latn" },
  { title: "Balinese (Latin) (BCP 47)", value: "ban-Latn" },
  { title: "Balti", value: "bft" },
  { title: "Balti (Arabic)", value: "bft-arab" },
  { title: "Balti (Arabic) (BCP 47)", value: "bft-Arab" },
  { title: "Balti (Tibetan)", value: "bft-tibt" },
  { title: "Balti (Tibetan) (BCP 47)", value: "bft-Tibt" },
  { title: "Bambara", value: "bm" },
  { title: "Bashkir", value: "ba" },
  { title: "Basque", value: "eu" },
  { title: "Batak", value: "btk" },
  { title: "Batak (Latin)", value: "btk-latn" },
  { title: "Batak (Latin) (BCP 47)", value: "btk-Latn" },
  { title: "Batak (Surat Batak)", value: "btk-batk" },
  { title: "Batak (Surat Batak) (BCP 47)", value: "btk-Batk" },
  { title: "Belarusian", value: "be" },
  { title: "Bemba", value: "bem" },
  { title: "Bena", value: "bez" },
  { title: "Bengali", value: "bn" },
  { title: "Berber", value: "ber" },
  { title: "Berber (Latin)", value: "ber-latn" },
  { title: "Berber (Latin) (BCP 47)", value: "ber-Latn" },
  { title: "Berber (Tifinagh)", value: "ber-tfng" },
  { title: "Berber (Tifinagh) (BCP 47)", value: "ber-Tfng" },
  { title: "Bihari", value: "bh" },
  { title: "Bislama", value: "bi" },
  { title: "Bosnian", value: "bs" },
  { title: "Bosnian (Cyrillic)", value: "bs-cyrl" },
  { title: "Bosnian (Cyrillic) (BCP 47)", value: "bs-Cyrl" },
  { title: "Bosnian (Latin)", value: "bs-latn" },
  { title: "Bosnian (Latin) (BCP 47)", value: "bs-Latn" },
  { title: "Breton", value: "br" },
  { title: "Buginese", value: "bug" },
  { title: "Buginese (Latin)", value: "bug-latn" },
  { title: "Buginese (Latin) (BCP 47)", value: "bug-Latn" },
  { title: "Buginese (Lontara)", value: "bug-bugi" },
  { title: "Buginese (Lontara) (BCP 47)", value: "bug-Bugi" },
  { title: "Buginese (Aksara Makassar Kuno)", value: "bug-maka" },
  { title: "Buginese (Aksara Makassar Kuno) (BCP 47)", value: "bug-Maka" },
  { title: "Bulgarian", value: "bg" },
  { title: "Burmese (Unicode)", value: "my" },
  { title: "Burmese (Zawgyi)", value: "my-qaag" },
  { title: "Burmese (Zawgyi) (BCP 47)", value: "my-Qaag" },
  { title: "Cantonese", value: "yue" },
  { title: "Cantonese (Simplified Han)", value: "yue-hans" },
  { title: "Cantonese (Simplified Han) (BCP 47)", value: "yue-Hans" },
  { title: "Cantonese (Traditional Han)", value: "yue-hant" },
  { title: "Cantonese (Traditional Han) (BCP 47)", value: "yue-Hant" },
  { title: "Catalan/Valencian", value: "ca" },
  { title: "Chamorro", value: "ch" },
  { title: "Chechen", value: "ce" },
  { title: "Cherokee", value: "chr" },
  { title: "Chicewa/Chewa/Nyanja", value: "ny" },
  { title: "Chigga", value: "cgg" },
  { title: "Chinese", value: "zh" },
  { title: "Chinese (Simplified Han)", value: "zh-hans" },
  { title: "Chinese (Simplified Han) (BCP 47)", value: "zh-Hans" },
  { title: "Chinese (Traditional Han)", value: "zh-hant" },
  { title: "Chinese (Traditional Han) (BCP 47)", value: "zh-Hant" },
  { title: "Church Slavonic", value: "cu" },
  { title: "Chuvash", value: "cv" },
  { title: "Cornish", value: "kw" },
  { title: "Corsican", value: "co" },
  { title: "Cree", value: "cr" },
  { title: "Croatian", value: "hr" },
  { title: "Czech", value: "cs" },
  { title: "Danish", value: "da" },
  { title: "Dari (Afghan Farsi/Afghan Persian)", value: "prs" },
  { title: "Divehi/Dhivehi/Maldivian", value: "dv" },
  { title: "Dutch", value: "nl" },
  { title: "Dzongkha", value: "dz" },
  { title: "Embu", value: "ebu" },
  { title: "English", value: "en" },
  { title: "Esperanto", value: "eo" },
  { title: "Estonian", value: "et" },
  { title: "Ewe", value: "ee" },
  { title: "Faroese", value: "fo" },
  { title: "Farsi/Persian", value: "fa" },
  { title: "Fijian", value: "fj" },
  { title: "Filipino", value: "fil" },
  { title: "Finnish", value: "fi" },
  { title: "French", value: "fr" },
  { title: "Fula/Fulah/Pulaar/Pular", value: "ff" },
  { title: "Galician", value: "gl" },
  { title: "Ganda/Luganda", value: "lg" },
  { title: "Georgian", value: "ka" },
  { title: "German", value: "de" },
  { title: "Gikuyu/Kikuyu", value: "ki" },
  { title: "Gilaki", value: "glk" },
  { title: "Greek (Ancient)", value: "grc" },
  { title: "Greek (Modern)", value: "el" },
  { title: "Greenlandic/Kalaallisut", value: "kl" },
  { title: "Guarani", value: "gn" },
  { title: "Gujarati", value: "gu" },
  { title: "Gusii", value: "guz" },
  { title: "Haitian Creole", value: "ht" },
  { title: "Hausa", value: "ha" },
  { title: "Hausa (Arabic)", value: "ha-arab" },
  { title: "Hausa (Arabic) (BCP 47)", value: "ha-Arab" },
  { title: "Hausa (Latin)", value: "ha-latn" },
  { title: "Hausa (Latin) (BCP 47)", value: "ha-Latn" },
  { title: "Hawaiian", value: "haw" },
  { title: "Hebrew", value: "he" },
  { title: "Herero", value: "hz" },
  { title: "Hindi", value: "hi" },
  { title: "Hiri Motu/Police Motu", value: "ho" },
  { title: "Hokkien/Min Nan", value: "nan" },
  { title: "Hokkien/Min Nan (Simplified Han)", value: "nan-hans" },
  { title: "Hokkien/Min Nan (Simplified Han) (BCP 47)", value: "nan-Hans" },
  { title: "Hokkien/Min Nan (Traditional Han)", value: "nan-hant" },
  { title: "Hokkien/Min Nan (Traditional Han) (BCP 47)", value: "nan-Hant" },
  { title: "Hungarian", value: "hu" },
  { title: "Hyolmo/Yolmo", value: "scp" },
  { title: "Icelandic", value: "is" },
  { title: "Ido", value: "io" },
  { title: "Igbo", value: "ig" },
  { title: "Indonesian", value: "id" },
  { title: "Interlingua (International Auxiliary Language Association)", value: "ia" },
  { title: "Interlingue/Occidental", value: "ie" },
  { title: "Inuktitut", value: "iu" },
  { title: "Inupiaq", value: "ik" },
  { title: "Irish", value: "ga" },
  { title: "Italian", value: "it" },
  { title: "Japanese", value: "ja" },
  { title: "Javanese", value: "jv" },
  { title: "Javanese (Aksara Jawa)", value: "jv-java" },
  { title: "Javanese (Aksara Jawa) (BCP 47)", value: "jv-Java" },
  { title: "Javanese (Latin)", value: "jv-latn" },
  { title: "Javanese (Latin) (BCP 47)", value: "jv-Latn" },
  { title: "Javanese (Pégon)", value: "jv-arab" },
  { title: "Javanese (Pégon) (BCP 47)", value: "jv-Arab" },
  { title: "Jirel", value: "jul" },
  { title: "Jirel (Devanagari)", value: "jul-deva" },
  { title: "Jirel (Devanagari) (BCP 47)", value: "jul-Deva" },
  { title: "Jirel (Tibetan)", value: "jul-tibt" },
  { title: "Jirel (Tibetan) (BCP 47)", value: "jul-Tibt" },
  { title: "Kabuverdianu", value: "kea" },
  { title: "Kabyle", value: "kab" },
  { title: "Kabyle (Arabic)", value: "kab-arab" },
  { title: "Kabyle (Arabic) (BCP 47)", value: "kab-Arab" },
  { title: "Kabyle (Latin)", value: "kab-latn" },
  { title: "Kabyle (Latin) (BCP 47)", value: "kab-Latn" },
  { title: "Kabyle (Tifinagh)", value: "kab-tfng" },
  { title: "Kabyle (Tifinagh) (BCP 47)", value: "kab-Tfng" },
  { title: "Kalaktang Monpa", value: "kkf" },
  { title: "Kalenjin", value: "kln" },
  { title: "Kamba", value: "kam" },
  { title: "Kannada", value: "kn" },
  { title: "Kanuri", value: "kr" },
  { title: "Kashmiri", value: "ks" },
  { title: "Kashmiri (Arabic)", value: "ks-arab" },
  { title: "Kashmiri (Arabic) (BCP 47)", value: "ks-Arab" },
  { title: "Kashmiri (Devanagari)", value: "ks-deva" },
  { title: "Kashmiri (Devanagari) (BCP 47)", value: "ks-Deva" },
  { title: "Kashubian", value: "csb" },
  { title: "Kazakh", value: "kk" },
  { title: "Kazakh (Cyrillic)", value: "kk-cyrl" },
  { title: "Kazakh (Cyrillic) (BCP 47)", value: "kk-Cyrl" },
  { title: "Kazakh (Latin)", value: "kk-latn" },
  { title: "Kazakh (Latin) (BCP 47)", value: "kk-Latn" },
  { title: "Khmer", value: "km" },
  { title: "Kinyarwanda", value: "rw" },
  { title: "Kirundi/Rundi", value: "rn" },
  { title: "Kiswahili/Swahili", value: "sw" },
  { title: "Komi", value: "kv" },
  { title: "Kongo", value: "kg" },
  { title: "Konkani", value: "kok" },
  { title: "Korean", value: "ko" },
  { title: "Koyra Chiini", value: "khq" },
  { title: "Koyraboro Senni", value: "ses" },
  { title: "Kuanyama/Kwanyama", value: "kj" },
  { title: "Kurdish", value: "ku" },
  { title: "Kurdish (Central/Sorani)", value: "ckb" },
  { title: "Kurdish (Hawar)", value: "ku-latn" },
  { title: "Kurdish (Hawar) (BCP 47)", value: "ku-Latn" },
  { title: "Kurdish (Kurmanji)", value: "ku-cyrl" },
  { title: "Kurdish (Kurmanji) (BCP 47)", value: "ku-Cyrl" },
  { title: "Kurdish (Sorani)", value: "ku-arab" },
  { title: "Kurdish (Sorani) (BCP 47)", value: "ku-Arab" },
  { title: "Kyrgyz", value: "ky" },
  { title: "K’iche", value: "quc" },
  { title: "Ladakhi", value: "lbi" },
  { title: "Langi", value: "lag" },
  { title: "Lao", value: "lo" },
  { title: "Latin", value: "la" },
  { title: "Latvian", value: "lv" },
  { title: "Limburgan/Limburger/Limburgish", value: "li" },
  { title: "Lingala", value: "ln" },
  { title: "Lithuanian", value: "lt" },
  { title: "Livonian", value: "liv" },
  { title: "Luba-Katanga/Luba-Shaba", value: "lu" },
  { title: "Luo", value: "luo" },
  { title: "Luxembourgish/Letzeburgesch", value: "lb" },
  { title: "Macedonian", value: "mk" },
  { title: "Machame", value: "jmc" },
  { title: "Makonde", value: "kde" },
  { title: "Malagasy", value: "mg" },
  { title: "Malay", value: "ms" },
  { title: "Malay (Jawi)", value: "ms-arab" },
  { title: "Malay (Jawi) (BCP 47)", value: "ms-Arab" },
  { title: "Malayalam", value: "ml" },
  { title: "Maltese", value: "mt" },
  { title: "Mandaic (Classical)", value: "myz" },
  { title: "Mandaic (Modern)", value: "mid" },
  { title: "Manx Gaelic", value: "gv" },
  { title: "Māori", value: "mi" },
  { title: "Marathi", value: "mr" },
  { title: "Marshallese", value: "mh" },
  { title: "Mapudungun", value: "arn" },
  { title: "Masai", value: "mas" },
  { title: "Mazanderani", value: "mzn" },
  { title: "Mende", value: "men" },
  { title: "Meru", value: "mer" },
  { title: "Moldavian/Moldovan (Deprecated)", value: "mo" },
  { title: "Mon (Myanmar)", value: "mnw-mymr" },
  { title: "Mon (Myanmar) (BCP 47)", value: "mnw-Mymr" },
  { title: "Mongolian", value: "mn" },
  { title: "Mongolian (Cyrillic)", value: "mn-cyrl" },
  { title: "Mongolian (Cyrillic) (BCP 47)", value: "mn-Cyrl" },
  { title: "Mongolian (Traditional Script)", value: "mn-mong" },
  { title: "Mongolian (Traditional Script) (BCP 47)", value: "mn-Mong" },
  { title: "Morisyen", value: "mfe" },
  { title: "Mohawk", value: "moh" },
  { title: "Nama", value: "naq" },
  { title: "Nauru", value: "na" },
  { title: "Navajo", value: "nv" },
  { title: "Ndonga", value: "ng" },
  { title: "Ndebele (Northern)", value: "nd" },
  { title: "Ndebele (Southern)", value: "nr" },
  { title: "Nepali", value: "ne" },
  { title: "Norwegian", value: "no" },
  { title: "Norwegian Bokmål", value: "nb" },
  { title: "Norwegian Nynorsk", value: "nn" },
  { title: "Nuosu/Sichuan Yi", value: "ii" },
  { title: "Nyankole", value: "nyn" },
  { title: "N’Ko'", value: "nqo" },
  { title: "Occitan", value: "oc" },
  { title: "Oriya", value: "or" },
  { title: "Oromo", value: "om" },
  { title: "Ossetian", value: "os" },
  { title: "Pāli", value: "pi" },
  { title: "Papiamento", value: "pap" },
  { title: "Pashto", value: "ps" },
  { title: "Polish", value: "pl" },
  { title: "Portuguese", value: "pt" },
  { title: "Punjabi", value: "pa" },
  { title: "Punjabi (Gurmukhi)", value: "pa-guru" },
  { title: "Punjabi (Gurmukhi) (BCP 47)", value: "pa-Guru" },
  { title: "Punjabi (Shahmukhi)", value: "pa-arab" },
  { title: "Punjabi (Shahmukhi) (BCP 47)", value: "pa-Arab" },
  { title: "Punjabi (Western)", value: "pnb" },
  { title: "Quechua", value: "qu" },
  { title: "Rejang", value: "rej" },
  { title: "Rejang (Aksara Rejang)", value: "rej-rjng" },
  { title: "Rejang (Aksara Rejang) (BCP 47)", value: "rej-Rjng" },
  { title: "Rejang (Latin)", value: "rej-latn" },
  { title: "Rejang (Latin) (BCP 47)", value: "rej-Latn" },
  { title: "Romansh", value: "rm" },
  { title: "Romanian/Moldavian/Moldovan", value: "ro" },
  { title: "Rombo", value: "rof" },
  { title: "Russian", value: "ru" },
  { title: "Rwa", value: "rwk" },
  { title: "Sakha/Yakut", value: "sah" },
  { title: "Samburu", value: "saq" },
  { title: "Sámi (Inari)", value: "smn" },
  { title: "Sámi (Lule)", value: "smj" },
  { title: "Sámi (Northern)", value: "se" },
  { title: "Sámi (Southern)", value: "sma" },
  { title: "Sámi (Skolt)", value: "sms" },
  { title: "Samoan", value: "sm" },
  { title: "Sango", value: "sg" },
  { title: "Sanskrit", value: "sa" },
  { title: "Santali", value: "sat" },
  { title: "Saraiki", value: "skr" },
  { title: "Saraiki (Arabic)", value: "skr-arab" },
  { title: "Saraiki (Arabic) (BCP 47)", value: "skr-Arab" },
  { title: "Saraiki (Devanagari)", value: "skr-deva" },
  { title: "Saraiki (Devanagari) (BCP 47)", value: "skr-Deva" },
  { title: "Sardinian", value: "sc" },
  { title: "Scots", value: "sco" },
  { title: "Scottish Gaelic", value: "gd" },
  { title: "Sena", value: "seh" },
  { title: "Serbian", value: "sr" },
  { title: "Serbian (Cyrillic)", value: "sr-cyrl" },
  { title: "Serbian (Cyrillic) (BCP 47)", value: "sr-Cyrl" },
  { title: "Serbian (Latin)", value: "sr-latn" },
  { title: "Serbian (Latin) (BCP 47)", value: "sr-Latn" },
  { title: "Serbo-Croatian", value: "sh" },
  { title: "Sesotho/Southern Sotho", value: "st" },
  { title: "Setswana/Tswana", value: "tn" },
  { title: "Sgaw Karen (Myanmar)", value: "ksw-mymr" },
  { title: "Sgaw Karen (Myanmar) (BCP 47)", value: "ksw-Mymr" },
  { title: "Sherpa", value: "xsr" },
  { title: "Sherpa (Devanagari)", value: "xsr-deva" },
  { title: "Sherpa (Devanagari) (BCP 47)", value: "xsr-Deva" },
  { title: "Sherpa (Tibetan)", value: "xsr-tibt" },
  { title: "Sherpa (Tibetan) (BCP 47)", value: "xsr-Tibt" },
  { title: "Shona", value: "sn" },
  { title: "Sikkimese", value: "sip" },
  { title: "Silesian", value: "szl" },
  { title: "Sindhi", value: "sd" },
  { title: "Sindhi (Arabic)", value: "sd-arab" },
  { title: "Sindhi (Arabic) (BCP 47)", value: "sd-Arab" },
  { title: "Sindhi (Devanagari)", value: "sd-deva" },
  { title: "Sindhi (Devanagari) (BCP 47)", value: "sd-Deva" },
  { title: "Sinhala", value: "si" },
  { title: "Siswati/Swati", value: "ss" },
  { title: "Slovak", value: "sk" },
  { title: "Slovenian", value: "sl" },
  { title: "Soga", value: "xog" },
  { title: "Somali", value: "so" },
  { title: "Sorbian (Lower)", value: "dsb" },
  { title: "Sorbian (Upper)", value: "hsb" },
  { title: "Southern Balochi", value: "bcc" },
  { title: "Spanish", value: "es" },
  { title: "Sundanese", value: "su" },
  { title: "Sundanese (Aksara Sunda)", value: "su-sund" },
  { title: "Sundanese (Aksara Sunda) (BCP 47)", value: "su-Sund" },
  { title: "Sundanese (Aksara Jawa)", value: "su-java" },
  { title: "Sundanese (Aksara Jawa) (BCP 47)", value: "su-Java" },
  { title: "Sundanese (Latin)", value: "su-latn" },
  { title: "Sundanese (Latin) (BCP 47)", value: "su-Latn" },
  { title: "Sundanese (Pégon)", value: "su-arab" },
  { title: "Sundanese (Pégon) (BCP 47)", value: "su-Arab" },
  { title: "Swedish", value: "sv" },
  { title: "Swiss German", value: "gsw" },
  { title: "Syriac", value: "syr" },
  { title: "Tachelhit", value: "shi" },
  { title: "Tachelhit (Arabic)", value: "shi-arab" },
  { title: "Tachelhit (Arabic) (BCP 47)", value: "shi-Arab" },
  { title: "Tachelhit (Latin)", value: "shi-latn" },
  { title: "Tachelhit (Latin) (BCP 47)", value: "shi-Latn" },
  { title: "Tachelhit (Tifinagh)", value: "shi-tfng" },
  { title: "Tachelhit (Tifinagh) (BCP 47)", value: "shi-Tfng" },
  { title: "Tagalog", value: "tl" },
  { title: "Tahitian", value: "ty" },
  { title: "Taita", value: "dav" },
  { title: "Tajik", value: "tg" },
  { title: "Tamazight", value: "tzm" },
  { title: "Tamazight (Arabic)", value: "tzm-arab" },
  { title: "Tamazight (Arabic) (BCP 47)", value: "tzm-Arab" },
  { title: "Tamazight (Latin)", value: "tzm-latn" },
  { title: "Tamazight (Latin) (BCP 47)", value: "tzm-Latn" },
  { title: "Tamazight (Tifinagh)", value: "tzm-tfng" },
  { title: "Tamazight (Tifinagh) (BCP 47)", value: "tzm-Tfng" },
  { title: "Tamil", value: "ta" },
  { title: "Tatar", value: "tt" },
  { title: "Telugu", value: "te" },
  { title: "Teso", value: "teo" },
  { title: "Thai", value: "th" },
  { title: "Tibetan", value: "bo" },
  { title: "Tigrinya", value: "ti" },
  { title: "Tongan", value: "to" },
  { title: "Tsangla", value: "tsi" },
  { title: "Tsonga", value: "ts" },
  { title: "Tuareg", value: "tmh" },
  { title: "Tuareg (Arabic)", value: "tmh-arab" },
  { title: "Tuareg (Arabic) (BCP 47)", value: "tmh-Arab" },
  { title: "Tuareg (Latin)", value: "tmh-latn" },
  { title: "Tuareg (Latin) (BCP 47)", value: "tmh-Latn" },
  { title: "Tuareg (Tifinagh)", value: "tmh-tfng" },
  { title: "Tuareg (Tifinagh) (BCP 47)", value: "tmh-Tfng" },
  { title: "Turkish", value: "tr" },
  { title: "Turkmen", value: "tk" },
  { title: "Twi", value: "tw" },
  { title: "Ukrainian", value: "uk" },
  { title: "Urdu", value: "ur" },
  { title: "Uyghur", value: "ug" },
  { title: "Uyghur (Arabic)", value: "ug-arab" },
  { title: "Uyghur (Arabic) (BCP 47)", value: "ug-Arab" },
  { title: "Uyghur (Cyrillic)", value: "ug-cyrl" },
  { title: "Uyghur (Cyrillic) (BCP 47)", value: "ug-Cyrl" },
  { title: "Uyghur (Latin)", value: "ug-latn" },
  { title: "Uyghur (Latin) (BCP 47)", value: "ug-Latn" },
  { title: "Uzbek", value: "uz" },
  { title: "Uzbek (Arabic)", value: "uz-arab" },
  { title: "Uzbek (Arabic) (BCP 47)", value: "uz-Arab" },
  { title: "Uzbek (Cyrillic)", value: "uz-cyrl" },
  { title: "Uzbek (Cyrillic) (BCP 47)", value: "uz-Cyrl" },
  { title: "Uzbek (Latin)", value: "uz-latn" },
  { title: "Uzbek (Latin) (BCP 47)", value: "uz-Latn" },
  { title: "Venda", value: "ve" },
  { title: "Vietnamese/Tiếng Việt", value: "vi" },
  { title: "Volapük", value: "vo" },
  { title: "Vunjo", value: "vun" },
  { title: "Walloon", value: "wa" },
  { title: "Welsh", value: "cy" },
  { title: "Western Frisian", value: "fy" },
  { title: "Wolof", value: "wo" },
  { title: "Wu", value: "wuu" },
  { title: "Xhosa", value: "xh" },
  { title: "Yiddish", value: "yi" },
  { title: "Yoruba", value: "yo" },
  { title: "Zhuang", value: "za" },
  { title: "Zangskari", value: "zau" },
  { title: "Zulu", value: "zu" },
];

export const REGIONS = [
  { title: "Unspecified", value: "" },
  { title: "Afghanistan", value: "AF" },
  { title: "Åland Island", value: "AX" },
  { title: "Albania", value: "AL" },
  { title: "Algeria", value: "DZ" },
  { title: "American Samoa", value: "AS" },
  { title: "Andorra", value: "AD" },
  { title: "Angola", value: "AO" },
  { title: "Anguilla", value: "AI" },
  { title: "Antarctica", value: "AQ" },
  { title: "Antigua and Barbuda", value: "AG" },
  { title: "Argentina", value: "AR" },
  { title: "Armenia", value: "AM" },
  { title: "Aruba", value: "AW" },
  { title: "Australia", value: "AU" },
  { title: "Austria", value: "AT" },
  { title: "Azerbaijan", value: "AZ" },
  { title: "Bahamas", value: "BS" },
  { title: "Bahrain", value: "BH" },
  { title: "Bangladesh", value: "BD" },
  { title: "Barbados", value: "BB" },
  { title: "Belarus", value: "BY" },
  { title: "Belgium", value: "BE" },
  { title: "Belize", value: "BZ" },
  { title: "Benin", value: "BJ" },
  { title: "Bermuda", value: "BM" },
  { title: "Bhutan", value: "BT" },
  { title: "Bolivia", value: "BO" },
  { title: "Bonaire, Sint Eustatius and Saba", value: "BQ" },
  { title: "Bosnia and Herzegovina", value: "BA" },
  { title: "Botswana", value: "BW" },
  { title: "Bouvet Island", value: "BV" },
  { title: "Brazil", value: "BR" },
  { title: "British Indian Ocean Territory", value: "IO" },
  { title: "Brunei Darussalam", value: "BN" },
  { title: "Bulgaria", value: "BG" },
  { title: "Burkina Faso", value: "BF" },
  { title: "Burma/Myanmar", value: "MM" },
  { title: "Burundi", value: "BI" },
  { title: "Cambodia", value: "KH" },
  { title: "Cameroon", value: "CM" },
  { title: "Canada", value: "CA" },
  { title: "Cape Verde", value: "CV" },
  { title: "Cayman Islands", value: "KY" },
  { title: "Central African Republic", value: "CF" },
  { title: "Chad", value: "TD" },
  { title: "Chechnya", value: "CE" },
  { title: "Chile", value: "CL" },
  { title: "China (Mainland) (People’s Republic of China)", value: "CN" },
  { title: "Christmas Islands", value: "CX" },
  { title: "Cocos (Keeling) Islands", value: "CC" },
  { title: "Colombia", value: "CO" },
  { title: "Comoros", value: "KM" },
  { title: "Congo (Brazzaville) (Republic of)", value: "CG" },
  { title: "Congo (Kinshasa) (Democratic Republic of)", value: "CD" },
  { title: "Cook Islands", value: "CK" },
  { title: "Costa Rica", value: "CR" },
  { title: "Côte d’Ivoire/Ivory Coast", value: "CI" },
  { title: "Croatia", value: "HR" },
  { title: "Cuba", value: "CU" },
  { title: "Curaçao", value: "CW" },
  { title: "Cyprus", value: "CY" },
  { title: "Czech Republic", value: "CZ" },
  { title: "Denmark", value: "DK" },
  { title: "Djibouti", value: "DJ" },
  { title: "Dominica", value: "DM" },
  { title: "Dominican Republic", value: "DO" },
  { title: "Ecuador", value: "EC" },
  { title: "Egypt", value: "EG" },
  { title: "El Salvador", value: "SV" },
  { title: "Equatorial Guinea", value: "GQ" },
  { title: "Eritrea", value: "ER" },
  { title: "Estonia", value: "EE" },
  { title: "Eswatini", value: "SZ" },
  { title: "Ethiopia", value: "ET" },
  { title: "European Union", value: "EU" },
  { title: "Falkland Islands/Malvinas", value: "FK" },
  { title: "Faroe Islands", value: "FO" },
  { title: "Fiji", value: "FJ" },
  { title: "Finland", value: "FI" },
  { title: "France", value: "FR" },
  { title: "France (Saint Barthélemy)", value: "BL" },
  { title: "French Guyana", value: "GF" },
  { title: "French Polynesia", value: "PF" },
  { title: "French Southern Territories", value: "TF" },
  { title: "Gabon", value: "GA" },
  { title: "Gambia", value: "GM" },
  { title: "Georgia", value: "GE" },
  { title: "Germany", value: "DE" },
  { title: "Ghana", value: "GH" },
  { title: "Gibraltar", value: "GI" },
  { title: "Greece", value: "GR" },
  { title: "Grenada", value: "GD" },
  { title: "Guadeloupe", value: "GP" },
  { title: "Guam", value: "GU" },
  { title: "Guatemala", value: "GT" },
  { title: "Guernsey and Alderney", value: "GG" },
  { title: "Guinea", value: "GN" },
  { title: "Guinea-Bissau", value: "GW" },
  { title: "Guyana", value: "GY" },
  { title: "Haiti", value: "HT" },
  { title: "Heard Island and McDonald Islands", value: "HM" },
  { title: "Holy See (Vatican)", value: "VA" },
  { title: "Honduras", value: "HN" },
  { title: "Hong Kong Special Administrative Region", value: "HK" },
  { title: "Hungary", value: "HU" },
  { title: "Iceland", value: "IS" },
  { title: "India", value: "IN" },
  { title: "Indonesia", value: "ID" },
  { title: "Iran", value: "IR" },
  { title: "Iraq", value: "IQ" },
  { title: "Ireland", value: "IE" },
  { title: "Isle of Man", value: "IM" },
  { title: "Israel", value: "IL" },
  { title: "Italy", value: "IT" },
  { title: "Jamaica", value: "JM" },
  { title: "Japan", value: "JP" },
  { title: "Jersey", value: "JE" },
  { title: "Jordan", value: "JO" },
  { title: "Kalaallit Nunaat/Greenland", value: "GL" },
  { title: "Kazakhstan", value: "KZ" },
  { title: "Kenya", value: "KE" },
  { title: "Kiribati", value: "KI" },
  { title: "Korea (North) (Democratic People’s Republic of)", value: "KP" },
  { title: "Korea (South) (Republic of)", value: "KR" },
  { title: "Kosovo", value: "XK" },
  { title: "Kuwait", value: "KW" },
  { title: "Kyrgystan", value: "KG" },
  { title: "Laos", value: "LA" },
  { title: "Latin America", value: 419 },
  { title: "Latvia", value: "LV" },
  { title: "Lebanon", value: "LB" },
  { title: "Lesotho", value: "LS" },
  { title: "Liberia", value: "LR" },
  { title: "Libya", value: "LY" },
  { title: "Liechtenstein", value: "LI" },
  { title: "Lithuania", value: "LT" },
  { title: "Luxembourg", value: "LU" },
  { title: "Macau Special Administrative Region", value: "MO" },
  { title: "Macedonia", value: "MK" },
  { title: "Madagascar", value: "MG" },
  { title: "Malawi", value: "MW" },
  { title: "Malaysia", value: "MY" },
  { title: "Maldives", value: "MV" },
  { title: "Mali", value: "ML" },
  { title: "Malta", value: "MT" },
  { title: "Marshall Islands", value: "MH" },
  { title: "Martinique", value: "MQ" },
  { title: "Mauritania", value: "MR" },
  { title: "Mauritius", value: "MU" },
  { title: "Mayotte", value: "YT" },
  { title: "Mexico", value: "MX" },
  { title: "Micronesia", value: "FM" },
  { title: "Moldova", value: "MD" },
  { title: "Monaco", value: "MC" },
  { title: "Mongolia", value: "MN" },
  { title: "Montenegro", value: "ME" },
  { title: "Montserrat", value: "MS" },
  { title: "Morocco", value: "MA" },
  { title: "Mozambique", value: "MZ" },
  { title: "Namibia", value: "NA" },
  { title: "Nauru", value: "NR" },
  { title: "Nepal", value: "NP" },
  { title: "Netherland", value: "NL" },
  { title: "Netherland Antilles", value: "AN" },
  { title: "New Caledonia", value: "NC" },
  { title: "New Zealand", value: "NZ" },
  { title: "Nicaragua", value: "NI" },
  { title: "Niger", value: "NE" },
  { title: "Nigeria", value: "NG" },
  { title: "Niue", value: "NU" },
  { title: "Norfolk Island", value: "NF" },
  { title: "Northern Mariana Islands", value: "MP" },
  { title: "Norway", value: "NO" },
  { title: "Oman", value: "OM" },
  { title: "Pakistan", value: "PK" },
  { title: "Palau", value: "PW" },
  { title: "Palestine", value: "PS" },
  { title: "Panama", value: "PA" },
  { title: "Papua New Guinea", value: "PG" },
  { title: "Paraguay", value: "PY" },
  { title: "Peru", value: "PE" },
  { title: "Philippines", value: "PH" },
  { title: "Pitcairn Island", value: "PN" },
  { title: "Poland", value: "PL" },
  { title: "Portugal", value: "PT" },
  { title: "Puerto Rico", value: "PR" },
  { title: "Qatar", value: "QA" },
  { title: "Réunion", value: "RE" },
  { title: "Romania", value: "RO" },
  { title: "Russia", value: "RU" },
  { title: "Rwanda", value: "RW" },
  { title: "Saint Helena, Ascension and Tristan da Cunha", value: "SH" },
  { title: "Saint Kitts and Nevis", value: "KN" },
  { title: "Saint Lucia", value: "LC" },
  { title: "Saint Martin (Dutch)", value: "SX" },
  { title: "Saint Martin (French)", value: "MF" },
  { title: "Saint Pierre and Miquelon", value: "PM" },
  { title: "Saint Vincent and the Grenadines", value: "VC" },
  { title: "Samoa", value: "WS" },
  { title: "San Marino", value: "SM" },
  { title: "Sao Tome and Principe", value: "ST" },
  { title: "Sark", value: "CQ" },
  { title: "Saudi Arabia", value: "SA" },
  { title: "Senegal", value: "SN" },
  { title: "Serbia", value: "RS" },
  { title: "Seychelles", value: "SC" },
  { title: "Sierra Leone", value: "SL" },
  { title: "Singapore", value: "SG" },
  { title: "Slovakia", value: "SK" },
  { title: "Slovenia", value: "SI" },
  { title: "Solomon Islands", value: "SB" },
  { title: "Somalia", value: "SO" },
  { title: "South Africa", value: "ZA" },
  { title: "South Georgia and the South Sandwich Islands", value: "GS" },
  { title: "South Sudan", value: "SS" },
  { title: "Spain", value: "ES" },
  { title: "Sri Lanka", value: "LK" },
  { title: "Sudan", value: "SD" },
  { title: "Suriname", value: "SR" },
  { title: "Svalbard and Jan Mayen Islands", value: "SJ" },
  { title: "Sweden", value: "SE" },
  { title: "Switzerland", value: "CH" },
  { title: "Syria", value: "SY" },
  { title: "Taiwan (Republic of China)", value: "TW" },
  { title: "Tajikistan", value: "TJ" },
  { title: "Tanzania", value: "TZ" },
  { title: "Thailand", value: "TH" },
  { title: "Timor Leste", value: "TL" },
  { title: "Togo", value: "TG" },
  { title: "Tokelau", value: "TK" },
  { title: "Tonga", value: "TO" },
  { title: "Trinidad and Tobago", value: "TT" },
  { title: "Tunisia", value: "TN" },
  { title: "Türkiye", value: "TR" },
  { title: "Turkmenistan", value: "TM" },
  { title: "Turks and Caicos Islands", value: "TC" },
  { title: "Tuvalu", value: "TV" },
  { title: "Uganda", value: "UG" },
  { title: "Ukraine", value: "UA" },
  { title: "United Arab Emirates", value: "AE" },
  { title: "United Kingdom", value: "GB" },
  { title: "United Nations Organization", value: "UN" },
  { title: "United States of America", value: "US" },
  { title: "United States Minor Outlying Islands", value: "UM" },
  { title: "Uruguay", value: "UY" },
  { title: "Uzbekistan", value: "UZ" },
  { title: "Vanuatu", value: "VU" },
  { title: "Venezuela", value: "VE" },
  { title: "Việt Nam", value: "VN" },
  { title: "Virgin Islands (British)", value: "VG" },
  { title: "Virgin Islands (U.S.)", value: "VI" },
  { title: "Wallis and Futuna", value: "WF" },
  { title: "Western Sahara", value: "EH" },
  { title: "Yemen", value: "YE" },
  { title: "Zambia", value: "ZM" },
  { title: "Zimbabwe", value: "ZW" },
];

export const CALENDAR_OPTIONS = {
  CALENDARS: [
    { title: "None", value: "" },
    { title: "Balinese Hindu/Indian Calendar", value: "indian" },
    { title: "Buddhist Calendar", value: "buddhist" },
    { title: "Coptic Calendar", value: "copt" },
    { title: "Ethiopic Amete Alem Calendar (Epoch Approx. 5493 B.C.E)", value: "ethioaa" },
    { title: "Ethiopic Amete Mihret Calendar (Epoch Approx, 8 C.E.)", value: "ethiopic" },
    { title: "Gregorian Calendar", value: "gregory" },
    { title: "Hijri Calendar", value: "islamic" },
    { title: "Hijri Calendar, Umm al-Qura", value: "islamic-umalqura" },
    { title: "Hijri Calendar, Astronomical Epoch", value: "islamic-tbla" },
    { title: "Hijri Calendar, Civil Epoch", value: "islamic-civil" },
    { title: "Hijri Calendar, Saudi Arabia Sighting", value: "islamic-rgsa" },
    { title: "Islamic Civil Calendar", value: "islamicc" },
    { title: "ISO 8601 Calendar", value: "iso8601" },
    { title: "Japanese Imperial Calendar", value: "japanese" },
    { title: "Persian Calendar", value: "persian" },
    { title: "Taiwanese R.O.C. Calendar", value: "roc" },
    { title: "Traditional Chinese Calendar", value: "chinese" },
    { title: "Traditional Hebrew Calendar", value: "hebrew" },
    { title: "Traditional Korean Calendar", value: "dangi" },
    { title: "Tibetan Calendar", value: "tibetan" },
    { title: "Ugaritic Calendar", value: "ugaritic" },
  ],
  NUMBERS: [
    { title: "None", value: "" },
    { title: "ASCII/Western Arabic Numbers", value: "latn" },
    { title: "Adlam Numbers", value: "adlm" },
    { title: "Ahom Numbers", value: "ahom" },
    { title: "Armenian Upper Case Numbers", value: "armn" },
    { title: "Armenian Lower Case Numbers", value: "armnlow" },
    { title: "Balinese Numbers", value: "bali" },
    { title: "Bengali Numbers", value: "beng" },
    { title: "Bhaiksuki Numbers", value: "bhks" },
    { title: "Brahmi Numbers", value: "brah" },
    { title: "Chakma Numbers", value: "cakm" },
    { title: "Cham Numbers", value: "cham" },
    { title: "Chisoi Numbers", value: "chis" },
    { title: "Cyrillic Numbers", value: "cyrl" },
    { title: "Devanagari Numbers", value: "deva" },
    { title: "Dives Akuru Numbers", value: "diak" },
    { title: "Eastern Arabic Numbers", value: "arab" },
    { title: "Eastern Arabic Numbers (Farsi, Urdu)", value: "arabext" },
    { title: "Ethiopian Numbers", value: "ethi" },
    { title: "Financial Numeral", value: "finance" },
    { title: "Full-Width Numbers", value: "fullwide" },
    { title: "Garay Numbers", value: "gara" },
    { title: "Georgian Numbers", value: "geor" },
    { title: "Greek Upper Case Numbers", value: "grek" },
    { title: "Greek Lower Case Numbers", value: "greklow" },
    { title: "Gujarati Numbers", value: "gujr" },
    { title: "Gunjala Gondi Numbers", value: "gong" },
    { title: "Gurung Khema Numbers", value: "gukh" },
    { title: "Gurmukhi Numbers", value: "guru" },
    { title: "Han Decimal Numbers", value: "hanidec" },
    { title: "Han Numbers (Lunar Calendar)", value: "hanidays" },
    { title: "Hanifi Rohingya Numbers", value: "rohg" },
    { title: "Hebrew Upper Case Numbers", value: "hebr" },
    { title: "Javanese Numbers", value: "java" },
    { title: "Japanese Numbers", value: "jpan" },
    { title: "Japanese Financial Numbers", value: "jpanfin" },
    { title: "Japanese First-Year Gannen Numbering for Japanese Calendar", value: "jpanyear" },
    { title: "Kannada Numbers", value: "knda" },
    { title: "Kayah Li Numbers", value: "kali" },
    { title: "Kayah Li Numbers (Latin)", value: "kalil" },
    { title: "Kawi Numbers", value: "kawi" },
    { title: "Khmer Numbers", value: "khmr" },
    { title: "Khmer Symbols", value: "khmrsym" },
    { title: "Khmer Symbols (Latin)", value: "khmrlatn" },
    { title: "Khudawadi Numbers", value: "sind" },
    { title: "Kirat Rai Numbers", value: "krai" },
    { title: "Korean Hangul Numbers", value: "hang" },
    { title: "Lao Numbers", value: "laoo" },
    { title: "Lepcha Numbers", value: "lepc" },
    { title: "Limbu Numbers", value: "limb" },
    { title: "Lisu Numbers", value: "lisudec" },
    { title: "Lisu Traditional Numbers", value: "lisutr" },
    { title: "Lycian Upper Case Numbers", value: "lyci" },
    { title: "Lycian Lower Case Numbers", value: "lycilow" },
    { title: "Lydian Upper Case Numbers", value: "lydi" },
    { title: "Lydian Lower Case Numbers", value: "lydilow" },
    { title: "Malayalam Numbers", value: "mlym" },
    { title: "Mandaic Upper Case Numbers", value: "mand" },
    { title: "Mandaic Lower Case Numbers", value: "mandlow" },
    { title: "Masaram Gondi Numbers", value: "gonm" },
    { title: "Modi Numbers", value: "modi" },
    { title: "Mongolian Numbers", value: "mong" },
    { title: "Mro Numbers", value: "mroo" },
    { title: "Meitei Mayek Numbers", value: "mtei" },
    { title: "Myanmar Numbers", value: "mymr" },
    { title: "Myanmar Eastern Pwo Karen Numbers", value: "mymrepka" },
    { title: "Myanmar Pao Numbers", value: "mymrpao" },
    { title: "Myanmar Shan Numbers", value: "mymrshan" },
    { title: "Myanmar Tai Laing Numbers", value: "mymrtlng" },
    { title: "Nag Mundari Numbers", value: "nagm" },
    { title: "New Tai Lüe Numbers", value: "talu" },
    { title: "Newa Numbers", value: "newa" },
    { title: "Nyiakeng Puachue Hmong Numbers", value: "hmnp" },
    { title: "N’Ko Numbers", value: "nkoo" },
    { title: "Ol Chiki Numbers", value: "olck" },
    { title: "Ol Onal Numbers", value: "onao" },
    { title: "Oriya Numbers", value: "orya" },
    { title: "Osmanya Numbers", value: "osma" },
    { title: "Pahawh Hmong Numbers", value: "hmng" },
    { title: "Roman Upper Case Numbers", value: "roman" },
    { title: "Roman Lower Case Numbers", value: "romanlow" },
    { title: "Saurashtra Numbers", value: "saur" },
    { title: "Sharada Numbers", value: "shrd" },
    { title: "Simplified Chinese Numbers", value: "hans" },
    { title: "Simplified Chinese Financial Numbers", value: "hansfin" },
    { title: "Sinhala Numbers", value: "sinh" },
    { title: "Sora Sompeng Numbers", value: "sora" },
    { title: "Sundanese Numbers", value: "sund" },
    { title: "Sunuwar Numbers", value: "sunu" },
    { title: "Tai Tham Hora (Secular) Numbers", value: "lana" },
    { title: "Tai Tham Tham (Ecclesiastical) Numbers", value: "lanatham" },
    { title: "Takri Numbers", value: "takr" },
    { title: "Tamil Decimal Numbers", value: "tamldec" },
    { title: "Tamil Traditional Numbers", value: "taml" },
    { title: "Tangsa Numbers", value: "tnsa" },
    { title: "Telugu Numbers", value: "telu" },
    { title: "Thai Numbers", value: "thai" },
    { title: "Tirhuta Numbers", value: "tirh" },
    { title: "Tibetan Numbers", value: "tibt" },
    { title: "Tolong Siki Numbers", value: "tols" },
    { title: "Traditional Chinese Numbers", value: "hant" },
    { title: "Traditional Chinese Financial Numbers", value: "hantfin" },
    { title: "Vai Numbers", value: "vaii" },
    { title: "Warang Citi Numbers", value: "wara" },
    { title: "Wancho Numbers", value: "wcho" },
  ],
};
