import { getTimezoneOffset } from "date-fns-tz";
import { getLangDir } from "rtl-detect";
import { countries, zones } from "moment-timezone/data/meta/latest.json";

export const LANGUAGES = [
  { title: "Abkhaizan", value: "ab" },
  { title: "Afar", value: "aa" },
  { title: "Afrikaans", value: "af" },
  { title: "Akan", value: "ak" },
  { title: "Albanian", value: "sq" },
  { title: "Albanian (Gheg)", value: "aln" },
  { title: "Albanian (Tosk)", value: "als" },
  { title: "Amharic", value: "am" },
  { title: "Anishinaabe/Ojibwe", value: "oj" },
  { title: "Arabic", value: "ar" },
  { title: "Aramaic", value: "arc" },
  { title: "Aragonese", value: "an" },
  { title: "Arbëreshe", value: "aae" },
  { title: "Armenian", value: "hy" },
  { title: "Arvanitika (Greek)", value: "aat-grek" },
  { title: "Arvanitika (Greek) (Mozilla)", value: "aat-Grek" },
  { title: "Assamese", value: "as" },
  { title: "Asturian", value: "ast" },
  { title: "Asu", value: "asa" },
  { title: "Avaric", value: "av" },
  { title: "Avestan", value: "ae" },
  { title: "Aymara", value: "ay" },
  { title: "Azerbaijani", value: "az" },
  { title: "Azerbaijani (Cyrillic)", value: "az-cyrl" },
  { title: "Azerbaijani (Cyrillic) (Mozilla)", value: "az-Cyrl" },
  { title: "Azerbaijani (Latin)", value: "az-latn" },
  { title: "Azerbaijani (Latin) (Mozilla)", value: "az-Latn" },
  { title: "Bakhtiari", value: "bqi" },
  { title: "Balinese (Latin)", value: "ban-latn" },
  { title: "Balinese (Latin) (Mozilla)", value: "ban-Latn" },
  { title: "Balinese (Aksara Bali)", value: "ban-bali" },
  { title: "Balinese (Aksara Bali) (Mozilla)", value: "ban-Bali" },
  { title: "Bambara", value: "bm" },
  { title: "Bashkir", value: "ba" },
  { title: "Basque", value: "eu" },
  { title: "Batak (Latin)", value: "btk-latn" },
  { title: "Batak (Latin) (Mozilla)", value: "btk-Latn" },
  { title: "Batak (Surat Batak)", value: "btk-batk" },
  { title: "Batak (Surat Batak) (Mozilla)", value: "btk-Batk" },
  { title: "Belarusian", value: "be" },
  { title: "Bemba", value: "bem" },
  { title: "Bena", value: "bez" },
  { title: "Bengali", value: "bn" },
  { title: "Berber", value: "ber" },
  { title: "Berber (Latin)", value: "ber-latn" },
  { title: "Berber (Latin) (Mozilla)", value: "ber-Latn" },
  { title: "Berber (Tifinagh)", value: "ber-tfng" },
  { title: "Berber (Tifinagh) (Mozilla)", value: "ber-Tfng" },
  { title: "Bihari", value: "bh" },
  { title: "Bislama", value: "bi" },
  { title: "Bosnian", value: "bs" },
  { title: "Bosnian (Cyrillic)", value: "bs-cyrl" },
  { title: "Bosnian (Cyrillic) (Mozilla)", value: "bs-Cyrl" },
  { title: "Bosnian (Latin)", value: "bs-latn" },
  { title: "Bosnian (Latin) (Mozilla)", value: "bs-Latn" },
  { title: "Breton", value: "br" },
  { title: "Buginese (Latin)", value: "bug-latn" },
  { title: "Buginese (Latin) (Mozilla)", value: "bug-Latn" },
  { title: "Buginese (Lontara)", value: "bug-bugi" },
  { title: "Buginese (Lontara) (Mozilla)", value: "bug-Bugi" },
  { title: "Buginese (Aksara Makassar Kuno)", value: "bug-maka" },
  { title: "Buginese (Aksara Makassar Kuno) (Mozilla)", value: "bug-Maka" },
  { title: "Bulgarian", value: "bg" },
  { title: "Burmese (Unicode)", value: "my" },
  { title: "Burmese (Zawgyi)", value: "my-qaag" },
  { title: "Burmese (Zawgyi) (Mozilla)", value: "my-Qaag" },
  { title: "Cantonese", value: "yue" },
  { title: "Cantonese (Simplified Han)", value: "yue-hans" },
  { title: "Cantonese (Simplified Han) (Mozilla)", value: "yue-Hans" },
  { title: "Cantonese (Traditional Han)", value: "yue-hant" },
  { title: "Cantonese (Traditional Han) (Mozilla)", value: "yue-Hant" },
  { title: "Catalan", value: "ca" },
  { title: "Chamorro", value: "ch" },
  { title: "Chechen", value: "ce" },
  { title: "Cherokee", value: "chr" },
  { title: "Chicewa/Chewa/Nyanja", value: "ny" },
  { title: "Chigga", value: "cgg" },
  { title: "Chinese", value: "zh" },
  { title: "Chinese (Simplified Han)", value: "zh-hans" },
  { title: "Chinese (Simplified Han) (Mozilla)", value: "zh-Hans" },
  { title: "Chinese (Traditional Han)", value: "zh-hant" },
  { title: "Chinese (Traditional Han) (Mozilla)", value: "zh-Hant" },
  { title: "Church Slavonic", value: "cu" },
  { title: "Chuvash", value: "cv" },
  { title: "Cornish", value: "kw" },
  { title: "Corsican", value: "co" },
  { title: "Cree", value: "cr" },
  { title: "Croatian", value: "hr" },
  { title: "Czech", value: "cs" },
  { title: "Danish", value: "da" },
  { title: "Dari (Afghan Farsi/Persian)", value: "prs" },
  { title: "Dhivehi", value: "dv" },
  { title: "Dutch", value: "nl" },
  { title: "Dzongkha", value: "dz" },
  { title: "Embu", value: "ebu" },
  { title: "English", value: "en" },
  { title: "Esperanto", value: "eo" },
  { title: "Estonian", value: "et" },
  { title: "Ewe", value: "ee" },
  { title: "Faroese", value: "fo" },
  { title: "Farsi/Persian", value: "fa" },
  { title: "Fijian", value: "fj" },
  { title: "Filipino", value: "fil" },
  { title: "Finnish", value: "fi" },
  { title: "French", value: "fr" },
  { title: "Fula/Fulah/Pulaar/Pular", value: "ff" },
  { title: "Galician", value: "gl" },
  { title: "Ganda/Luganda", value: "lg" },
  { title: "Georgian", value: "ka" },
  { title: "German", value: "de" },
  { title: "Gilaki", value: "glk" },
  { title: "Greek", value: "el" },
  { title: "Greenlandic/Kalaallisut", value: "kl" },
  { title: "Guarani", value: "gn" },
  { title: "Gujarati", value: "gu" },
  { title: "Gusii", value: "guz" },
  { title: "Haitian Creole", value: "ht" },
  { title: "Hausa", value: "ha" },
  { title: "Hausa (Arabic)", value: "ha-arab" },
  { title: "Hausa (Arabic) (Mozilla)", value: "ha-Arab" },
  { title: "Hausa (Latin)", value: "ha-latn" },
  { title: "Hausa (Latin) (Mozilla)", value: "ha-Latn" },
  { title: "Hawaiian", value: "haw" },
  { title: "Hebrew", value: "he" },
  { title: "Herero", value: "hz" },
  { title: "Hindi", value: "hi" },
  { title: "Hiri Motu/Police Motu", value: "ho" },
  { title: "Hungarian", value: "hu" },
  { title: "Icelandic", value: "is" },
  { title: "Ido", value: "io" },
  { title: "Igbo", value: "ig" },
  { title: "Indonesian", value: "id" },
  { title: "Interlingua", value: "ia" },
  { title: "Interlingue", value: "ie" },
  { title: "Inuktitut", value: "iu" },
  { title: "Inupiaq", value: "ik" },
  { title: "Irish", value: "ga" },
  { title: "Italian", value: "it" },
  { title: "Japanese", value: "ja" },
  { title: "Javanese (Latin)", value: "jv-latn" },
  { title: "Javanese (Latin) (Mozilla)", value: "jv-Latn" },
  { title: "Javanese (Aksara Jawa)", value: "jv-java" },
  { title: "Javanese (Aksara Jawa) (Mozilla)", value: "jv-Java" },
  { title: "Kabuverdianu", value: "kea" },
  { title: "Kabyle (Arabic)", value: "kab-arab" },
  { title: "Kabyle (Arabic) (Mozilla)", value: "kab-Arab" },
  { title: "Kabyle (Latin)", value: "kab-latn" },
  { title: "Kabyle (Latin) (Mozilla)", value: "kab-Latn" },
  { title: "Kabyle (Tifinagh)", value: "kab-tfng" },
  { title: "Kabyle (Tifinagh) (Mozilla)", value: "kab-Tfng" },
  { title: "Kalenjin", value: "kln" },
  { title: "Kamba", value: "kam" },
  { title: "Kannada", value: "kn" },
  { title: "Kanuri", value: "kr" },
  { title: "Kashmiri (Arabic)", value: "ks-arab" },
  { title: "Kashmiri (Arabic) (Mozilla)", value: "ks-Arab" },
  { title: "Kashmiri (Devanagari)", value: "ks-deva" },
  { title: "Kashmiri (Devanagari) (Mozilla)", value: "ks-Deva" },
  { title: "Kashubian", value: "csb" },
  { title: "Kazakh", value: "kk" },
  { title: "Kazakh (Cyrillic)", value: "kk-cyrl" },
  { title: "Kazakh (Cyrillic) (Mozilla)", value: "kk-Cyrl" },
  { title: "Kazakh (Latin)", value: "kk-latn" },
  { title: "Kazakh (Latin) (Mozilla)", value: "kk-Latn" },
  { title: "Khmer", value: "km" },
  { title: "Kikuyu", value: "ki" },
  { title: "Kinyarwanda", value: "rw" },
  { title: "Kirundi", value: "rn" },
  { title: "Kiswahili/Swahili", value: "sw" },
  { title: "Komi", value: "kv" },
  { title: "Kongo", value: "kg" },
  { title: "Konkani", value: "kok" },
  { title: "Korean", value: "ko" },
  { title: "Koyra Chiini", value: "khq" },
  { title: "Koyraboro Senni", value: "ses" },
  { title: "Kurdish (Central)", value: "ckb" },
  { title: "Kurdish (Hawar)", value: "ku-latn" },
  { title: "Kurdish (Hawar) (Mozilla)", value: "ku-Latn" },
  { title: "Kurdish (Kurmanji)", value: "ku-cyrl" },
  { title: "Kurdish (Kurmanji) (Mozilla)", value: "ku-Cyrl" },
  { title: "Kurdish (Sorani)", value: "ku-arab" },
  { title: "Kurdish (Sorani) (Mozilla)", value: "ku-Arab" },
  { title: "Kwanyama", value: "kj" },
  { title: "Kyrgyz", value: "ky" },
  { title: "K’iche", value: "quc" },
  { title: "Langi", value: "lag" },
  { title: "Lao", value: "lo" },
  { title: "Latin", value: "la" },
  { title: "Latvian", value: "lv" },
  { title: "Limburgish", value: "li" },
  { title: "Lingala", value: "ln" },
  { title: "Lithuanian", value: "lt" },
  { title: "Livonian", value: "liv" },
  { title: "Luga-Katanga", value: "lu" },
  { title: "Luo", value: "luo" },
  { title: "Luxembourgish", value: "lb" },
  { title: "Macedonian", value: "mk" },
  { title: "Machame", value: "jmc" },
  { title: "Makonde", value: "kde" },
  { title: "Malagasy", value: "mg" },
  { title: "Malay", value: "ms" },
  { title: "Malay (Jawi)", value: "ms-arab" },
  { title: "Malay (Jawi) (Mozilla)", value: "ms-Arab" },
  { title: "Malayalam", value: "ml" },
  { title: "Maltese", value: "mt" },
  { title: "Manx Gaelic", value: "gv" },
  { title: "Marathi", value: "mr" },
  { title: "Marshallese", value: "mh" },
  { title: "Mapudungun", value: "arn" },
  { title: "Masai", value: "mas" },
  { title: "Mazanderani", value: "mzn" },
  { title: "Meru", value: "mer" },
  { title: "Min Nan", value: "nan" },
  { title: "Min Nan (Simplified Han)", value: "nan-hans" },
  { title: "Min Nan (Simplified Han) (Mozilla)", value: "nan-Hans" },
  { title: "Min Nan (Traditional Han)", value: "nan-hant" },
  { title: "Min Nan (Traditional Han) (Mozilla)", value: "nan-Hant" },
  { title: "Moldavian", value: "mo" },
  { title: "Mon", value: "mnw-mymr" },
  { title: "Mon (Mozilla)", value: "mnw-Mymr" },
  { title: "Mongolian", value: "mn" },
  { title: "Mongolian (Cyrillic)", value: "mn-cyrl" },
  { title: "Mongolian (Cyrillic) (Mozilla)", value: "mn-Cyrl" },
  { title: "Mongolian (Traditional Script)", value: "mn-mong" },
  { title: "Mongolian (Traditional Script) (Mozilla)", value: "mn-Mong" },
  { title: "Morisyen", value: "mfe" },
  { title: "Moroccan Arabic", value: "ary" },
  { title: "Mohawk", value: "moh" },
  { title: "Māori", value: "mi" },
  { title: "Nama", value: "naq" },
  { title: "Nauru", value: "na" },
  { title: "Navajo", value: "nv" },
  { title: "Ndonga", value: "ng" },
  { title: "Nepali", value: "ne" },
  { title: "Northern Ndebele", value: "nd" },
  { title: "Norwegian", value: "no" },
  { title: "Norwegian Bokmål", value: "nb" },
  { title: "Norwegian Nynorsk", value: "nn" },
  { title: "Nuosu/Sichuan Yi", value: "ii" },
  { title: "Nyankole", value: "nyn" },
  { title: "N’Ko'", value: "nqo" },
  { title: "Occitan", value: "oc" },
  { title: "Oriya", value: "or" },
  { title: "Oromo", value: "om" },
  { title: "Ossetian", value: "os" },
  { title: "Papiamento", value: "pap" },
  { title: "Pashto", value: "ps" },
  { title: "Polish", value: "pl" },
  { title: "Portuguese", value: "pt" },
  { title: "Punjabi", value: "pa" },
  { title: "Punjabi (Gurmukhi)", value: "pa-guru" },
  { title: "Punjabi (Gurmukhi) (Mozilla)", value: "pa-Guru" },
  { title: "Punjabi (Shahmukhi)", value: "pa-arab" },
  { title: "Punjabi (Shahmukhi) (Mozilla)", value: "pa-Arab" },
  { title: "Punjabi (Western)", value: "pnb" },
  { title: "Pāli", value: "pi" },
  { title: "Quechua", value: "qu" },
  { title: "Rejang (Latin)", value: "rej-latn" },
  { title: "Rejang (Latin) (Mozilla)", value: "rej-Latn" },
  { title: "Rejang (Aksara Rejang)", value: "rej-rjng" },
  { title: "Rejang (Aksara Rejang) (Mozilla)", value: "rej-Rjng" },
  { title: "Romansh", value: "rm" },
  { title: "Romanian", value: "ro" },
  { title: "Rombo", value: "rof" },
  { title: "Russian", value: "ru" },
  { title: "Rwa", value: "rwk" },
  { title: "Sakha/Yakut", value: "sah" },
  { title: "Samburu", value: "saq" },
  { title: "Sámi (Inari)", value: "smn" },
  { title: "Sámi (Lule)", value: "smj" },
  { title: "Sámi (Northern)", value: "se" },
  { title: "Sámi (Southern)", value: "sma" },
  { title: "Sámi (Skolt)", value: "sms" },
  { title: "Samoan", value: "sm" },
  { title: "Sango", value: "sg" },
  { title: "Sanskrit", value: "sa" },
  { title: "Santali", value: "sat" },
  { title: "Saraiki (Arabic)", value: "skr-arab" },
  { title: "Saraiki (Arabic) (Mozilla)", value: "skr-Arab" },
  { title: "Saraiki (Devanagari)", value: "skr-deva" },
  { title: "Saraiki (Devanagari) (Mozilla)", value: "skr-Deva" },
  { title: "Sardinian", value: "sc" },
  { title: "Scots", value: "sco" },
  { title: "Scottish Gaelic", value: "gd" },
  { title: "Sena", value: "seh" },
  { title: "Serbian", value: "sr" },
  { title: "Serbian (Cyrillic)", value: "sr-cyrl" },
  { title: "Serbian (Cyrillic) (Mozilla)", value: "sr-Cyrl" },
  { title: "Serbian (Latin)", value: "sr-latn" },
  { title: "Serbian (Latin) (Mozilla)", value: "sr-Latn" },
  { title: "Serbo-Croatian", value: "sh" },
  { title: "Sesotho", value: "st" },
  { title: "Setswana/Tswana", value: "tn" },
  { title: "Sgaw Karen", value: "ksw-mymr" },
  { title: "Sgaw Karen (Mozilla)", value: "ksw-Mymr" },
  { title: "Shona", value: "sn" },
  { title: "Silesian", value: "szl" },
  { title: "Sindhi", value: "sd" },
  { title: "Sindhi (Arabic)", value: "sd-arab" },
  { title: "Sindhi (Arabic) (Mozilla)", value: "sd-Arab" },
  { title: "Sindhi (Devanagari)", value: "sd-deva" },
  { title: "Sindhi (Devanagari) (Mozilla)", value: "sd-Deva" },
  { title: "Sinhala", value: "si" },
  { title: "Siswati/Swati", value: "ss" },
  { title: "Slovak", value: "sk" },
  { title: "Slovenian", value: "sl" },
  { title: "Soga", value: "xog" },
  { title: "Somali", value: "so" },
  { title: "Sorbian (Lower)", value: "dsb" },
  { title: "Sorbian (Upper)", value: "hsb" },
  { title: "Southern Balochi", value: "bcc" },
  { title: "Southern Ndebele", value: "nr" },
  { title: "Spanish", value: "es" },
  { title: "Sundanese (Latin)", value: "su-latn" },
  { title: "Sundanese (Latin) (Mozilla)", value: "su-Latn" },
  { title: "Sundanese (Aksara Sunda)", value: "su-sund" },
  { title: "Sundanese (Aksara Sunda) (Mozilla)", value: "su-Sund" },
  { title: "Swedish", value: "sv" },
  { title: "Swiss German", value: "gsw" },
  { title: "Syriac", value: "syc" },
  { title: "Tachelhit (Arabic)", value: "shi-arab" },
  { title: "Tachelhit (Arabic) (Mozilla)", value: "shi-Arab" },
  { title: "Tachelhit (Latin)", value: "shi-latn" },
  { title: "Tachelhit (Latin) (Mozilla)", value: "shi-Latn" },
  { title: "Tachelhit (Tifinagh)", value: "shi-tfng" },
  { title: "Tachelhit (Tifinagh) (Mozilla)", value: "shi-Tfng" },
  { title: "Tagalog", value: "tl" },
  { title: "Tahitian", value: "ty" },
  { title: "Taita", value: "dav" },
  { title: "Tajik", value: "tg" },
  { title: "Tamazight", value: "tzm" },
  { title: "Tamazight (Arabic)", value: "tzm-arab" },
  { title: "Tamazight (Arabic) (Mozilla)", value: "tzm-Arab" },
  { title: "Tamazight (Latin)", value: "tzm-latn" },
  { title: "Tamazight (Latin) (Mozilla)", value: "tzm-Latn" },
  { title: "Tamazight (Tifinagh)", value: "tzm-tfng" },
  { title: "Tamazight (Tifinagh) (Mozilla)", value: "tzm-Tfng" },
  { title: "Tamil", value: "ta" },
  { title: "Tatar", value: "tt" },
  { title: "Telugu", value: "te" },
  { title: "Teso", value: "teo" },
  { title: "Thai", value: "th" },
  { title: "Tibetan", value: "bo" },
  { title: "Tigrinya", value: "ti" },
  { title: "Tongan", value: "to" },
  { title: "Tsonga", value: "ts" },
  { title: "Tuareg", value: "tmh" },
  { title: "Tuareg (Arabic)", value: "tmh-arab" },
  { title: "Tuareg (Arabic) (Mozilla)", value: "tmh-Arab" },
  { title: "Tuareg (Latin)", value: "tmh-latn" },
  { title: "Tuareg (Latin) (Mozilla)", value: "tmh-Latn" },
  { title: "Tuareg (Tifinagh)", value: "tmh-tfng" },
  { title: "Tuareg (Tifinagh) (Mozilla)", value: "tmh-Tfng" },
  { title: "Turkish", value: "tr" },
  { title: "Turkmen", value: "tk" },
  { title: "Twi", value: "tw" },
  { title: "Ukrainian", value: "uk" },
  { title: "Urdu", value: "ur" },
  { title: "Uyghur", value: "ug" },
  { title: "Uyghur (Arabic)", value: "ug-arab" },
  { title: "Uyghur (Arabic) (Mozilla)", value: "ug-Arab" },
  { title: "Uyghur (Cyrillic)", value: "ug-cyrl" },
  { title: "Uyghur (Cyrillic) (Mozilla)", value: "ug-Cyrl" },
  { title: "Uyghur (Latin)", value: "ug-latn" },
  { title: "Uyghur (Latin) (Mozilla)", value: "ug-Latn" },
  { title: "Uzbek", value: "uz" },
  { title: "Uzbek (Arabic)", value: "uz-arab" },
  { title: "Uzbek (Arabic) (Mozilla)", value: "uz-Arab" },
  { title: "Uzbek (Cyrillic)", value: "uz-cyrl" },
  { title: "Uzbek (Cyrillic) (Mozilla)", value: "uz-Cyrl" },
  { title: "Uzbek (Latin)", value: "uz-latn" },
  { title: "Uzbek (Latin) (Mozilla)", value: "uz-Latn" },
  { title: "Venda", value: "ve" },
  { title: "Vietnamese", value: "vi" },
  { title: "Volapük", value: "vo" },
  { title: "Vunjo", value: "vun" },
  { title: "Walloon", value: "wa" },
  { title: "Welsh", value: "cy" },
  { title: "Western Frisian", value: "fy" },
  { title: "Wolof", value: "wo" },
  { title: "Wu", value: "wuu" },
  { title: "Xhosa", value: "xh" },
  { title: "Yiddish", value: "yi" },
  { title: "Yoruba", value: "yo" },
  { title: "Zhuang", value: "za" },
  { title: "Zulu", value: "zu" },
];

export const REGIONS = [
  { title: "Afghanistan", value: "AF" },
  { title: "Åland Island", value: "AX" },
  { title: "Albania", value: "AL" },
  { title: "Algeria", value: "DZ" },
  { title: "American Samoa", value: "AS" },
  { title: "Andorra", value: "AD" },
  { title: "Angola", value: "AO" },
  { title: "Anguilla", value: "AI" },
  { title: "Antarctica", value: "AQ" },
  { title: "Antigua and Barbuda", value: "AG" },
  { title: "Argentina", value: "AR" },
  { title: "Armenia", value: "AM" },
  { title: "Aruba", value: "AW" },
  { title: "Australia", value: "AU" },
  { title: "Austria", value: "AT" },
  { title: "Azerbaijan", value: "AZ" },
  { title: "Bahamas", value: "BS" },
  { title: "Bahrain", value: "BH" },
  { title: "Bangladesh", value: "BD" },
  { title: "Barbados", value: "BB" },
  { title: "Belarus", value: "BY" },
  { title: "Belgium", value: "BE" },
  { title: "Belize", value: "BZ" },
  { title: "Benin", value: "BJ" },
  { title: "Bermuda", value: "BM" },
  { title: "Bhutan", value: "BT" },
  { title: "Bolivia", value: "BO" },
  { title: "Bonaire, Sint Eustatius and Saba", value: "BQ" },
  { title: "Bosnia and Herzegovina", value: "BA" },
  { title: "Botswana", value: "BW" },
  { title: "Bouvet Island", value: "BV" },
  { title: "Brazil", value: "BR" },
  { title: "British Indian Ocean Territory", value: "IO" },
  { title: "Brunei Darussalam", value: "BN" },
  { title: "Bulgaria", value: "BG" },
  { title: "Burkina Faso", value: "BF" },
  { title: "Burma/Myanmar", value: "MM" },
  { title: "Burundi", value: "BI" },
  { title: "Cambodia", value: "KH" },
  { title: "Cameroon", value: "CM" },
  { title: "Canada", value: "CA" },
  { title: "Cape Verde", value: "CV" },
  { title: "Cayman Islands", value: "KY" },
  { title: "Central African Republic", value: "CF" },
  { title: "Chad", value: "TD" },
  { title: "Chechnya", value: "CE" },
  { title: "Chile", value: "CL" },
  { title: "China (Mainland) (People’s Republic of China)", value: "CN" },
  { title: "Christmas Islands", value: "CX" },
  { title: "Cocos (Keeling) Islands", value: "CC" },
  { title: "Colombia", value: "CO" },
  { title: "Comoros", value: "KM" },
  { title: "Congo (Brazzaville)", value: "CG" },
  { title: "Congo (Kinshasa) (Democratic Republic of)", value: "CD" },
  { title: "Cook Islands", value: "CK" },
  { title: "Costa Rica", value: "CR" },
  { title: "Côte d’Ivoire/Ivory Coast", value: "CI" },
  { title: "Croatia", value: "HR" },
  { title: "Cuba", value: "CU" },
  { title: "Curaçao", value: "CW" },
  { title: "Cyprus", value: "CY" },
  { title: "Czech Republic", value: "CZ" },
  { title: "Denmark", value: "DK" },
  { title: "Djibouti", value: "DJ" },
  { title: "Dominica", value: "DM" },
  { title: "Dominican Republic", value: "DO" },
  { title: "Ecuador", value: "EC" },
  { title: "Egypt", value: "EG" },
  { title: "El Salvador", value: "SV" },
  { title: "Equatorial Guinea", value: "GQ" },
  { title: "Eritrea", value: "ER" },
  { title: "Estonia", value: "EE" },
  { title: "Eswatini", value: "SZ" },
  { title: "Ethiopia", value: "ET" },
  { title: "European Union", value: "EU" },
  { title: "Falkland Islands/Malvinas", value: "FK" },
  { title: "Faroe Islands", value: "FO" },
  { title: "Fiji", value: "FJ" },
  { title: "Finland", value: "FI" },
  { title: "France", value: "FR" },
  { title: "France (Saint Barthélemy)", value: "BL" },
  { title: "French Guyana", value: "GF" },
  { title: "French Polynesia", value: "PF" },
  { title: "French Southern Territories", value: "TF" },
  { title: "Gabon", value: "GA" },
  { title: "Gambia", value: "GM" },
  { title: "Georgia", value: "GE" },
  { title: "Germany", value: "DE" },
  { title: "Ghana", value: "GH" },
  { title: "Gibraltar", value: "GI" },
  { title: "Greece", value: "GR" },
  { title: "Grenada", value: "GD" },
  { title: "Guadeloupe", value: "GP" },
  { title: "Guam", value: "GU" },
  { title: "Guatemala", value: "GT" },
  { title: "Guernsey and Alderney", value: "GG" },
  { title: "Guinea", value: "GN" },
  { title: "Guinea-Bissau", value: "GW" },
  { title: "Guyana", value: "GY" },
  { title: "Haiti", value: "HT" },
  { title: "Heard Island and McDonald Islands", value: "HM" },
  { title: "Holy See (Vatican)", value: "VA" },
  { title: "Honduras", value: "HN" },
  { title: "Hong Kong Special Administrative Region", value: "HK" },
  { title: "Hungary", value: "HU" },
  { title: "Iceland", value: "IS" },
  { title: "India", value: "IN" },
  { title: "Indonesia", value: "ID" },
  { title: "Iran", value: "IR" },
  { title: "Iraq", value: "IQ" },
  { title: "Ireland", value: "IE" },
  { title: "Isle of Man", value: "IM" },
  { title: "Israel", value: "IL" },
  { title: "Italy", value: "IT" },
  { title: "Jamaica", value: "JM" },
  { title: "Japan", value: "JP" },
  { title: "Jersey", value: "JE" },
  { title: "Jordan", value: "JO" },
  { title: "Kalaallit Nunaat/Greenland", value: "GL" },
  { title: "Kazakhstan", value: "KZ" },
  { title: "Kenya", value: "KE" },
  { title: "Kiribati", value: "KI" },
  { title: "Korea (North) (Democratic People’s Republic of)", value: "KP" },
  { title: "Korea (South) (Republic of)", value: "KR" },
  { title: "Kosovo", value: "XK" },
  { title: "Kuwait", value: "KW" },
  { title: "Kyrgystan", value: "KG" },
  { title: "Laos", value: "LA" },
  { title: "Latin America", value: 419 },
  { title: "Latvia", value: "LV" },
  { title: "Lebanon", value: "LB" },
  { title: "Lesotho", value: "LS" },
  { title: "Liberia", value: "LR" },
  { title: "Libya", value: "LY" },
  { title: "Liechtenstein", value: "LI" },
  { title: "Lithuania", value: "LT" },
  { title: "Luxembourg", value: "LU" },
  { title: "Macau Special Administrative Region", value: "MO" },
  { title: "Macedonia", value: "MK" },
  { title: "Madagascar", value: "MG" },
  { title: "Malawi", value: "MW" },
  { title: "Malaysia", value: "MY" },
  { title: "Maldives", value: "MV" },
  { title: "Mali", value: "ML" },
  { title: "Malta", value: "MT" },
  { title: "Marshall Islands", value: "MH" },
  { title: "Martinique", value: "MQ" },
  { title: "Mauritania", value: "MR" },
  { title: "Mauritius", value: "MU" },
  { title: "Mayotte", value: "YT" },
  { title: "Mexico", value: "MX" },
  { title: "Micronesia", value: "FM" },
  { title: "Moldova", value: "MD" },
  { title: "Monaco", value: "MC" },
  { title: "Mongolia", value: "MN" },
  { title: "Montenegro", value: "ME" },
  { title: "Montserrat", value: "MS" },
  { title: "Morocco", value: "MA" },
  { title: "Mozambique", value: "MZ" },
  { title: "Namibia", value: "NA" },
  { title: "Nauru", value: "NR" },
  { title: "Nepal", value: "NP" },
  { title: "Netherland", value: "NL" },
  { title: "Netherland Antilles", value: "AN" },
  { title: "New Caledonia", value: "NC" },
  { title: "New Zealand", value: "NZ" },
  { title: "Nicaragua", value: "NI" },
  { title: "Niger", value: "NE" },
  { title: "Nigeria", value: "NG" },
  { title: "Niue", value: "NU" },
  { title: "Norfolk Island", value: "NF" },
  { title: "Northern Mariana Islands", value: "MP" },
  { title: "Norway", value: "NO" },
  { title: "Oman", value: "OM" },
  { title: "Pakistan", value: "PK" },
  { title: "Palau", value: "PW" },
  { title: "Palestine", value: "PS" },
  { title: "Panama", value: "PA" },
  { title: "Papua New Guinea", value: "PG" },
  { title: "Paraguay", value: "PY" },
  { title: "Peru", value: "PE" },
  { title: "Philippines", value: "PH" },
  { title: "Pitcairn Island", value: "PN" },
  { title: "Poland", value: "PL" },
  { title: "Portugal", value: "PT" },
  { title: "Puerto Rico", value: "PR" },
  { title: "Qatar", value: "QA" },
  { title: "Réunion", value: "RE" },
  { title: "Romania", value: "RO" },
  { title: "Russia", value: "RU" },
  { title: "Rwanda", value: "RW" },
  { title: "Saint Helena, Ascension and Tristan da Cunha", value: "SH" },
  { title: "Saint Kitts and Nevis", value: "KN" },
  { title: "Saint Lucia", value: "LC" },
  { title: "Saint Martin (Dutch)", value: "SX" },
  { title: "Saint Martin (French)", value: "MF" },
  { title: "Saint Pierre and Miquelon", value: "PM" },
  { title: "Saint Vincent and the Grenadines", value: "VC" },
  { title: "Samoa", value: "WS" },
  { title: "San Marino", value: "SM" },
  { title: "Sao Tome and Principe", value: "ST" },
  { title: "Saudi Arabia", value: "SA" },
  { title: "Senegal", value: "SN" },
  { title: "Serbia", value: "RS" },
  { title: "Seychelles", value: "SC" },
  { title: "Sierra Leone", value: "SL" },
  { title: "Singapore", value: "SG" },
  { title: "Slovakia", value: "SK" },
  { title: "Slovenia", value: "SI" },
  { title: "Solomon Islands", value: "SB" },
  { title: "Somalia", value: "SO" },
  { title: "South Africa", value: "ZA" },
  { title: "South Georgia and the South Sandwich Islands", value: "GS" },
  { title: "South Sudan", value: "SS" },
  { title: "Spain", value: "ES" },
  { title: "Sri Lanka", value: "LK" },
  { title: "Sudan", value: "SD" },
  { title: "Suriname", value: "SR" },
  { title: "Svalbard and Jan Mayen Islands", value: "SJ" },
  { title: "Sweden", value: "SE" },
  { title: "Switzerland", value: "CH" },
  { title: "Syria", value: "SY" },
  { title: "Taiwan (Republic of China)", value: "TW" },
  { title: "Tajikistan", value: "TJ" },
  { title: "Tanzania", value: "TZ" },
  { title: "Thailand", value: "TH" },
  { title: "Timor Leste", value: "TL" },
  { title: "Togo", value: "TG" },
  { title: "Tokelau", value: "TK" },
  { title: "Tonga", value: "TO" },
  { title: "Trinidad and Tobago", value: "TT" },
  { title: "Tunisia", value: "TN" },
  { title: "Türkiye", value: "TR" },
  { title: "Turkmenistan", value: "TM" },
  { title: "Turks and Caicos Islands", value: "TC" },
  { title: "Tuvalu", value: "TV" },
  { title: "Uganda", value: "UG" },
  { title: "Ukraine", value: "UA" },
  { title: "United Arab Emirates", value: "AE" },
  { title: "United Kingdom", value: "GB" },
  { title: "United Nations Organization", value: "UN" },
  { title: "United States of America", value: "US" },
  { title: "United States Minor Outlying Islands", value: "UM" },
  { title: "Uruguay", value: "UY" },
  { title: "Uzbekistan", value: "UZ" },
  { title: "Vanuatu", value: "VU" },
  { title: "Venezuela", value: "VE" },
  { title: "Việt Nam", value: "VN" },
  { title: "Virgin Islands (British)", value: "VG" },
  { title: "Virgin Islands (U.S.)", value: "VI" },
  { title: "Wallis and Futuna", value: "WF" },
  { title: "Western Sahara", value: "EH" },
  { title: "Yemen", value: "YE" },
  { title: "Zambia", value: "ZM" },
  { title: "Zimbabwe", value: "ZW" },
  { title: "Unspecified", value: "" },
];

export const getFlagEmoji = regionalCode =>
  typeof regionalCode === "string"
    ? regionalCode
        .toUpperCase()
        .split("")
        // .map(char => String.fromCodePoint(char.charCodeAt(0) + 127397))
        // .map(char => String.fromCodePoint(127397 + char.charCodeAt(0)))
        // .map(char => String.fromCodePoint(char.charCodeAt(0) + 0x1f1a5))
        .map(char => String.fromCodePoint(0x1f1a5 + char.charCodeAt(0)))
        .join("")
    : // .reduce((a, b) => `${a}${b}`)
      "(No flag for this region.)";

export const CALENDAR_OPTIONS = [
  { title: "None", value: "" },
  { title: "ASCII Numbers", value: "nu-latn" },
  { title: "Adlam Numbers", value: "nu-adlm" },
  { title: "Ahom Numbers", value: "nu-ahom" },
  { title: "Armenian Upper Case Numbers", value: "nu-armn" },
  { title: "Armenian Lower Case Numbers", value: "nu-armnlow" },
  { title: "Balinese Numbers", value: "nu-bali" },
  { title: "Balinese Hindu Calendar", value: "ca-indian" },
  { title: "Balinese Hindu Calendar, Balinese Numbers", value: "ca-indian-nu-bali" },
  { title: "Bengali Numbers", value: "nu-beng" },
  { title: "Bhaiksuki Numbers", value: "nu-bhks" },
  { title: "Brahmi Numbers", value: "nu-brah" },
  { title: "Buddhist Calendar", value: "ca-buddhist" },
  { title: "Buddhist Calendar, Bhaiksuki Numbers", value: "ca-buddhist-nu-bhks" },
  { title: "Chakma Numbers", value: "nu-cakm" },
  { title: "Cham Numbers", value: "nu-cham" },
  { title: "Coptic Calendar", value: "nu-copt" },
  { title: "Cyrillic Numbers", value: "nu-cyrl" },
  { title: "Devanagari Numbers", value: "nu-deva" },
  { title: "Dives Akuru Numbers", value: "nu-diak" },
  { title: "Eastern Arabic Numbers", value: "nu-arab" },
  { title: "Eastern Arabic Numbers (Farsi, Urdu)", value: "nu-arabext" },
  { title: "Ethiopian Numbers", value: "nu-ethi" },
  { title: "Ethiopic Amete Alem Calendar", value: "ca-ethioaa" },
  { title: "Ethiopic Amete Alem Calendar, Ethiopian Numbers", value: "ca-ethioaa-nu-ethi" },
  { title: "Ethiopic Amete Mihret Calendar", value: "ca-ethiopic" },
  { title: "Ethiopic Amete Mihret Calendar, Ethiopian Numbers", value: "ca-ethiopic-nu-ethi" },
  { title: "Garay Numbers", value: "nu-gara" },
  { title: "Georgian Numbers", value: "nu-geor" },
  { title: "Greek Upper Case Numbers", value: "nu-grek" },
  { title: "Greek Lower Case Numbers", value: "nu-greklow" },
  { title: "Gregorian Calendar", value: "ca-gregory" },
  { title: "Gregorian Calendar, ASCII Number", value: "ca-gregory-nu-latn" },
  { title: "Gregorian Calendar, Bengali Numbers", value: "ca-gregory-nu-beng" },
  { title: "Gregorian Calendar, Bhaiksuki Numbers", value: "ca-gregory-nu-bhks" },
  { title: "Gregorian Calendar, Brahmi Numbers", value: "ca-gregory-nu-brah" },
  { title: "Gregorian Calendar, Devanagari Numbers", value: "ca-gregory-nu-deva" },
  { title: "Gregorian Calendar, Eastern Arabic Numbers", value: "ca-gregory-nu-arab" },
  {
    title: "Gregorian Calendar, Eastern Arabic Numbers (Farsi, Urdu)",
    value: "ca-gregory-nu-arabext",
  },
  { title: "Gregorian Calendar, Gujarati Numbers", value: "ca-gregory-nu-gujr" },
  { title: "Gregorian Calendar, Gunjala Gondi Numbers", value: "ca-gregory-nu-gong" },
  { title: "Gregorian Calendar, Gurmukhi Numbers", value: "ca-gregory-nu-guru" },
  { title: "Gregorian Calendar, Hanifi Rohingnya Numbers", value: "ca-gregory-nu-rohg" },
  { title: "Gregorian Calendar, Malayalam Numbers", value: "ca-gregory-nu-mlym" },
  { title: "Gregorian Calendar, Masala Gondi Numbers", value: "ca-gregory-nu-gonm" },
  { title: "Gregorian Calendar, Ol Chiki Numbers", value: "ca-gregory-nu-olck" },
  { title: "Gregorian Calendar, Oriya Numbers", value: "ca-gregory-nu-orya" },
  { title: "Gregorian Calendar, Sinhala Numbers", value: "ca-gregory-nu-sinh" },
  { title: "Gregorian Calendar, Sora Sompeng Numbers", value: "ca-gregory-nu-sora" },
  { title: "Gregorian Calendar, Tamil Decimal Numbers", value: "ca-gregory-nu-tamldec" },
  { title: "Gregorian Calendar, Tamil Traditional Numbers", value: "ca-gregory-nu-taml" },
  { title: "Gregorian Calendar, Telugu Numbers", value: "ca-gregory-nu-telu" },
  { title: "Gregorian Calendar, Thai Numbers", value: "ca-gregory-nu-thai" },
  { title: "Gujarati Numbers", value: "nu-gujr" },
  { title: "Gurung Khema Numbers", value: "nu-gukh" },
  { title: "Gurmukhi Numbers", value: "nu-guru" },
  { title: "Gunjala Gondi Numbers", value: "nu-gong" },
  { title: "Han Numbers", value: "nu-hanidays" },
  { title: "Hanifi Rohingya Numbers", value: "nu-rohg" },
  { title: "Hijri Calendar", value: "ca-islamic" },
  { title: "Hijri Calendar, ASCII Numbers", value: "ca-islamic-nu-latn" },
  { title: "Hijri Calendar, Bengali Numbers", value: "ca-islamic-nu-beng" },
  { title: "Hijri Calendar, Bhaiksuki Numbers", value: "ca-islamic-nu-bhks" },
  { title: "Hijri Calendar, Brahmi Numbers", value: "ca-islamic-nu-brah" },
  { title: "Hijri Calendar, Devanagari Numbers", value: "ca-islamic-nu-deva" },
  { title: "Hijri Calendar, Eastern Arabic Numbers", value: "ca-islamic-nu-arab" },
  { title: "Hijri Calendar, Eastern Arabic Numbers (Farsi, Urdu)", value: "ca-islamic-nu-arabext" },
  { title: "Hijri Calendar, Gujarati Numbers", value: "ca-islamic-nu-gujr" },
  { title: "Hijri Calendar, Gunjala Gondi Numbers", value: "ca-islamic-nu-gong" },
  { title: "Hijri Calendar, Gurmukhi Numbers", value: "ca-islamic-nu-guru" },
  { title: "Hijri Calendar, Hanifi Rohingya Numbers", value: "ca-islamic-nu-rohg" },
  { title: "Hijri Calendar, Malayalam Numbers", value: "ca-islamic-nu-mlym" },
  { title: "Hijri Calendar, Masala Gondi Numbers", value: "ca-islamic-nu-gonm" },
  { title: "Hijri Calendar, Ol Chiki Numbers", value: "ca-islamic-nu-olck" },
  { title: "Hijri Calendar, Oriya Numbers", value: "ca-islamic-nu-orya" },
  { title: "Hijri Calendar, Sinhala Numbers", value: "ca-islamic-nu-sinh" },
  { title: "Hijri Calendar, Sora Sompeng Numbers", value: "ca-islamic-nu-sora" },
  { title: "Hijri Calendar, Tamil Decimal Numbers", value: "ca-islamic-nu-tamldec" },
  { title: "Hijri Calendar, Tamil Traditional Numbers", value: "ca-islamic-nu-taml" },
  { title: "Hijri Calendar, Telugu Numbers", value: "ca-islamic-nu-telu" },
  { title: "Hijri Calendar, Thai Numberss", value: "ca-islamic-nu-thai" },
  { title: "ISO 8601 Calendar", value: "ca-iso8601" },
  { title: "Japanese Emperial Calendar", value: "ca-japanese" },
  { title: "Jewish Calendar", value: "ca-hebrew" },
  { title: "Jewish Calendar, Hebrew Numeral", value: "ca-hebrew-nu-hebr" },
  { title: "Khudawadi Numbers", value: "nu-sind" },
  { title: "Malayalam Numbers", value: "nu-mlym" },
  { title: "Masala Gondi Numbers", value: "nu-gonm" },
  { title: "Modi Numbers", value: "nu-modi" },
  { title: "Mongolian Numbers", value: "nu-mong" },
  { title: "Mroo Numbers", value: "nu-mroo" },
  { title: "Meitei Mayek Numbers", value: "nu-mtei" },
  { title: "Myanmar Numbers", value: "nu-mymr" },
  { title: "Nag Mundari Numbers", value: "nu-nagm" },
  { title: "New Tai Lüe Numbers", value: "nu-talu" },
  { title: "Newa Numbers", value: "nu-newa" },
  { title: "N’Ko Numbers", value: "nu-nkoo" },
  { title: "Ol Chiki Numbers", value: "nu-olck" },
  { title: "Ol Onal Numbers", value: "nu-onao" },
  { title: "Oriya Numbers", value: "nu-orya" },
  { title: "Osmanya Numbers", value: "nu-osma" },
  { title: "Persian Calendar", value: "ca-persian" },
  { title: "Roman Upper Case Numbers", value: "nu-roman" },
  { title: "Roman Lower Case Numbers", value: "nu-romanlow" },
  { title: "Saurashtra Numbers", value: "nu-saur" },
  { title: "Sharada Numbers", value: "nu-shrd" },
  { title: "Sinhala Numbers", value: "nu-sinh" },
  { title: "Sora Sompeng Numbers", value: "nu-sora" },
  { title: "Sundanese Numbers", value: "nu-sund" },
  { title: "Sunuwar Numbers", value: "nu-sunu" },
  { title: "Taiwanese R.O.C. Calendar", value: "ca-roc" },
  { title: "Taiwanese R.O.C. Calendar, Han Numbers", value: "ca-roc-nu-hanidays" },
  { title: "Takri Numbers", value: "nu-takr" },
  { title: "Tamil Decimal Numbers", value: "nu-tamldec" },
  { title: "Tamil Traditional Numbers", value: "nu-taml" },
  { title: "Tangsa Numbers", value: "nu-tnsa" },
  { title: "Telugu Numbers", value: "nu-telu" },
  { title: "Thai Calendar", value: "ca-buddhist" },
  { title: "Thai Calendar, ASCII Numbers", value: "ca-buddhist-nu-latn" },
  { title: "Thai Calendar, Thai Numbers", value: "ca-buddhist-nu-thai" },
  { title: "Thai Numbers", value: "nu-thai" },
  { title: "Tirhuta Numbers", value: "nu-tirh" },
  { title: "Tibetan Numbers", value: "nu-tibt" },
  { title: "Traditional Chinese Calendar", value: "ca-chinese" },
  { title: "Traditional Chinese Calendar, Han Numbers", value: "ca-chinese-nu-hanidays" },
  { title: "Traditional Indian Calendar", value: "ca-indian" },
  { title: "Traditional Indian Calendar, ASCII Numbers", value: "ca-indian-nu-latn" },
  { title: "Traditional Indian Calendar, Arabic-Indic Numbers", value: "ca-indian-nu-arab" },
  { title: "Traditional Indian Calendar, Bengali Numbers", value: "ca-indian-nu-beng" },
  { title: "Traditional Indian Calendar, Bhaiksuki Numbers", value: "ca-indian-nu-bhks" },
  { title: "Traditional Indian Calendar, Brahmi Numbers", value: "ca-indian-nu-brah" },
  { title: "Traditional Indian Calendar, Devanagari Numbers", value: "ca-indian-nu-deva" },
  { title: "Traditional Indian Calendar, Gujarati Numbers", value: "ca-indian-nu-gujr" },
  { title: "Traditional Indian Calendar, Gunjala Gondi Numbers", value: "ca-indian-nu-gong" },
  { title: "Traditional Indian Calendar, Gurmukhi Numbers", value: "ca-indian-nu-guru" },
  { title: "Traditional Indian Calendar, Hanifi Rohngya Numbers", value: "ca-indian-nu-rohg" },
  { title: "Traditional Indian Calendar, Malayalam Numbers", value: "ca-indian-nu-mlym" },
  { title: "Traditional Indian Calendar, Masala Gondi Numbers", value: "ca-indian-nu-gonm" },
  { title: "Traditional Indian Calendar, Ol Chiki Numbers", value: "ca-indian-nu-olck" },
  { title: "Traditional Indian Calendar, Oriya Numbers", value: "ca-indian-nu-orya" },
  { title: "Traditional Indian Calendar, Sinhala Numbers", value: "ca-indian-nu-sinh" },
  { title: "Traditional Indian Calendar, Sora Sompeng Numbers", value: "ca-indian-nu-sora" },
  { title: "Traditional Indian Calendar, Tamil Decimal Numbers", value: "ca-indian-nu-tamldec" },
  { title: "Traditional Indian Calendar, Tamil Traditional Numbers", value: "ca-indian-nu-taml" },
  { title: "Traditional Indian Calendar, Telugu Numbers", value: "ca-indian-nu-telu" },
  { title: "Traditional Indian Calendar, Thai Numbers", value: "ca-indian-nu-thai" },
  { title: "Traditional Indian Calendar, Urdu Numbers", value: "ca-indian-nu-arabext" },
  { title: "Traditional Korean Calendar", value: "ca-dangi" },
  { title: "Vai Numbers", value: "nu-vaii" },
  { title: "Warang Citi Numbers", value: "nu-wara" },
  { title: "Wancho Numbers", value: "nu-wcho" },
];

export const direction = lang =>
  lang.includes("arab") ||
  lang.includes("Arab") ||
  lang.includes("hebr") ||
  lang.includes("Hebr") ||
  lang.startsWith("syc") ||
  (lang.startsWith("skr") && (!lang.includes("deva") || !lang.includes("Deva")))
    ? "rtl"
    : getLangDir(lang);

const date = new Date();
const timeZoneOffsetUTC = timeZone => {
  const tzOffset = getTimezoneOffset(timeZone, date);
  const tzHourResult = tzOffset / (60 * 60 * 1000);
  const tzHour =
    tzOffset > 0 ? Math.floor(tzHourResult) : tzOffset < 0 ? Math.ceil(tzHourResult) : tzHourResult;
  const tzMinute = (tzOffset % (60 * 60 * 1000)) / (60 * 1000);
  const absTzMinute = Math.abs(tzMinute);
  return (
    "UTC" +
    (tzHour !== 0
      ? (tzHour > 0 ? "+" : "") + tzHour + ":" + (absTzMinute < 10 ? "0" : "") + absTzMinute
      : tzMinute !== 0
      ? (tzMinute > 0 ? "+" : "-") + "0:" + (absTzMinute < 10 ? "0" : "") + absTzMinute
      : "")
  );
};
const timeZoneOffsetLong = timeZone =>
  Intl.DateTimeFormat("en", { timeStyle: "long", timeZone })
    .formatToParts(date)
    .find(({ type }) => type === "timeZoneName").value;
const timeZoneOffsetFull = timeZone =>
  Intl.DateTimeFormat("en", { timeStyle: "full", timeZone })
    .formatToParts(date)
    .find(({ type }) => type === "timeZoneName").value;
const compatibilityTimeZone = [
  { timeZone: "Africa/Asmera", regionalCode: "ER" },
  { timeZone: "America/Buenos_Aires", regionalCode: "AR" },
  { timeZone: "America/Catamarca", regionalCode: "AR" },
  { timeZone: "America/Coral_Harbour", regionalCode: "CA" },
  { timeZone: "America/Cordoba", regionalCode: "AR" },
  { timeZone: "America/Godthab", regionalCode: "GL" },
  { timeZone: "America/Indianapolis", regionalCode: "US" },
  { timeZone: "America/Jujuy", regionalCode: "AR" },
  { timeZone: "America/Louisville", regionalCode: "US" },
  { timeZone: "America/Mendoza", regionalCode: "AR" },
  { timeZone: "Asia/Calcutta", regionalCode: "IN" },
  { timeZone: "Asia/Chongqing", regionalCode: "CN" },
  { timeZone: "Asia/Harbin", regionalCode: "CN" },
  { timeZone: "Asia/Katmandu", regionalCode: "NP" },
  { timeZone: "Asia/Rangoon", regionalCode: "MM" },
  { timeZone: "Asia/Saigon", regionalCode: "VN" },
  { timeZone: "Atlantic/Faeroe", regionalCode: "FO" },
  { timeZone: "Europe/Kiev", regionalCode: "UA" },
  { timeZone: "Pacific/Enderbury", regionalCode: "KI" },
  { timeZone: "Pacific/Ponape", regionalCode: "FM" },
  { timeZone: "Pacific/Truk", regionalCode: "FM" },
];
const timeZoneRegion = timeZone => {
  const regionalCode = zones[timeZone]?.countries[0];
  // const region = regionalCode ? countries[regionalCode]?.name || "" : "";
  const region = regionalCode
    ? REGIONS.find(({ value }) => value === regionalCode)?.title || ""
    : "";

  const timeZoneIsObsolete = compatibilityTimeZone.some(tz => tz.timeZone === timeZone);
  const obsoleteTimeZoneRegionalCode =
    compatibilityTimeZone.find(tz => tz.timeZone === timeZone)?.regionalCode || "";
  const obsoleteTimeZoneRegion =
    REGIONS.find(region => region.value === obsoleteTimeZoneRegionalCode)?.title || "";

  return region !== ""
    ? `${region} ${getFlagEmoji(regionalCode)}`
    : timeZoneIsObsolete
    ? `${obsoleteTimeZoneRegion} ${getFlagEmoji(obsoleteTimeZoneRegionalCode)}`
    : timeZone === "UTC"
    ? "Coordinated Universal Time"
    : "Unspecified Region";
};
export const TIMEZONES = Intl.supportedValuesOf("timeZone").map(tz => ({
  title:
    `${tz} (${timeZoneOffsetUTC(tz)}|${timeZoneOffsetLong(tz)}|${timeZoneOffsetFull(tz)}), ` +
    timeZoneRegion(tz),
  value: tz,
}));

const regionalCodeArray = zones[Intl.DateTimeFormat().resolvedOptions().timeZone]?.countries || [];
export const localeRegionData = {
  name: regionalCodeArray.length !== 0 ? countries[regionalCodeArray[0]].name : "No data",
  code: regionalCodeArray.length !== 0 ? countries[regionalCodeArray[0]].abbr : "No data",
  flag: regionalCodeArray.length !== 0 ? getFlagEmoji(regionalCodeArray[0]) : "No data",
  timeZones: regionalCodeArray.length !== 0 ? countries[regionalCodeArray[0]].zones : [],
};
