export const LANGUAGES = [
  { title: "Abkhaizan", value: "ab" },
  { title: "Afar", value: "aa" },
  { title: "Afrikaans", value: "af" },
  { title: "Akan", value: "ak" },
  { title: "Albanian", value: "sq" },
  { title: "Albanian (Gheg)", value: "aln" },
  { title: "Albanian (Tosk)", value: "als" },
  { title: "Amharic", value: "am" },
  { title: "Anishinaabe/Ojibwe", value: "oj" },
  { title: "Arabic", value: "ar" },
  { title: "Aragonese", value: "an" },
  { title: "Arbëreshe", value: "aae" },
  { title: "Armenian", value: "hy" },
  { title: "Arvanitika (Greek)", value: "aat-grek" },
  { title: "Assamese", value: "as" },
  { title: "Asu", value: "asa" },
  { title: "Avaric", value: "av" },
  { title: "Avestan", value: "ae" },
  { title: "Aymara", value: "ay" },
  { title: "Azerbaijani (Cyrillic)", value: "az-cyrl" },
  { title: "Azerbaijani (Latin)", value: "az-latn" },
  { title: "Balinese (Latin)", value: "ban-latn" },
  { title: "Bambara", value: "bm" },
  { title: "Bashkir", value: "ba" },
  { title: "Basque", value: "eu" },
  { title: "Batak", value: "btk" },
  { title: "Belarusian", value: "be" },
  { title: "Bemba", value: "bem" },
  { title: "Bena", value: "bez" },
  { title: "Bengali", value: "bn" },
  { title: "Berber (Latin)", value: "ber-latn" },
  { title: "Berber (Tifinagh)", value: "ber-tfng" },
  { title: "Bihari", value: "bh" },
  { title: "Bislama", value: "bi" },
  { title: "Bosnian (Cyrillic)", value: "bs-cyrl" },
  { title: "Bosnian (Latin)", value: "bs-latn" },
  { title: "Breton", value: "br" },
  { title: "Bulgarian", value: "bg" },
  { title: "Burmese (Unicode)", value: "my-mymr" },
  { title: "Burmese (Zawgyi)", value: "my-qaag" },
  { title: "Cantonese", value: "yue" },
  { title: "Catalan", value: "ca" },
  { title: "Chamorro", value: "ch" },
  { title: "Chechen", value: "ce" },
  { title: "Cherokee", value: "chr" },
  { title: "Chicewa/Chewa/Nyanja", value: "ny" },
  { title: "Chigga", value: "cgg" },
  { title: "Chinese (Simplified)", value: "zh-hans" },
  { title: "Chinese (Traditional)", value: "zh-hant" },
  { title: "Church Slavonic", value: "cu" },
  { title: "Chuvash", value: "cv" },
  { title: "Cornish", value: "kw" },
  { title: "Corsican", value: "co" },
  { title: "Cree", value: "cr" },
  { title: "Croatian", value: "hr" },
  { title: "Czech", value: "cs" },
  { title: "Danish", value: "da" },
  { title: "Dari/Farsi/Persian", value: "fa" },
  { title: "Divehi", value: "dv" },
  { title: "Dutch", value: "nl" },
  { title: "Dzongkha", value: "nz" },
  { title: "Embu", value: "ebu" },
  { title: "English", value: "en" },
  { title: "Esperanto", value: "eo" },
  { title: "Estonian", value: "et" },
  { title: "Ewe", value: "ee" },
  { title: "Faroese", value: "fo" },
  { title: "Fijian", value: "fj" },
  { title: "Filipino", value: "fil" },
  { title: "Finnish", value: "fi" },
  { title: "French", value: "fr" },
  { title: "Fula/Fulah/Pulaar/Pular", value: "ff" },
  { title: "Galician", value: "gl" },
  { title: "Ganda/Luganda", value: "lg" },
  { title: "Georgian", value: "ka" },
  { title: "German", value: "de" },
  { title: "Greek", value: "el" },
  { title: "Greenlandic/Kalaallisut", value: "kl" },
  { title: "Guarani", value: "gn" },
  { title: "Gujarati", value: "gu" },
  { title: "Gusii", value: "guz" },
  { title: "Haitian Creole", value: "ht" },
  { title: "Hausa (Arabic)", value: "ha-arab" },
  { title: "Hausa (Latin)", value: "ha-latn" },
  { title: "Hawaiian", value: "haw" },
  { title: "Hebrew", value: "he" },
  { title: "Herero", value: "hz" },
  { title: "Hindi", value: "hi" },
  { title: "Hiri Motu/Police Motu", value: "ho" },
  { title: "Hungarian", value: "hu" },
  { title: "Icelandic", value: "is" },
  { title: "Ido", value: "io" },
  { title: "Igbo", value: "ig" },
  { title: "Indonesian", value: "id" },
  { title: "Interlingua", value: "ia" },
  { title: "Interlingue", value: "ie" },
  { title: "Inuktitut", value: "iu" },
  { title: "Inupiaq", value: "ik" },
  { title: "Irish", value: "ga" },
  { title: "Italian", value: "it" },
  { title: "Japanese", value: "ja" },
  { title: "Javanese (Latin)", value: "jv-latn" },
  { title: "Javanese (Aksara Jawa)", value: "jv-java" },
  { title: "Kabuverdianu", value: "kea" },
  { title: "Kabyle (Arabic)", value: "kab-arab" },
  { title: "Kabyle (Latin)", value: "kab-latn" },
  { title: "Kabyle (Tifinagh)", value: "kab-tfng" },
  { title: "Kalenjin", value: "kln" },
  { title: "Kamba", value: "kam" },
  { title: "Kannada", value: "kn" },
  { title: "Kanuri", value: "kr" },
  { title: "Kashmiri (Arabic)", value: "ks-arab" },
  { title: "Kashmiri (Devanagari)", value: "ks-deva" },
  { title: "Kashubian", value: "csb" },
  { title: "Kazakh (Cyrillic)", value: "kk-cyrl" },
  { title: "Kazakh (Latin)", value: "kk-latn" },
  { title: "Khmer", value: "km" },
  { title: "Kikuyu", value: "ki" },
  { title: "Kinyarwanda", value: "rw" },
  { title: "Kirundi", value: "rn" },
  { title: "Kiswahili/Swahili", value: "sw" },
  { title: "Komi", value: "kv" },
  { title: "Kongo", value: "kg" },
  { title: "Konkani", value: "kok" },
  { title: "Korean", value: "ko" },
  { title: "Koyra Chiini", value: "khq" },
  { title: "Koyraboro Senni", value: "ses" },
  { title: "Kurdish (Hawar)", value: "ku-latn" },
  { title: "Kurdish (Kurmanji)", value: "ku-cyrl" },
  { title: "Kurdish (Sorani)", value: "ku-arab" },
  { title: "Kwanyama", value: "kj" },
  { title: "Kyrgyz", value: "ky" },
  { title: "Langi", value: "lag" },
  { title: "Lao", value: "lo" },
  { title: "Latin", value: "la" },
  { title: "Latvian", value: "lv" },
  { title: "Limburgish", value: "li" },
  { title: "Lingala", value: "ln" },
  { title: "Lithuanian", value: "lt" },
  { title: "Luga-Katanga", value: "lu" },
  { title: "Luo", value: "luo" },
  { title: "Luxembourgish", value: "lb" },
  { title: "Macedonian", value: "mk" },
  { title: "Machame", value: "jmc" },
  { title: "Makonde", value: "kde" },
  { title: "Malagasy", value: "mg" },
  { title: "Malay", value: "ms" },
  { title: "Malay (Jawi)", value: "ms-arab" },
  { title: "Malayalam", value: "ml" },
  { title: "Maltese", value: "mt" },
  { title: "Manx Gaelic", value: "gv" },
  { title: "Marathi", value: "mr" },
  { title: "Marshallese", value: "mh" },
  { title: "Masai", value: "mas" },
  { title: "Meru", value: "mer" },
  { title: "Moldavian", value: "mo" },
  { title: "Mon", value: "mnw-mymr" },
  { title: "Mongolian (Cyrillic)", value: "mn-cyrl" },
  { title: "Mongolian (Traditional Script)", value: "mn-mong" },
  { title: "Morisyen", value: "mfe" },
  { title: "Māori", value: "mi" },
  { title: "Nama", value: "naq" },
  { title: "Nauru", value: "na" },
  { title: "Navajo", value: "nv" },
  { title: "Ndonga", value: "ng" },
  { title: "Nepali", value: "ne" },
  { title: "Northern Ndebele", value: "nd" },
  { title: "Norwegian", value: "no" },
  { title: "Norwegian Bokmål", value: "nb" },
  { title: "Norwegian Nynorsk", value: "nn" },
  { title: "Nuosu/Sichuan Yi", value: "ii" },
  { title: "Nyankole", value: "nyn" },
  { title: "Occitan", value: "oc" },
  { title: "Oriya", value: "or" },
  { title: "Oromo", value: "om" },
  { title: "Ossetian", value: "os" },
  { title: "Pashto", value: "ps" },
  { title: "Polish", value: "pl" },
  { title: "Portuguese", value: "pt" },
  { title: "Punjabi (Gurmukhi)", value: "pa-guru" },
  { title: "Punjabi (Shahmukhi)", value: "pa-arab" },
  { title: "Pāli", value: "pi" },
  { title: "Quechua", value: "qu" },
  { title: "Romansh", value: "rm" },
  { title: "Romanian", value: "ro" },
  { title: "Rombo", value: "rof" },
  { title: "Russian", value: "ru" },
  { title: "Rwa", value: "rwk" },
  { title: "Samburu", value: "saq" },
  { title: "Samoan", value: "sm" },
  { title: "Sango", value: "sg" },
  { title: "Sanskrit", value: "sa" },
  { title: "Saraiki (Arabic)", value: "skr-arab" },
  { title: "Saraiki (Devanagari)", value: "skr-deva" },
  { title: "Scottish Gaelic", value: "gd" },
  { title: "Sena", value: "seh" },
  { title: "Serbian (Cyrillic)", value: "sr-cyrl" },
  { title: "Serbian (Latin)", value: "sr-latn" },
  { title: "Serbo-Croatian", value: "sh" },
  { title: "Sesotho", value: "st" },
  { title: "Setswana", value: "tn" },
  { title: "Sgaw Karen", value: "ksw-mymr" },
  { title: "Shona", value: "sn" },
  { title: "Sindhi (Arabic)", value: "sd-arab" },
  { title: "Sindhi (Devanagari)", value: "sd-deva" },
  { title: "Sinhala", value: "si" },
  { title: "Siswati/Swati", value: "ss" },
  { title: "Slovak", value: "sk" },
  { title: "Slovenian", value: "sl" },
  { title: "Soga", value: "xog" },
  { title: "Somali", value: "so" },
  { title: "Southern Ndebele", value: "nr" },
  { title: "Spanish", value: "es" },
  { title: "Sundanese (Latin)", value: "su-latn" },
  { title: "Sundanese (Aksara Sunda)", value: "su-sund" },
  { title: "Swedish", value: "sv" },
  { title: "Swiss German", value: "gsw" },
  { title: "Sámi", value: "se" },
  { title: "Tachelhit (Arabic)", value: "shi-arab" },
  { title: "Tachelhit (Latin)", value: "shi-latn" },
  { title: "Tachelhit (Tifinagh)", value: "shi-tfng" },
  { title: "Tagalog", value: "tl" },
  { title: "Tahitian", value: "ty" },
  { title: "Taita", value: "dav" },
  { title: "Tajik", value: "tg" },
  { title: "Tamazight (Arabic)", value: "tzm-arab" },
  { title: "Tamazight (Latin)", value: "tzm-latn" },
  { title: "Tamazight (Tifinagh)", value: "tzm-tfng" },
  { title: "Tamil", value: "ta" },
  { title: "Tatar", value: "tt" },
  { title: "Telugu", value: "te" },
  { title: "Teso", value: "teo" },
  { title: "Thai", value: "th" },
  { title: "Tibetan", value: "bo" },
  { title: "Tigrinya", value: "ti" },
  { title: "Tongan", value: "to" },
  { title: "Tsonga", value: "ts" },
  { title: "Tuareg (Arabic)", value: "tmh-arab" },
  { title: "Tuareg (Latin)", value: "tmh-latn" },
  { title: "Tuareg (Tifinagh)", value: "tmh-tfng" },
  { title: "Turkish", value: "tr" },
  { title: "Turkmen", value: "tk" },
  { title: "Twi", value: "tw" },
  { title: "Ukrainian", value: "uk" },
  { title: "Urdu", value: "ur" },
  { title: "Uyghur (Arabic)", value: "ug-arab" },
  { title: "Uyghur (Cyrillic)", value: "ug-cyrl" },
  { title: "Uyghur (Latin)", value: "ug-latn" },
  { title: "Uzbek (Arabic)", value: "uz-arab" },
  { title: "Uzbek (Cyrillic)", value: "uz-cyrl" },
  { title: "Uzbek (Latin)", value: "uz-latn" },
  { title: "Venda", value: "ve" },
  { title: "Vietnamese", value: "vi" },
  { title: "Volapük", value: "vo" },
  { title: "Vunjo", value: "vun" },
  { title: "Walloon", value: "wa" },
  { title: "Welsh", value: "cy" },
  { title: "Western Frisian", value: "fy" },
  { title: "Wolof", value: "wo" },
  { title: "Wu", value: "wuu" },
  { title: "Xhosa", value: "xh" },
  { title: "Yiddish", value: "yi" },
  { title: "Yoruba", value: "yo" },
  { title: "Zhuang", value: "za" },
  { title: "Zulu", value: "zu" },
];

export const REGIONS = [
  { title: "Afghanistan", value: "AF" },
  { title: "Albania", value: "AL" },
  { title: "Algeria", value: "DZ" },
  { title: "American Samoa", value: "AS" },
  { title: "Andorra", value: "AD" },
  { title: "Angola", value: "AO" },
  { title: "Antarctica", value: "AQ" },
  { title: "Antigua and Barbuda", value: "AG" },
  { title: "Argentina", value: "AR" },
  { title: "Armenia", value: "AM" },
  { title: "Aruba", value: "AW" },
  { title: "Australia", value: "AU" },
  { title: "Austria", value: "AT" },
  { title: "Azerbaijan", value: "AZ" },
  { title: "Bahamas", value: "BS" },
  { title: "Bahrain", value: "BH" },
  { title: "Bangladesh", value: "BD" },
  { title: "Barbados", value: "BB" },
  { title: "Belarus", value: "BY" },
  { title: "Belgium", value: "BE" },
  { title: "Belize", value: "BZ" },
  { title: "Benin", value: "BJ" },
  { title: "Bermuda", value: "BM" },
  { title: "Bhutan", value: "BT" },
  { title: "Bolivia", value: "BO" },
  { title: "Bosnia and Herzegovina", value: "BA" },
  { title: "Botswana", value: "BW" },
  { title: "Bouvet Island", value: "BV" },
  { title: "Brazil", value: "BR" },
  { title: "British Indian Ocean Territory", value: "IO" },
  { title: "British Virgin Islands", value: "VG" },
  { title: "Brunei Darussalam", value: "BN" },
  { title: "Bulgaria", value: "BG" },
  { title: "Burkina Faso", value: "BF" },
  { title: "Burma/Myanmar", value: "MM" },
  { title: "Burundi", value: "BI" },
  { title: "Cambodia", value: "KH" },
  { title: "Cameroon", value: "CM" },
  { title: "Canada", value: "CA" },
  { title: "Cape Verde", value: "CV" },
  { title: "Cayman Islands", value: "KY" },
  { title: "Central African Republic", value: "CF" },
  { title: "Chad", value: "TD" },
  { title: "Chechnya", value: "CE" },
  { title: "Chile", value: "CL" },
  { title: "Christmas Islands", value: "CC" },
  { title: "Colombia", value: "CO" },
  { title: "Comoros", value: "KM" },
  { title: "Congo (Brazzaville)", value: "CG" },
  { title: "Congo (Kinshasa)", value: "CD" },
  { title: "Cook Islands", value: "CK" },
  { title: "Costa Rica", value: "CR" },
  { title: "Croatia", value: "HR" },
  { title: "Cuba", value: "CU" },
  { title: "Cyprus", value: "CY" },
  { title: "Czech Republic", value: "CZ" },
  { title: "Côte d’Ivoire/Ivory Coast", value: "CI" },
  { title: "Denmark", value: "DK" },
  { title: "Djibouti", value: "DJ" },
  { title: "Dominica", value: "DM" },
  { title: "Dominican Republic", value: "DO" },
  { title: "Ecuador", value: "EC" },
  { title: "Egypt", value: "EG" },
  { title: "El Salvador", value: "SV" },
  { title: "Equatorial Guinea", value: "GQ" },
  { title: "Eritrea", value: "ER" },
  { title: "Estonia", value: "EE" },
  { title: "Ethiopia", value: "ET" },
  { title: "European Union", value: "EU" },
  { title: "Falkland Islands/Malvinas", value: "FK" },
  { title: "Faroe Islands", value: "FO" },
  { title: "Fiji", value: "FJ" },
  { title: "Finland", value: "FI" },
  { title: "France", value: "FR" },
  { title: "France (Saint Barthélemy)", value: "BL" },
  { title: "French Guiana", value: "GF" },
  { title: "French Polinesia", value: "PF" },
  { title: "French Southern Territories", value: "TF" },
  { title: "Gabon", value: "GA" },
  { title: "Gambia", value: "GM" },
  { title: "Georgia", value: "GE" },
  { title: "Germany", value: "DE" },
  { title: "Ghana", value: "GH" },
  { title: "Gibraltar", value: "GI" },
  { title: "Greece", value: "GR" },
  { title: "Greenland", value: "GL" },
  { title: "Grenada", value: "GD" },
  { title: "Guadeloupe", value: "GP" },
  { title: "Guam", value: "GU" },
  { title: "Guatemala", value: "GT" },
  { title: "Guinea", value: "GN" },
  { title: "Guinea-Bissau", value: "GW" },
  { title: "Guyana", value: "GY" },
  { title: "Haiti", value: "HT" },
  { title: "Heard Island and McDonald Islands", value: "HM" },
  { title: "Holy See (Vatican)", value: "VA" },
  { title: "Honduras", value: "HN" },
  { title: "Hong Kong Special Administrative Region", value: "HK" },
  { title: "Hungary", value: "HU" },
  { title: "Iceland", value: "IS" },
  { title: "India", value: "IN" },
  { title: "Indonesia", value: "ID" },
  { title: "Iran", value: "IR" },
  { title: "Iraq", value: "IQ" },
  { title: "Ireland", value: "IE" },
  { title: "Israel", value: "IL" },
  { title: "Italy", value: "IT" },
  { title: "Jamaica", value: "JM" },
  { title: "Japan", value: "JP" },
  { title: "Jordan", value: "JO" },
  { title: "Kazakhstan", value: "KZ" },
  { title: "Kenya", value: "KE" },
  { title: "Kiribati", value: "KI" },
  { title: "Kosovo", value: "XK" },
  { title: "Kuwait", value: "KW" },
  { title: "Kyrgystan", value: "KG" },
  { title: "Laos", value: "LA" },
  { title: "Latin America", value: 419 },
  { title: "Latvia", value: "LV" },
  { title: "Lebanon", value: "LB" },
  { title: "Lesotho", value: "LS" },
  { title: "Liberia", value: "LR" },
  { title: "Libya", value: "LY" },
  { title: "Liechtenstein", value: "LI" },
  { title: "Lithuania", value: "LT" },
  { title: "Luxembourg", value: "LU" },
  { title: "Macao Special Administrative Region", value: "MO" },
  { title: "Macedonia", value: "MK" },
  { title: "Madagascar", value: "MG" },
  { title: "Mainland China (People’s Republic of China)", value: "CN" },
  { title: "Malawi", value: "MW" },
  { title: "Malaysia", value: "MY" },
  { title: "Maldives", value: "MV" },
  { title: "Mali", value: "ML" },
  { title: "Malta", value: "MT" },
  { title: "Marshall Islands", value: "MH" },
  { title: "Martinique", value: "MQ" },
  { title: "Mauritania", value: "MR" },
  { title: "Mauritius", value: "MU" },
  { title: "Mayotte", value: "YT" },
  { title: "Mexico", value: "MX" },
  { title: "Micronesia", value: "FM" },
  { title: "Moldova", value: "MD" },
  { title: "Monaco", value: "MC" },
  { title: "Mongolia", value: "MN" },
  { title: "Montenegro", value: "ME" },
  { title: "Montserrat", value: "MS" },
  { title: "Morocco", value: "MA" },
  { title: "Mozambique", value: "MZ" },
  { title: "Namibia", value: "NA" },
  { title: "Nauru", value: "NR" },
  { title: "Nepal", value: "NP" },
  { title: "Netherland", value: "NL" },
  { title: "Netherland Antilles", value: "AN" },
  { title: "New Caledonia", value: "NC" },
  { title: "New Zealand", value: "NZ" },
  { title: "Nicaragua", value: "NI" },
  { title: "Niger", value: "NE" },
  { title: "Nigeria", value: "NG" },
  { title: "Niue", value: "NU" },
  { title: "Norfolk Island", value: "NF" },
  { title: "North Korea", value: "KP" },
  { title: "Northern Mariana Islands", value: "MP" },
  { title: "Norway", value: "NO" },
  { title: "Oman", value: "OM" },
  { title: "Pakistan", value: "PK" },
  { title: "Palau", value: "PW" },
  { title: "Palestine", value: "PS" },
  { title: "Panama", value: "PA" },
  { title: "Papua New Guinea", value: "PG" },
  { title: "Paraguay", value: "PY" },
  { title: "Peru", value: "PE" },
  { title: "Philippines", value: "PH" },
  { title: "Pitcairn", value: "PN" },
  { title: "Poland", value: "PL" },
  { title: "Portugal", value: "PT" },
  { title: "Puerto Rico", value: "PR" },
  { title: "Qatar", value: "QA" },
  { title: "Romania", value: "RO" },
  { title: "Russia", value: "RU" },
  { title: "Rwanda", value: "RW" },
  { title: "Réunion", value: "RE" },
  { title: "Saint Helena", value: "SH" },
  { title: "Saint Kitts and Nevis", value: "KN" },
  { title: "Saint Lucia", value: "LC" },
  { title: "Saint Martin", value: "MF" },
  { title: "Saint Pierre and Miquelon", value: "PM" },
  { title: "Saint Vincent and the Grenadines", value: "VC" },
  { title: "Samoa", value: "WS" },
  { title: "San Marino", value: "SM" },
  { title: "Sao Tome and Principe", value: "ST" },
  { title: "Saudi Arabia", value: "SA" },
  { title: "Senegal", value: "SN" },
  { title: "Serbia", value: "RS" },
  { title: "Seychelles", value: "SC" },
  { title: "Sierra Leone", value: "SL" },
  { title: "Singapore", value: "SG" },
  { title: "Slovakia", value: "SK" },
  { title: "Slovenia", value: "SI" },
  { title: "Solomon Islands", value: "SB" },
  { title: "Somalia", value: "SO" },
  { title: "South Africa", value: "ZA" },
  { title: "South Georgia and the South Sandwich Islands", value: "GS" },
  { title: "South Korea", value: "KR" },
  { title: "South Sudan", value: "SS" },
  { title: "Spain", value: "ES" },
  { title: "Sri Lanka", value: "LK" },
  { title: "Sudan", value: "SD" },
  { title: "Suriname", value: "SR" },
  { title: "Svalbard and Jan Mayen", value: "SJ" },
  { title: "Swaziland", value: "SZ" },
  { title: "Sweden", value: "SE" },
  { title: "Switzerland", value: "CH" },
  { title: "Syria", value: "SY" },
  { title: "Taiwan (Republic of China)", value: "TW" },
  { title: "Tajikistan", value: "TJ" },
  { title: "Tanzania", value: "TZ" },
  { title: "Thailand", value: "TH" },
  { title: "Timor Leste", value: "TL" },
  { title: "Togo", value: "TG" },
  { title: "Tokelau", value: "TK" },
  { title: "Tonga", value: "TO" },
  { title: "Trinidad and Tobago", value: "TT" },
  { title: "Tunisia", value: "TN" },
  { title: "Turkmenistan", value: "TM" },
  { title: "Turks and Caicos Islands", value: "TC" },
  { title: "Tuvalu", value: "TV" },
  { title: "Türkiye", value: "TR" },
  { title: "U.S. Virgin Islands", value: "VI" },
  { title: "Uganda", value: "UG" },
  { title: "Ukraine", value: "UA" },
  { title: "United Arab Emirates", value: "AE" },
  { title: "United Kingdom", value: "GB" },
  { title: "United States of America", value: "US" },
  { title: "United States Minor Outlying Islands", value: "UM" },
  { title: "Uruguay", value: "UY" },
  { title: "Uzbekistan", value: "UZ" },
  { title: "Vanuatu", value: "VU" },
  { title: "Venezuela", value: "VE" },
  { title: "Việt Nam", value: "VN" },
  { title: "Wallis and Futuna", value: "WF" },
  { title: "Western Sahara", value: "EH" },
  { title: "Yemen", value: "YE" },
  { title: "Zambia", value: "ZM" },
  { title: "Zimbabwe", value: "ZW" },
];

export function getFlagEmoji(countryCode) {
  const countryCodeIsNumber = typeof countryCode === "number";
  return !countryCodeIsNumber
    ? countryCode
        .toUpperCase()
        .split("")
        .map(char => String.fromCodePoint(127397 + char.charCodeAt(0)))
        // .map(char => String.fromCodePoint(char.charCodeAt(0) + 0x1F1A5))
        .join("")
    : // .reduce((a, b) => `${a}${b}`)
      "";
}

export const CALENDAR_OPTIONS = [
  { title: "None", value: "" },
  { title: "Adlam Number", value: "nu-adlm" },
  { title: "Ahom Number", value: "nu-ahom" },
  { title: "Armenian Upper Case Number", value: "nu-armn" },
  { title: "Armenian Lower Case Number", value: "nu-armnlow" },
  { title: "Balinese Number", value: "nu-bali" },
  { title: "Balinese Hindu Calendar", value: "ca-indian" },
  { title: "Balinese Hindu Calendar, Balinese Number", value: "ca-indian-nu-bali" },
  { title: "Bengali Number", value: "nu-beng" },
  { title: "Bhaiksuki Number", value: "nu-bhks" },
  { title: "Brahmi Number", value: "nu-brah" },
  { title: "Chakma Number", value: "nu-cakm" },
  { title: "Cham Number", value: "nu-cham" },
  { title: "Coptic Calendar", value: "nu-copt" },
  { title: "Cyrillic Number", value: "nu-cyrl" },
  { title: "Devanagari Number", value: "nu-deva" },
  { title: "Dives Akuru Number", value: "nu-diak" },
  { title: "Eastern Arabic Number", value: "nu-arab" },
  { title: "Eastern Arabic Number (Farsi, Urdu)", value: "nu-arabext" },
  { title: "Ethiopian Number", value: "nu-ethi" },
  { title: "Ethiopic Amete Alem Calendar", value: "ca-ethioaa" },
  { title: "Ethiopic Amete Alem Calendar, Ethiopian Number", value: "ca-ethioaa-nu-ethi" },
  { title: "Ethiopic Amete Mihret Calendar", value: "ca-ethiopic" },
  { title: "Ethiopic Amete Mihret Calendar, Ethiopian Number", value: "ca-ethiopic-nu-ethi" },
  { title: "Garay Number", value: "nu-gara" },
  { title: "Georgian Number", value: "nu-geor" },
  { title: "Greek Upper Case Number", value: "nu-grek" },
  { title: "Greek Lower Case Number", value: "nu-greklow" },
  { title: "Gregorian Calendar", value: "ca-gregory" },
  { title: "Gregorian Calendar, Bengali Number", value: "ca-gregory-nu-beng" },
  { title: "Gregorian Calendar, Brahmi Number", value: "ca-gregory-nu-brah" },
  { title: "Gregorian Calendar, Devanagari Number", value: "ca-gregory-nu-deva" },
  { title: "Gregorian Calendar, Eastern Arabic Number", value: "ca-gregory-nu-arab" },
  {
    title: "Gregorian Calendar, Eastern Arabic Number (Farsi, Urdu)",
    value: "ca-gregory-nu-arabext",
  },
  { title: "Gregorian Calendar, Gujarati Number", value: "ca-gregory-nu-gujr" },
  { title: "Gregorian Calendar, Gunjala Gondi Number", value: "ca-gregory-nu-gong" },
  { title: "Gregorian Calendar, Gurmukhi Number", value: "ca-gregory-nu-guru" },
  { title: "Gregorian Calendar, Hanifi Rohingnya Number", value: "ca-gregory-nu-rohg" },
  { title: "Gregorian Calendar, Malayalam Number", value: "ca-gregory-nu-mlym" },
  { title: "Gregorian Calendar, Masala Gondi Number", value: "ca-gregory-nu-gonm" },
  { title: "Gregorian Calendar, Ol Chiki Number", value: "ca-gregory-nu-olck" },
  { title: "Gregorian Calendar, Oriya Number", value: "ca-gregory-nu-orya" },
  { title: "Gregorian Calendar, Sinhala Number", value: "ca-gregory-nu-sinh" },
  { title: "Gregorian Calendar, Sora Sompeng Number", value: "ca-gregory-nu-sora" },
  { title: "Gregorian Calendar, Tamil Number", value: "ca-gregory-nu-tamldec" },
  { title: "Gregorian Calendar, Telugu Number", value: "ca-gregory-nu-telu" },
  { title: "Gregorian Calendar, Thai Number", value: "ca-gregory-nu-thai" },
  { title: "Gujarati Number", value: "nu-gujr" },
  { title: "Gurung Khema Number", value: "nu-gukh" },
  { title: "Gurmukhi Number", value: "nu-guru" },
  { title: "Gunjala Gondi Number", value: "nu-gong" },
  { title: "Han Number", value: "nu-hanidays" },
  { title: "Hanifi Rohingya Number", value: "nu-rohg" },
  { title: "Hijri Calendar", value: "ca-islamic" },
  { title: "Hijri Calendar, Bengali Number", value: "ca-islamic-nu-beng" },
  { title: "Hijri Calendar, Brahmi Number", value: "ca-islamic-nu-brah" },
  { title: "Hijri Calendar, Devanagari Number", value: "ca-islamic-nu-deva" },
  { title: "Hijri Calendar, Eastern Arabic Number", value: "ca-islamic-nu-arab" },
  { title: "Hijri Calendar, Eastern Arabic Number (Farsi, Urdu)", value: "ca-islamic-nu-arabext" },
  { title: "Hijri Calendar, Gujarati Number", value: "ca-islamic-nu-gujr" },
  { title: "Hijri Calendar, Gunjala Gondi Number", value: "ca-islamic-nu-gong" },
  { title: "Hijri Calendar, Gurmukhi Number", value: "ca-islamic-nu-guru" },
  { title: "Hijri Calendar, Hanifi Rohingya Number", value: "ca-islamic-nu-rohg" },
  { title: "Hijri Calendar, Malayalam Number", value: "ca-islamic-nu-mlym" },
  { title: "Hijri Calendar, Masala Gondi Number", value: "ca-islamic-nu-gonm" },
  { title: "Hijri Calendar, Ol Chiki Number", value: "ca-islamic-nu-olck" },
  { title: "Hijri Calendar, Oriya Number", value: "ca-islamic-nu-orya" },
  { title: "Hijri Calendar, Sinhala Number", value: "ca-islamic-nu-sinh" },
  { title: "Hijri Calendar, Sora Sompeng Number", value: "ca-islamic-nu-sora" },
  { title: "Hijri Calendar, Tamil Number", value: "ca-islamic-nu-tamldec" },
  { title: "Hijri Calendar, Telugu Number", value: "ca-islamic-nu-telu" },
  { title: "Hijri Calendar, Thai Numbers", value: "ca-islamic-nu-thai" },
  { title: "ISO 8601 Calendar", value: "ca-iso8601" },
  { title: "Japanese Emperial Calendar", value: "ca-japanese" },
  { title: "Jewish Calendar", value: "ca-hebrew" },
  { title: "Jewish Calendar, Hebrew Numeral", value: "ca-hebrew-nu-hebr" },
  { title: "Khudawadi Number", value: "nu-sind" },
  { title: "Malayalam Number", value: "nu-mlym" },
  { title: "Masala Gondi Number", value: "nu-gonm" },
  { title: "Modi Number", value: "nu-modi" },
  { title: "Mongolian Number", value: "nu-mong" },
  { title: "Mroo Number", value: "nu-mroo" },
  { title: "Meitei Mayek Number", value: "nu-mtei" },
  { title: "Myanmar Number", value: "nu-mymr" },
  { title: "Nag Mundari Number", value: "nu-nagm" },
  { title: "New Tai Lüe Number", value: "nu-talu" },
  { title: "Newa Number", value: "nu-newa" },
  { title: "N’Ko Number", value: "nu-nkoo" },
  { title: "Ol Chiki Number", value: "nu-olck" },
  { title: "Ol Onal Number", value: "nu-onao" },
  { title: "Oriya Number", value: "nu-orya" },
  { title: "Osmanya Number", value: "nu-osma" },
  { title: "Persian Calendar", value: "ca-persian" },
  { title: "Roman Upper Case Number", value: "nu-roman" },
  { title: "Roman Lower Case Number", value: "nu-romanlow" },
  { title: "Saurashtra Number", value: "nu-saur" },
  { title: "Sharada Number", value: "nu-shrd" },
  { title: "Sinhala Number", value: "nu-sinh" },
  { title: "Sora Sompeng Number", value: "nu-sora" },
  { title: "Sundanese Number", value: "nu-sund" },
  { title: "Sunuwar Number", value: "nu-sunu" },
  { title: "Taiwanese R.O.C. Calendar", value: "ca-roc" },
  { title: "Taiwanese R.O.C. Calendar, Han Number", value: "ca-roc-nu-hanidays" },
  { title: "Takri Number", value: "nu-takr" },
  { title: "Tamil Number", value: "nu-tamldec" },
  { title: "Tangsa Number", value: "nu-tnsa" },
  { title: "Telugu Number", value: "nu-telu" },
  { title: "Thai Calendar", value: "ca-buddhist" },
  { title: "Thai Calendar, Thai Number", value: "ca-buddhist-nu-thai" },
  { title: "Thai Number", value: "nu-thai" },
  { title: "Tirhuta Number", value: "nu-tirh" },
  { title: "Tibetan Number", value: "nu-tibt" },
  { title: "Traditional Chinese Calendar", value: "ca-chinese" },
  { title: "Traditional Chinese Calendar, Han Number", value: "ca-chinese-nu-hanidays" },
  { title: "Traditional Indian Calendar", value: "ca-indian" },
  { title: "Traditional Indian Calendar, Arabic-Indic Number", value: "ca-indian-nu-arab" },
  { title: "Traditional Indian Calendar, Bengali Number", value: "ca-indian-nu-beng" },
  { title: "Traditional Indian Calendar, Brahmi Number", value: "ca-indian-nu-brah" },
  { title: "Traditional Indian Calendar, Devanagari Number", value: "ca-indian-nu-deva" },
  { title: "Traditional Indian Calendar, Gujarati Number", value: "ca-indian-nu-gujr" },
  { title: "Traditional Indian Calendar, Gunjala Gondi Number", value: "ca-indian-nu-gong" },
  { title: "Traditional Indian Calendar, Gurmukhi Number", value: "ca-indian-nu-guru" },
  { title: "Traditional Indian Calendar, Hanifi Rohngya Number", value: "ca-indian-nu-rohg" },
  { title: "Traditional Indian Calendar, Malayalam Number", value: "ca-indian-nu-mlym" },
  { title: "Traditional Indian Calendar, Masala Gondi Number", value: "ca-indian-nu-gonm" },
  { title: "Traditional Indian Calendar, Ol Chiki Number", value: "ca-indian-nu-olck" },
  { title: "Traditional Indian Calendar, Oriya Number", value: "ca-indian-nu-orya" },
  { title: "Traditional Indian Calendar, Sinhala Number", value: "ca-indian-nu-sinh" },
  { title: "Traditional Indian Calendar, Sora Sompeng Number", value: "ca-indian-nu-sora" },
  { title: "Traditional Indian Calendar, Tamil Number", value: "ca-indian-nu-tamldec" },
  { title: "Traditional Indian Calendar, Telugu Number", value: "ca-indian-nu-telu" },
  { title: "Traditional Indian Calendar, Thai Number", value: "ca-indian-nu-thai" },
  { title: "Traditional Indian Calendar, Urdu Number", value: "ca-indian-nu-arabext" },
  { title: "Traditional Korean Calendar", value: "ca-dangi" },
  { title: "Vai Number", value: "nu-vaii" },
  { title: "Warang Citi Number", value: "nu-wara" },
  { title: "Wancho Number", value: "nu-wcho" },
];
